(function(root){
'use strict';
const lessons=[
 {id:'introduce',title:'l1',goal:'g1',person:'Daniel',role:'Daniel · student',speakingPrompt:'Introduce yourself as a new student. Say your name, country and role. Ask your partner their name and country.',audioTitle:'Students in a new class',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953ca29a25e926ab54497e9_Listening%20A1.%20Lesson%202.%20Students%20in%20a%20new%20class.mp3',transcript:["Hello.","My name is Anna, and I want to tell you about my new language class.","I study Japanese at a language school in the city.","Our class is small. There are eight students.","Our teacher’s name is Mr Tanaka.","He is from Japan, and he is forty-five years old.","He is very kind and friendly.","He loves music, and sometimes he plays the guitar in class.","The students in my class are from different countries.","One student is Maria. She is from Mexico.","She is twenty years old, and she is a university student.","She likes dancing and music.","Another student is Paul. He is from Canada.","He is thirty years old, and he works as a waiter.","He likes football and video games.","We also have a student from France.","Her name is Silvie. She is a nurse, and she loves anime and Japan.","I really like my class.","The students are friendly, and the teacher is great.","I enjoy learning Japanese, and I am happy to be in this class."],vocabulary:[['class','класс'],['student','студент'],['teacher','учитель'],['friendly','дружелюбный'],['country','страна'],['nurse','медсестра']],examples:["Hi! I'm Anna.",'My name is Anna.',"I'm a student."],rules:['be','my','student'],items:[
  {id:'1-1',type:'choice',prompt:'You meet Anna for the first time. Choose a greeting.',options:['Hi!','Goodbye!'],answer:'Hi!',rule:'greeting',source:'new bridge'},
  {id:'1-2',type:'choice',prompt:'I ___ Anna.',options:['is','are','am'],answer:'am',rule:'be',source:'S1 adapted'},
  {id:'1-3',type:'choice',prompt:'___ name is Anna.',options:['I','My'],answer:'My',rule:'my',source:'S9.1 adapted'},
  {id:'1-4',type:'match',prompt:'Match the full forms with their short forms.',pairs:[['I am',"I'm"],['My name is',"My name's"]],rule:'short',source:'S1 adapted + bridge'},
  {id:'1-5',type:'order',prompt:'Introduce yourself as a student.',tokens:['student.','a',"I'm"],answer:"I'm a student.",rule:'student',source:'S1 adapted'},
  {id:'1-6',type:'input',prompt:'Correct the sentence: I student.',answers:['I am a student',"I'm a student"],rule:'student',source:'S1 adapted'},
  {id:'1-7',type:'input',prompt:'You are Daniel. Complete: I am ___ (or write the full sentence).',answers:['Daniel','I am Daniel',"I'm Daniel"],rule:'be',source:'S1 + bridge'},
  {id:'1-8',type:'choice',prompt:'Choose the correct sentence.',options:['She is from France.','She are from France.','She am from France.'],answer:'She is from France.',rule:'be',source:'to be practice'},
  {id:'1-10',type:'input',prompt:'Complete the sentence: I am ___ Armenia.',answers:['from'],modelAnswer:'I am from Armenia.',rule:'be',source:'guided gap-fill'}]},
 {id:'daily',title:'l2',goal:'g2',person:'Michael',role:'Michael · shop assistant',speakingPrompt:'Tell your partner about your job and weekday routine. Ask what they do and when they start their day.',audioTitle:'Tell me about your life',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953f72489bec422321a323b_speech_1767110387213.mp3',transcript:["Hello.","My name is Michael.","I am thirty years old.","I live in a small town near the sea.","I live in a flat with my wife.","We do not have children.","I work in a supermarket.","I am a shop assistant.","I help customers and work at the cash desk.","I like my job because my colleagues are friendly.","On weekdays, I wake up at six thirty.","I take a shower and get dressed.","Then I have breakfast at home.","I usually drink coffee and eat a sandwich.","I go to work by bike.","It takes about ten minutes.","I start work at eight o’clock.","After work, I go home and rest.","In the evening, I cook dinner with my wife.","We watch TV or talk about our day.","On weekends, I do not work.","I like walking near the sea.","Sometimes I meet my friends and play football.","I also like listening to music.","I am learning English now.","I study English at home.","I want to travel and meet new people in the future.","Thank you for listening."],vocabulary:[['weekday','будний день'],['supermarket','супермаркет'],['customer','клиент'],['cash desk','касса'],['colleague','коллега'],['future','будущее']],examples:['I work in a supermarket.','I usually drink coffee.','I go to work by bike.'],rules:['presentSimple','frequency','doQuestion'],items:[
  {id:'2-1',type:'choice',prompt:'Where does Michael work?',options:['In a café','In a supermarket','At a school'],answer:'In a supermarket',rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-2',type:'choice',prompt:'What time does Michael wake up on weekdays?',options:['At six thirty','At seven thirty','At eight o’clock'],answer:'At six thirty',rule:'frequency',source:'Listening A1 Tell me about your life'},
  {id:'2-3',type:'order',prompt:'Build the sentence about Michael’s transport.',tokens:['bike.','work','to','go','I','by'],answer:'I go to work by bike.',rule:'wordOrder',source:'Listening A1 Tell me about your life'},
  {id:'2-4',type:'input',prompt:'Complete: I usually drink ___ and eat a sandwich.',answers:['coffee'],rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-5',type:'choice',prompt:'Choose the correct negative sentence.',options:["We don't have children.","We doesn't have children.","We not have children."],answer:"We don't have children.",rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-6',type:'choice',prompt:'Choose the correct question about Michael’s routine.',options:['What time does he start work?','What time he starts work?','What time do he start work?'],answer:'What time does he start work?',rule:'doQuestion',source:'Listening A1 Tell me about your life'},
  {id:'2-7',type:'input',prompt:'Complete: On weekends, Michael ___ work.',answers:["doesn't",'does not'],rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-8',type:'order',prompt:'Put the words in order to describe a regular action.',tokens:['English.','study','I','every day'],answer:'I study English every day.',rule:'frequency',source:'guided transfer from Listening A1 Tell me about your life'}]},
 {id:'meet',title:'l3',goal:'g3',person:'Anna',role:'Anna · café worker',speakingPrompt:'Describe a typical day and what you do in your free time. Ask your partner about their evenings or weekends.',audioTitle:'My Daily Life',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/69538927b8f13a47a81c7924_Listening%20A1.%20Lesson%201.%20My%20daily%20life.mp3',transcript:["Hello.","My name is Anna.","I am twenty-six years old.","I live in a small city.","I live with my parents and my younger brother.","My family is very friendly.","I work in a café near my home.","I like my job because the people are nice.","Every day, I wake up at seven o’clock.","I wash my face and brush my teeth.","Then I have breakfast.","For breakfast, I usually drink coffee and eat toast.","Sometimes I eat eggs or fruit.","I leave home at eight o’clock.","I go to work by bus.","The bus ride takes about twenty minutes.","At work, I make coffee and serve customers.","I talk to people and smile a lot.","I finish work at four o’clock.","After work, I go home.","In the evening, I like to relax.","I watch TV or listen to music.","Sometimes I read a book.","I like reading simple stories.","I also like learning English.","On weekends, I do not work.","I meet my friends or stay at home.","We go for a walk or drink tea together.","I like weekends very much.","Thank you for listening."],vocabulary:[['routine','распорядок'],['café','кафе'],['customer','клиент'],['wake up','просыпаться'],['serve','обслуживать'],['relax','отдыхать']],examples:['I wake up at seven o’clock.','I go to work by bus.','I finish work at four.'],rules:['presentSimple','frequency','wordOrder'],items:[
  {id:'3-1',type:'choice',prompt:'Where does Anna work?',options:['In a café','In a supermarket','At a school'],answer:'In a café',rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-2',type:'input',prompt:'Complete: Anna is ___ years old.',answers:['twenty-six','26'],rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-3',type:'order',prompt:'Build the sentence about Anna’s transport.',tokens:['bus.','by','work','to','go','I'],answer:'I go to work by bus.',rule:'wordOrder',source:'Listening A1 My Daily Life'},
  {id:'3-4',type:'choice',prompt:'What time does Anna wake up?',options:['At six o’clock','At seven o’clock','At eight o’clock'],answer:'At seven o’clock',rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-5',type:'input',prompt:'Complete: For breakfast, Anna usually drinks ___.',answers:['coffee'],rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-6',type:'choice',prompt:'What time does Anna finish work?',options:['At two o’clock','At four o’clock','At eight o’clock'],answer:'At four o’clock',rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-7',type:'choice',prompt:'What does Anna do at weekends?',options:['She works in a café.','She meets friends or stays at home.','She goes to school.'],answer:'She meets friends or stays at home.',rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-8',type:'choice',prompt:'Choose the correct sentence about free time.',options:['She reads a book in the evening.','She read a book in the evening every day.','She is read a book in the evening.'],answer:'She reads a book in the evening.',rule:'presentSimple',source:'Present Simple practice'}]}
];
lessons[0].listeningItems=[
 {id:'1-l1',type:'choice',prompt:'Where is Mr Tanaka from?',options:['Japan','Canada','France'],answer:'Japan',rule:'listen',source:'Students in a new class'},
 {id:'1-l2',type:'choice',prompt:'How many students are in the class?',options:['Six','Eight','Ten'],answer:'Eight',rule:'listen',source:'Students in a new class'},
 {id:'1-l3',type:'choice',prompt:'Where is Maria from?',options:['Mexico','Japan','France'],answer:'Mexico',rule:'listen',source:'Students in a new class'},
 {id:'1-l4',type:'choice',prompt:'What does Paul do?',options:['He is a waiter.','He is a nurse.','He is a teacher.'],answer:'He is a waiter.',rule:'listen',source:'Students in a new class'},
 {id:'1-l5',type:'choice',prompt:'What instrument does Mr Tanaka sometimes play?',options:['The guitar','The piano','The violin'],answer:'The guitar',rule:'listen',source:'Students in a new class'},
 {id:'1-l6',type:'choice',prompt:'What does Silvie do?',options:['She is a nurse.','She is a student.','She is a waiter.'],answer:'She is a nurse.',rule:'listen',source:'Students in a new class'}
];
lessons[1].items=[
 {id:'2-1',type:'choice',prompt:'Choose the correct sentence.',options:['I work in a supermarket.','I works in a supermarket.','I am work in a supermarket.'],answer:'I work in a supermarket.',rule:'presentSimple',source:'Present Simple'},
 {id:'2-2',type:'choice',prompt:'Complete: Michael ___ at six thirty.',options:['wake up','wakes up','waking up'],answer:'wakes up',rule:'presentSimple',source:'Present Simple'},
 {id:'2-3',type:'order',prompt:'Build the sentence.',tokens:['coffee.','usually','drink','I'],answer:'I usually drink coffee.',rule:'frequency',source:'Present Simple'},
 {id:'2-4',type:'choice',prompt:'Choose the correct negative.',options:["We don't have children.","We doesn't have children.","We not have children."],answer:"We don't have children.",rule:'presentSimple',source:'Present Simple'},
 {id:'2-5',type:'choice',prompt:'Choose the correct question.',options:['What time does he start work?','What time he starts work?','What time do he start work?'],answer:'What time does he start work?',rule:'doQuestion',source:'Present Simple questions'},
 {id:'2-6',type:'input',prompt:'Complete: He ___ (work) in a supermarket.',answers:['works'],rule:'presentSimple',source:'Present Simple'},
 {id:'2-7',type:'choice',prompt:'Where does the frequency adverb go?',options:['I usually drink coffee.','I drink usually coffee.','Usually I coffee drink.'],answer:'I usually drink coffee.',rule:'frequency',source:'Adverbs of frequency'},
 {id:'2-8',type:'order',prompt:'Put the words in order to describe a regular action.',tokens:['English.','study','I','every day'],answer:'I study English every day.',rule:'frequency',source:'guided transfer from Listening A1 Tell me about your life'},
 {id:'2-9',type:'input',prompt:'Complete with a frequency word: I ___ study English.',answers:['always','usually','often','sometimes','rarely','never'],modelAnswer:'I usually study English.',rule:'frequency',source:'guided gap-fill'},
 {id:'2-10',type:'input',prompt:'Complete the question: Do you ___ English every day?',answers:['study','practice','learn'],modelAnswer:'Do you study English every day?',rule:'doQuestion',source:'guided gap-fill'}
];
lessons[1].listeningItems=[
 {id:'2-l1',type:'choice',prompt:'Where does Michael work?',options:['In a café','In a supermarket','At a school'],answer:'In a supermarket',rule:'listen',source:'Tell me about your life'},
 {id:'2-l2',type:'choice',prompt:'What time does Michael wake up on weekdays?',options:['At six thirty','At seven thirty','At eight o’clock'],answer:'At six thirty',rule:'listen',source:'Tell me about your life'},
 {id:'2-l3',type:'choice',prompt:'How does Michael go to work?',options:['By bike','By bus','By car'],answer:'By bike',rule:'listen',source:'Tell me about your life'},
 {id:'2-l4',type:'choice',prompt:'What does Michael usually have for breakfast?',options:['Coffee and a sandwich','Tea and toast','Eggs and fruit'],answer:'Coffee and a sandwich',rule:'listen',source:'Tell me about your life'},
 {id:'2-l5',type:'choice',prompt:'What does Michael want to do in the future?',options:['Travel and meet new people','Move to the city','Work in a café'],answer:'Travel and meet new people',rule:'listen',source:'Tell me about your life'}
];
lessons[2].items=[
 {id:'3-1',type:'choice',prompt:'Choose the correct sentence.',options:['Anna works in a café.','Anna work in a café.','Anna is work in a café.'],answer:'Anna works in a café.',rule:'presentSimple',source:'Present Simple'},
 {id:'3-2',type:'input',prompt:'Complete: Anna ___ up at seven o’clock.',answers:['wakes'],rule:'presentSimple',source:'Present Simple'},
 {id:'3-3',type:'order',prompt:'Build the sentence.',tokens:['bus.','by','work','to','go','I'],answer:'I go to work by bus.',rule:'wordOrder',source:'English word order'},
 {id:'3-4',type:'choice',prompt:'Choose the correct frequency sentence.',options:['She usually drinks coffee.','She drinks usually coffee.','Usually she coffee drinks.'],answer:'She usually drinks coffee.',rule:'frequency',source:'Adverbs of frequency'},
 {id:'3-5',type:'choice',prompt:'Choose the correct negative.',options:["Anna doesn't work at weekends.","Anna don't work at weekends.","Anna isn't work at weekends."],answer:"Anna doesn't work at weekends.",rule:'presentSimple',source:'Present Simple'},
 {id:'3-6',type:'choice',prompt:'Complete: ___ Anna read simple stories?',options:['Do','Does','Is'],answer:'Does',rule:'doQuestion',source:'Present Simple questions'},
 {id:'3-7',type:'input',prompt:'Complete: She ___ (watch) TV in the evening.',answers:['watches'],rule:'presentSimple',source:'Present Simple'},
 {id:'3-8',type:'choice',prompt:'Choose the correct sentence about free time.',options:['She reads a book in the evening.','She read a book in the evening every day.','She is read a book in the evening.'],answer:'She reads a book in the evening.',rule:'presentSimple',source:'Present Simple practice'},
 {id:'3-9',type:'input',prompt:'Complete the sentence: She ___ to work by bus.',answers:['goes','travels'],modelAnswer:'She goes to work by bus.',rule:'presentSimple',source:'guided gap-fill'},
 {id:'3-10',type:'input',prompt:'Complete the question: Do you ___ books in your free time?',answers:['read','buy','borrow'],modelAnswer:'Do you read books in your free time?',rule:'doQuestion',source:'guided gap-fill'}
];
lessons[2].listeningItems=[
 {id:'3-l1',type:'choice',prompt:'Where does Anna work?',options:['In a café','In a supermarket','At a school'],answer:'In a café',rule:'listen',source:'My Daily Life'},
 {id:'3-l2',type:'choice',prompt:'What time does Anna wake up?',options:['At six o’clock','At seven o’clock','At eight o’clock'],answer:'At seven o’clock',rule:'listen',source:'My Daily Life'},
 {id:'3-l3',type:'choice',prompt:'How does Anna go to work?',options:['By bus','By bike','By train'],answer:'By bus',rule:'listen',source:'My Daily Life'},
 {id:'3-l4',type:'choice',prompt:'What time does Anna finish work?',options:['At two o’clock','At four o’clock','At eight o’clock'],answer:'At four o’clock',rule:'listen',source:'My Daily Life'},
 {id:'3-l5',type:'choice',prompt:'What does Anna sometimes do at weekends?',options:['She meets her friends or stays at home.','She works in a café.','She goes to school.'],answer:'She meets her friends or stays at home.',rule:'listen',source:'My Daily Life'}
];
lessons.push(
 {id:'now',title:'l4',goal:'g4',person:'Tom',role:'Tom · at home',speakingPrompt:'Describe what you and the people around you are doing right now. Ask your partner: “What are you doing at the moment?”',audioTitle:'What we are doing right now',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953e18cc17165f5b98e0462_Listening%20A1.%20Lesson%203.%20What%20we%20are%20doing%20right%20now.mp3',transcript:['Hello.','My name is Tom.','I want to tell you what my family is doing right now.','Today we are all at home.','It is a quiet day, and everyone is busy.','My wife is in the living room.','She is sitting on the sofa and studying Spanish.','She is writing new words in her notebook and listening to a lesson on her phone.','She wants to learn Spanish because we are planning a trip next year.','My son is in the kitchen.','He is cooking lunch at the moment.','He is cutting vegetables and boiling pasta.','He likes cooking, and he often finds new recipes online.','My daughter is in her bedroom.','She is doing her homework.','She is reading a book and answering questions.','She is also listening to music while she is studying.','My father is outside.','He is washing the car in front of the house.','He is wearing headphones and listening to his favorite songs.','As for me, I am in my room.','I am drinking tea and working on my computer.','I am watching some old family videos and smiling a lot.','Everyone is doing something different, but we are all at home together.','It is a nice and relaxing day.','Thank you for listening.'],vocabulary:[['at the moment',''],['living room',''],['sofa',''],['notebook',''],['vegetables',''],['headphones','']],examples:['She is studying Spanish now.','They are cooking lunch.','I am drinking tea at the moment.'],rules:['presentContinuous','continuousNow'],items:[
  {id:'4-1',type:'choice',prompt:'Choose the action happening now.',options:['Tom is drinking tea.','Tom drinks tea every morning.','Tom drank tea yesterday.'],answer:'Tom is drinking tea.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-2',type:'input',prompt:'Complete: She ___ on the sofa now.',answers:['is sitting'],rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-3',type:'choice',prompt:'Complete: They ___ lunch at the moment.',options:['are cooking','is cooking','cook'],answer:'are cooking',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-4',type:'choice',prompt:'Choose the correct negative sentence.',options:['I am not watching TV now.','I not watching TV now.','I do not watching TV now.'],answer:'I am not watching TV now.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-5',type:'order',prompt:'Build a sentence about an action happening now.',tokens:['lunch.','cooking','is','He'],answer:'He is cooking lunch.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-6',type:'input',prompt:'Complete: We ___ listening to music now.',answers:['are'],modelAnswer:'We are listening to music now.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-7',type:'choice',prompt:'Choose the sentence about a temporary action today.',options:['I usually walk, but today I am taking the bus.','I usually walking, but today I take bus.','I am usually walk, but today taking the bus.'],answer:'I usually walk, but today I am taking the bus.',rule:'continuousNow',source:'Present Simple vs Present Continuous'},
  {id:'4-8',type:'choice',prompt:'Choose the correct question.',options:['What are they doing?','What they are doing?','What do they doing?'],answer:'What are they doing?',rule:'presentContinuous',source:'Present Continuous questions'},
  {id:'4-9',type:'input',prompt:'Complete: My father is ___ the car.',answers:['washing'],modelAnswer:'My father is washing the car.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-10',type:'choice',prompt:'Choose the correct sentence.',options:['She is reading a book now.','She reading a book now.','She does reading a book now.'],answer:'She is reading a book now.',rule:'presentContinuous',source:'Present Continuous'}
 ]},
 {id:'plans',title:'l5',goal:'g5',person:'Anna',role:'Anna · weekend plans',speakingPrompt:'Tell your partner three plans for this weekend. Ask: “What are you going to do?”',audioTitle:'Weekend plans',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695be23dcea4e43e7fe7e661_Listening%20A1%20Elementary.%20Weekend%20plans%20(Anna).mp3',transcript:['Hi. I’m Anna.','This weekend I have simple plans.','On Saturday morning, I’m going to clean my apartment and do the laundry.','Then I’m going to go to the supermarket and buy food for the week.','In the afternoon, I’m going to meet my friend in a café.','We’re going to drink coffee and talk.','In the evening, I’m going to cook pasta at home and watch a movie.','On Sunday, I’m going to sleep a little longer.','Then I’m going to take a walk in the park and listen to music.','If the weather is good, I’m going to take some photos.','I want a calm weekend.'],vocabulary:[['weekend',''],['do the laundry',''],['supermarket',''],['in the afternoon',''],['take a walk',''],['calm','']],examples:['I am going to meet my friend.','We are going to drink coffee.','She is going to take some photos.'],rules:['goingTo','goingToPlans'],items:[
  {id:'5-1',type:'choice',prompt:'Choose the correct plan for tomorrow.',options:['I am going to clean my apartment.','I going to clean my apartment.','I am going clean my apartment.'],answer:'I am going to clean my apartment.',rule:'goingTo',source:'Be going to'},
  {id:'5-2',type:'input',prompt:'Complete: She ___ going to meet her friend.',answers:['is'],modelAnswer:'She is going to meet her friend.',rule:'goingTo',source:'Be going to'},
  {id:'5-3',type:'choice',prompt:'Complete: We ___ going to cook dinner.',options:['are','is','am'],answer:'are',rule:'goingTo',source:'Be going to'},
  {id:'5-4',type:'choice',prompt:'Choose the correct negative.',options:['They are not going to work on Sunday.','They do not going to work on Sunday.','They not are going to work on Sunday.'],answer:'They are not going to work on Sunday.',rule:'goingTo',source:'Be going to'},
  {id:'5-5',type:'order',prompt:'Build Anna’s plan for Saturday.',tokens:['my','meet','friend.','to','going','am','I'],answer:'I am going to meet my friend.',rule:'goingTo',source:'Be going to'},
  {id:'5-6',type:'choice',prompt:'Choose the correct question about a plan.',options:['Are you going to take a walk?','Do you going to take a walk?','You are going to take a walk?'],answer:'Are you going to take a walk?',rule:'goingTo',source:'Be going to questions'},
  {id:'5-7',type:'input',prompt:'Complete: He is going to ___ a movie tonight.',answers:['watch'],modelAnswer:'He is going to watch a movie tonight.',rule:'goingTo',source:'Be going to'},
  {id:'5-8',type:'choice',prompt:'Choose the correct short answer: “Are they going to shop?”',options:['Yes, they are.','Yes, they do.','Yes, they going.'],answer:'Yes, they are.',rule:'goingTo',source:'Be going to'},
  {id:'5-9',type:'input',prompt:'Complete: I ___ going to listen to music.',answers:['am'],modelAnswer:'I am going to listen to music.',rule:'goingTo',source:'Be going to'},
  {id:'5-10',type:'choice',prompt:'Which sentence describes an intention decided before speaking?',options:['I am going to visit my friend on Saturday.','I visit my friend last Saturday.','I am visiting my friend every Saturday.'],answer:'I am going to visit my friend on Saturday.',rule:'goingToPlans',source:'Be going to'}
 ]},
 {id:'free-time',title:'l6',goal:'g6',person:'Anna and David',role:'Anna and David · free time',speakingPrompt:'Talk about two things you enjoy doing in your free time. Ask your partner: “What do you like doing after work?”',audioTitle:'Free time',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695a8a6c2b74305d156712cb_Listening%20A1%20Elementary.%20Free%20time%20(Anna).mp3',transcript:["Anna: Hello. My name is Anna.","Anna: In my free time, I like simple things.","Anna: After work, I usually go home and rest.","Anna: I often make tea and listen to music.","Anna: Sometimes I watch a short comedy on my phone.","Anna: On weekdays, I don’t go out a lot, because I feel tired.","Anna: But I always try to do one nice thing.","Anna: For example, I read an easy book for ten or fifteen minutes.","Anna: On Fridays, I sometimes meet my friend in a café.","Anna: We talk and drink coffee.","Anna: At the weekend, I have more free time.","Anna: I like walking in the park and taking photos.","Anna: If the weather is bad, I stay at home and cook pasta or soup.","Anna: Free time helps me feel happy and calm.","David: Hi. I’m David.","David: I work during the day, so my free time is in the evening.","David: After work, I often go to the gym.","David: I go there two or three times a week.","David: When I don’t go to the gym, I stay at home and play video games for a little while.","David: I also like cooking.","David: I usually make something easy, like eggs, rice, or chicken.","David: On some days, I call my parents and talk with them.","David: At the weekend, I meet my friends.","David: We sometimes play football in the park, or we go to a small restaurant.","David: I don’t like very noisy places. I prefer quiet time.","David: On Sunday, I often clean my room, do my shopping, and then relax.","David: For me, free time is important."],vocabulary:[['free time',''],['rest',''],['comedy',''],['take photos',''],['gym',''],['prefer','']],examples:['I enjoy reading simple stories.','She likes walking in the park.','He enjoys cooking at home.'],rules:['likeIng','enjoyIng'],items:[
  {id:'6-1',type:'choice',prompt:'Complete: I enjoy ___ simple stories.',options:['reading','read','to read'],answer:'reading',rule:'enjoyIng',source:'Verbs + -ing'},
  {id:'6-2',type:'input',prompt:'Complete: Anna likes ___ to music.',answers:['listening'],modelAnswer:'Anna likes listening to music.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-3',type:'choice',prompt:'Choose the correct sentence.',options:['David likes cooking.','David likes cook.','David likes to cooking.'],answer:'David likes cooking.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-4',type:'input',prompt:'Complete: We enjoy ___ football in the park.',answers:['playing'],modelAnswer:'We enjoy playing football in the park.',rule:'enjoyIng',source:'Verbs + -ing'},
  {id:'6-5',type:'choice',prompt:'Choose the correct negative.',options:['I don’t like waiting in long lines.','I don’t like wait in long lines.','I not like waiting in long lines.'],answer:'I don’t like waiting in long lines.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-6',type:'order',prompt:'Build a sentence about a hobby.',tokens:['at','cooking','likes','home.','David'],answer:'David likes cooking at home.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-7',type:'choice',prompt:'Complete: She doesn’t mind ___ a short book.',options:['reading','read','to reading'],answer:'reading',rule:'enjoyIng',source:'Verbs + -ing'},
  {id:'6-8',type:'input',prompt:'Complete: They love ___ photos in the park.',answers:['taking'],modelAnswer:'They love taking photos in the park.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-9',type:'choice',prompt:'Choose the correct question.',options:['Do you like walking in the park?','Are you like walking in the park?','Do you like walk in the park?'],answer:'Do you like walking in the park?',rule:'likeIng',source:'Present Simple questions + -ing'},
  {id:'6-10',type:'choice',prompt:'Choose the correct sentence.',options:['Anna enjoys making tea.','Anna enjoys make tea.','Anna enjoys to make tea.'],answer:'Anna enjoys making tea.',rule:'enjoyIng',source:'Verbs + -ing'}
 ]}
);
lessons[3].listeningItems=[
 {id:'4-l1',type:'choice',prompt:'What is Tom’s wife doing?',options:['She is studying Spanish.','She is cooking lunch.','She is washing the car.'],answer:'She is studying Spanish.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l2',type:'choice',prompt:'What is Tom’s son doing?',options:['He is cooking lunch.','He is reading a book.','He is listening to a lesson.'],answer:'He is cooking lunch.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l3',type:'choice',prompt:'What is Tom’s daughter doing?',options:['She is doing her homework.','She is washing the car.','She is making tea.'],answer:'She is doing her homework.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l4',type:'choice',prompt:'What is Tom’s father doing?',options:['He is washing the car.','He is writing new words.','He is cooking pasta.'],answer:'He is washing the car.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l5',type:'choice',prompt:'What is Tom doing?',options:['He is drinking tea and working on his computer.','He is playing football.','He is studying Spanish.'],answer:'He is drinking tea and working on his computer.',rule:'listen',source:'What we are doing right now'}
];
lessons[4].listeningItems=[
 {id:'5-l1',type:'choice',prompt:'What is Anna going to do on Saturday morning?',options:['Clean her apartment and do the laundry.','Meet her friend in a café.','Take a walk in the park.'],answer:'Clean her apartment and do the laundry.',rule:'listen',source:'Weekend plans'},
 {id:'5-l2',type:'choice',prompt:'Where is Anna going to meet her friend?',options:['In a café.','At the supermarket.','In the park.'],answer:'In a café.',rule:'listen',source:'Weekend plans'},
 {id:'5-l3',type:'choice',prompt:'What is Anna going to cook on Saturday evening?',options:['Pasta.','Soup.','Chicken and rice.'],answer:'Pasta.',rule:'listen',source:'Weekend plans'},
 {id:'5-l4',type:'choice',prompt:'What is Anna going to do on Sunday?',options:['Take a walk in the park.','Go to work.','Visit a museum.'],answer:'Take a walk in the park.',rule:'listen',source:'Weekend plans'},
 {id:'5-l5',type:'choice',prompt:'What will Anna do if the weather is good?',options:['Take some photos.','Stay at home.','Do the laundry.'],answer:'Take some photos.',rule:'listen',source:'Weekend plans'}
];
lessons[5].listeningItems=[
 {id:'6-l1',type:'choice',prompt:'What does Anna often do after work?',options:['Make tea and listen to music.','Go to the gym.','Play football.'],answer:'Make tea and listen to music.',rule:'listen',source:'Free time'},
 {id:'6-l2',type:'choice',prompt:'What does Anna like doing at the weekend?',options:['Walking in the park and taking photos.','Going to the gym.','Watching a long movie.'],answer:'Walking in the park and taking photos.',rule:'listen',source:'Free time'},
 {id:'6-l3',type:'choice',prompt:'What does David often do after work?',options:['Go to the gym.','Meet a friend in a café.','Read an easy book.'],answer:'Go to the gym.',rule:'listen',source:'Free time'},
 {id:'6-l4',type:'choice',prompt:'What does David like doing?',options:['Cooking.','Taking photos.','Reading in a café.'],answer:'Cooking.',rule:'listen',source:'Free time'},
 {id:'6-l5',type:'choice',prompt:'What kind of places does David prefer?',options:['Quiet places.','Very noisy places.','Busy shops.'],answer:'Quiet places.',rule:'listen',source:'Free time'}
];
const data={version:4,lessons};if(typeof module==='object'&&module.exports)module.exports=data;else root.EvoCourseBank=data;
})(typeof globalThis==='object'?globalThis:this);
