(function(root){
'use strict';
const lessons=[
 {id:'introduce',title:'l1',goal:'g1',person:'Daniel',role:'Daniel · student',speakingPrompt:'Introduce yourself as a new student. Say your name, country and role. Ask your partner their name and country.',audioTitle:'Students in a new class',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953ca29a25e926ab54497e9_Listening%20A1.%20Lesson%202.%20Students%20in%20a%20new%20class.mp3',transcript:["Hello.","My name is Anna, and I want to tell you about my new language class.","I study Japanese at a language school in the city.","Our class is small. There are eight students.","Our teacher’s name is Mr Tanaka.","He is from Japan, and he is forty-five years old.","He is very kind and friendly.","He loves music, and sometimes he plays the guitar in class.","The students in my class are from different countries.","One student is Maria. She is from Mexico.","She is twenty years old, and she is a university student.","She likes dancing and music.","Another student is Paul. He is from Canada.","He is thirty years old, and he works as a waiter.","He likes football and video games.","We also have a student from France.","Her name is Silvie. She is a nurse, and she loves anime and Japan.","I really like my class.","The students are friendly, and the teacher is great.","I enjoy learning Japanese, and I am happy to be in this class."],vocabulary:[['class','класс'],['student','студент'],['teacher','учитель'],['friendly','дружелюбный'],['country','страна'],['nurse','медсестра']],examples:["Hi! I'm Anna.",'My name is Anna.',"I'm a student."],rules:['be','my','student'],items:[
  {id:'1-1',type:'choice',prompt:'You meet Anna for the first time. Choose a greeting.',options:['Hi!','Goodbye!'],answer:'Hi!',rule:'greeting',source:'new bridge'},
  {id:'1-2',type:'choice',prompt:'I ___ Anna.',options:['is','are','am'],answer:'am',rule:'be',source:'S1 adapted'},
  {id:'1-3',type:'choice',prompt:'___ name is Anna.',options:['I','My'],answer:'My',rule:'my',source:'S9.1 adapted'},
  {id:'1-4',type:'match',prompt:'Match the full forms with their short forms.',pairs:[['I am',"I'm"],['My name is',"My name's"]],rule:'short',source:'S1 adapted + bridge'},
  {id:'1-5',type:'order',prompt:'Introduce yourself as a student.',tokens:['student.','a',"I'm"],answer:"I'm a student.",rule:'student',source:'S1 adapted'},
  {id:'1-6',type:'input',prompt:'Correct the sentence in the present tense: I student.',answers:['I am a student',"I'm a student"],rule:'student',source:'S1 adapted'},
  {id:'1-7',type:'input',prompt:'You are Daniel. Complete: I am ___ (or write the full sentence).',answers:['Daniel','I am Daniel',"I'm Daniel"],rule:'be',source:'S1 + bridge'},
  {id:'1-8',type:'choice',prompt:'Choose the correct sentence.',options:['She is from France.','She are from France.','She am from France.'],answer:'She is from France.',rule:'be',source:'to be practice'},
  {id:'1-10',type:'input',prompt:'Say where you come from. Complete: I am ___ Armenia.',answers:['from'],modelAnswer:'I am from Armenia.',rule:'be',source:'guided gap-fill'}]},
 {id:'daily',title:'l2',goal:'g2',person:'Michael',role:'Michael · shop assistant',speakingPrompt:'Tell your partner about your job and weekday routine. Ask what they do and when they start their day.',audioTitle:'Tell me about your life',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953f72489bec422321a323b_speech_1767110387213.mp3',transcript:["Hello.","My name is Michael.","I am thirty years old.","I live in a small town near the sea.","I live in a flat with my wife.","We do not have children.","I work in a supermarket.","I am a shop assistant.","I help customers and work at the cash desk.","I like my job because my colleagues are friendly.","On weekdays, I wake up at six thirty.","I take a shower and get dressed.","Then I have breakfast at home.","I usually drink coffee and eat a sandwich.","I go to work by bike.","It takes about ten minutes.","I start work at eight o’clock.","After work, I go home and rest.","In the evening, I cook dinner with my wife.","We watch TV or talk about our day.","On weekends, I do not work.","I like walking near the sea.","Sometimes I meet my friends and play football.","I also like listening to music.","I am learning English now.","I study English at home.","I want to travel and meet new people in the future.","Thank you for listening."],vocabulary:[['weekday','будний день'],['supermarket','супермаркет'],['customer','клиент'],['cash desk','касса'],['colleague','коллега'],['future','будущее']],examples:['I work in a supermarket.','I usually drink coffee.','I go to work by bike.'],rules:['presentSimple','frequency','doQuestion'],items:[
  {id:'2-1',type:'choice',prompt:'Where does Michael work?',options:['In a café','In a supermarket','At a school'],answer:'In a supermarket',rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-2',type:'choice',prompt:'What time does Michael wake up on weekdays?',options:['At six thirty','At seven thirty','At eight o’clock'],answer:'At six thirty',rule:'frequency',source:'Listening A1 Tell me about your life'},
  {id:'2-3',type:'order',prompt:'Build the sentence about Michael’s transport.',tokens:['bike.','work','to','go','I','by'],answer:'I go to work by bike.',rule:'wordOrder',source:'Listening A1 Tell me about your life'},
  {id:'2-4',type:'input',prompt:'Complete: I usually drink ___ and eat a sandwich.',answers:['coffee'],rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-5',type:'choice',prompt:'Choose the correct negative sentence.',options:["We don't have children.","We doesn't have children.","We not have children."],answer:"We don't have children.",rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-6',type:'choice',prompt:'Choose the correct question about Michael’s routine.',options:['What time does he start work?','What time he starts work?','What time do he start work?'],answer:'What time does he start work?',rule:'doQuestion',source:'Listening A1 Tell me about your life'},
  {id:'2-7',type:'input',prompt:'Complete: On weekends, Michael ___ work.',answers:["doesn't",'does not'],rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-8',type:'order',prompt:'Put the words in order to describe a regular action.',tokens:['English.','study','I','every day'],answer:'I study English every day.',rule:'frequency',source:'guided transfer from Listening A1 Tell me about your life'}]},
 {id:'meet',title:'l3',goal:'g3',person:'Anna',role:'Anna · café worker',speakingPrompt:'Describe a typical day and what you do in your free time. Ask your partner about their evenings or weekends.',audioTitle:'My Daily Life',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/69538927b8f13a47a81c7924_Listening%20A1.%20Lesson%201.%20My%20daily%20life.mp3',transcript:["Hello.","My name is Anna.","I am twenty-six years old.","I live in a small city.","I live with my parents and my younger brother.","My family is very friendly.","I work in a café near my home.","I like my job because the people are nice.","Every day, I wake up at seven o’clock.","I wash my face and brush my teeth.","Then I have breakfast.","For breakfast, I usually drink coffee and eat toast.","Sometimes I eat eggs or fruit.","I leave home at eight o’clock.","I go to work by bus.","The bus ride takes about twenty minutes.","At work, I make coffee and serve customers.","I talk to people and smile a lot.","I finish work at four o’clock.","After work, I go home.","In the evening, I like to relax.","I watch TV or listen to music.","Sometimes I read a book.","I like reading simple stories.","I also like learning English.","On weekends, I do not work.","I meet my friends or stay at home.","We go for a walk or drink tea together.","I like weekends very much.","Thank you for listening."],vocabulary:[['routine','распорядок'],['café','кафе'],['customer','клиент'],['wake up','просыпаться'],['serve','обслуживать'],['relax','отдыхать']],examples:['I wake up at seven o’clock.','I go to work by bus.','I finish work at four.'],rules:['presentSimple','frequency','wordOrder'],items:[
  {id:'3-1',type:'choice',prompt:'Where does Anna work?',options:['In a café','In a supermarket','At a school'],answer:'In a café',rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-2',type:'input',prompt:'Complete: Anna is ___ years old.',answers:['twenty-six','26'],rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-3',type:'order',prompt:'Build the sentence about Anna’s transport.',tokens:['bus.','by','work','to','go','I'],answer:'I go to work by bus.',rule:'wordOrder',source:'Listening A1 My Daily Life'},
  {id:'3-4',type:'choice',prompt:'What time does Anna wake up?',options:['At six o’clock','At seven o’clock','At eight o’clock'],answer:'At seven o’clock',rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-5',type:'input',prompt:'Complete: For breakfast, Anna usually drinks ___.',answers:['coffee'],rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-6',type:'choice',prompt:'What time does Anna finish work?',options:['At two o’clock','At four o’clock','At eight o’clock'],answer:'At four o’clock',rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-7',type:'choice',prompt:'What does Anna do at weekends?',options:['She works in a café.','She meets friends or stays at home.','She goes to school.'],answer:'She meets friends or stays at home.',rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-8',type:'choice',prompt:'Choose the correct sentence about free time.',options:['She reads a book in the evening.','She read a book in the evening every day.','She is read a book in the evening.'],answer:'She reads a book in the evening.',rule:'presentSimple',source:'Present Simple practice'}]}
];
lessons[0].listeningItems=[
 {id:'1-l1',type:'choice',prompt:'Where is Mr Tanaka from?',options:['Japan','Canada','France'],answer:'Japan',rule:'listen',source:'Students in a new class'},
 {id:'1-l2',type:'choice',prompt:'How many students are in the class?',options:['Six','Eight','Ten'],answer:'Eight',rule:'listen',source:'Students in a new class'},
 {id:'1-l3',type:'choice',prompt:'Where is Maria from?',options:['Mexico','Japan','France'],answer:'Mexico',rule:'listen',source:'Students in a new class'},
 {id:'1-l4',type:'choice',prompt:'What does Paul do?',options:['He is a waiter.','He is a nurse.','He is a teacher.'],answer:'He is a waiter.',rule:'listen',source:'Students in a new class'},
 {id:'1-l5',type:'choice',prompt:'What instrument does Mr Tanaka sometimes play?',options:['The guitar','The piano','The violin'],answer:'The guitar',rule:'listen',source:'Students in a new class'},
 {id:'1-l6',type:'choice',prompt:'What does Silvie do?',options:['She is a nurse.','She is a student.','She is a waiter.'],answer:'She is a nurse.',rule:'listen',source:'Students in a new class'}
];
lessons[1].items=[
 {id:'2-1',type:'choice',prompt:'Choose the correct sentence.',options:['I work in a supermarket.','I works in a supermarket.','I am work in a supermarket.'],answer:'I work in a supermarket.',rule:'presentSimple',source:'Present Simple'},
 {id:'2-2',type:'choice',prompt:'Complete: Michael ___ at six thirty.',options:['wake up','wakes up','waking up'],answer:'wakes up',rule:'presentSimple',source:'Present Simple'},
 {id:'2-3',type:'order',prompt:'Build the sentence.',tokens:['coffee.','usually','drink','I'],answer:'I usually drink coffee.',rule:'frequency',source:'Present Simple'},
 {id:'2-4',type:'choice',prompt:'Choose the correct negative.',options:["We don't have children.","We doesn't have children.","We not have children."],answer:"We don't have children.",rule:'presentSimple',source:'Present Simple'},
 {id:'2-5',type:'choice',prompt:'Choose the correct question.',options:['What time does he start work?','What time he starts work?','What time do he start work?'],answer:'What time does he start work?',rule:'doQuestion',source:'Present Simple questions'},
 {id:'2-6',type:'input',prompt:'Complete: He ___ (work) in a supermarket.',answers:['works'],rule:'presentSimple',source:'Present Simple'},
 {id:'2-7',type:'choice',prompt:'Where does the frequency adverb go?',options:['I usually drink coffee.','I drink usually coffee.','Usually I coffee drink.'],answer:'I usually drink coffee.',rule:'frequency',source:'Adverbs of frequency'},
 {id:'2-8',type:'order',prompt:'Put the words in order to describe a regular action.',tokens:['English.','study','I','every day'],answer:'I study English every day.',rule:'frequency',source:'guided transfer from Listening A1 Tell me about your life'},
 {id:'2-9',type:'input',prompt:'Use the frequency adverb meaning 100% of the time: I ___ study English.',answers:['always'],modelAnswer:'I always study English.',rule:'frequency',source:'guided gap-fill'},
 {id:'2-10',type:'input',prompt:'Use study in this question: Do you ___ English every day?',answers:['study'],modelAnswer:'Do you study English every day?',rule:'doQuestion',source:'guided gap-fill'}
];
lessons[1].listeningItems=[
 {id:'2-l1',type:'choice',prompt:'Where does Michael work?',options:['In a café','In a supermarket','At a school'],answer:'In a supermarket',rule:'listen',source:'Tell me about your life'},
 {id:'2-l2',type:'choice',prompt:'What time does Michael wake up on weekdays?',options:['At six thirty','At seven thirty','At eight o’clock'],answer:'At six thirty',rule:'listen',source:'Tell me about your life'},
 {id:'2-l3',type:'choice',prompt:'How does Michael go to work?',options:['By bike','By bus','By car'],answer:'By bike',rule:'listen',source:'Tell me about your life'},
 {id:'2-l4',type:'choice',prompt:'What does Michael usually have for breakfast?',options:['Coffee and a sandwich','Tea and toast','Eggs and fruit'],answer:'Coffee and a sandwich',rule:'listen',source:'Tell me about your life'},
 {id:'2-l5',type:'choice',prompt:'What does Michael want to do in the future?',options:['Travel and meet new people','Move to the city','Work in a café'],answer:'Travel and meet new people',rule:'listen',source:'Tell me about your life'}
];
lessons[2].items=[
 {id:'3-1',type:'choice',prompt:'Choose the correct sentence.',options:['Anna works in a café.','Anna work in a café.','Anna is work in a café.'],answer:'Anna works in a café.',rule:'presentSimple',source:'Present Simple'},
 {id:'3-2',type:'input',prompt:'Use wake up in the Present Simple: Anna ___ up at seven o’clock.',answers:['wakes'],modelAnswer:'Anna wakes up at seven o’clock.',rule:'presentSimple',source:'Present Simple'},
 {id:'3-3',type:'order',prompt:'Build the sentence.',tokens:['bus.','by','work','to','go','I'],answer:'I go to work by bus.',rule:'wordOrder',source:'English word order'},
 {id:'3-4',type:'choice',prompt:'Choose the correct frequency sentence.',options:['She usually drinks coffee.','She drinks usually coffee.','Usually she coffee drinks.'],answer:'She usually drinks coffee.',rule:'frequency',source:'Adverbs of frequency'},
 {id:'3-5',type:'choice',prompt:'Choose the correct negative.',options:["Anna doesn't work at weekends.","Anna don't work at weekends.","Anna isn't work at weekends."],answer:"Anna doesn't work at weekends.",rule:'presentSimple',source:'Present Simple'},
 {id:'3-6',type:'choice',prompt:'Complete: ___ Anna read simple stories?',options:['Do','Does','Is'],answer:'Does',rule:'doQuestion',source:'Present Simple questions'},
 {id:'3-7',type:'input',prompt:'Complete: She ___ (watch) TV in the evening.',answers:['watches'],rule:'presentSimple',source:'Present Simple'},
 {id:'3-8',type:'choice',prompt:'Choose the correct sentence about free time.',options:['She reads a book in the evening.','She read a book in the evening every day.','She is read a book in the evening.'],answer:'She reads a book in the evening.',rule:'presentSimple',source:'Present Simple practice'},
 {id:'3-9',type:'input',prompt:'Use go in the Present Simple: She ___ to work by bus.',answers:['goes'],modelAnswer:'She goes to work by bus.',rule:'presentSimple',source:'guided gap-fill'},
 {id:'3-10',type:'input',prompt:'Use read in this question: Do you ___ books in your free time?',answers:['read'],modelAnswer:'Do you read books in your free time?',rule:'doQuestion',source:'guided gap-fill'}
];
lessons[2].listeningItems=[
 {id:'3-l1',type:'choice',prompt:'Where does Anna work?',options:['In a café','In a supermarket','At a school'],answer:'In a café',rule:'listen',source:'My Daily Life'},
 {id:'3-l2',type:'choice',prompt:'What time does Anna wake up?',options:['At six o’clock','At seven o’clock','At eight o’clock'],answer:'At seven o’clock',rule:'listen',source:'My Daily Life'},
 {id:'3-l3',type:'choice',prompt:'How does Anna go to work?',options:['By bus','By bike','By train'],answer:'By bus',rule:'listen',source:'My Daily Life'},
 {id:'3-l4',type:'choice',prompt:'What time does Anna finish work?',options:['At two o’clock','At four o’clock','At eight o’clock'],answer:'At four o’clock',rule:'listen',source:'My Daily Life'},
 {id:'3-l5',type:'choice',prompt:'What does Anna sometimes do at weekends?',options:['She meets her friends or stays at home.','She works in a café.','She goes to school.'],answer:'She meets her friends or stays at home.',rule:'listen',source:'My Daily Life'}
];
lessons.push(
 {id:'now',title:'l4',goal:'g4',person:'Tom',role:'Tom · at home',speakingPrompt:'Describe what you and the people around you are doing right now. Ask your partner: “What are you doing at the moment?”',audioTitle:'What we are doing right now',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953e18cc17165f5b98e0462_Listening%20A1.%20Lesson%203.%20What%20we%20are%20doing%20right%20now.mp3',transcript:['Hello.','My name is Tom.','I want to tell you what my family is doing right now.','Today we are all at home.','It is a quiet day, and everyone is busy.','My wife is in the living room.','She is sitting on the sofa and studying Spanish.','She is writing new words in her notebook and listening to a lesson on her phone.','She wants to learn Spanish because we are planning a trip next year.','My son is in the kitchen.','He is cooking lunch at the moment.','He is cutting vegetables and boiling pasta.','He likes cooking, and he often finds new recipes online.','My daughter is in her bedroom.','She is doing her homework.','She is reading a book and answering questions.','She is also listening to music while she is studying.','My father is outside.','He is washing the car in front of the house.','He is wearing headphones and listening to his favorite songs.','As for me, I am in my room.','I am drinking tea and working on my computer.','I am watching some old family videos and smiling a lot.','Everyone is doing something different, but we are all at home together.','It is a nice and relaxing day.','Thank you for listening.'],vocabulary:[['at the moment',''],['living room',''],['sofa',''],['notebook',''],['vegetables',''],['headphones','']],examples:['She is studying Spanish now.','They are cooking lunch.','I am drinking tea at the moment.'],rules:['presentContinuous','continuousNow'],items:[
  {id:'4-1',type:'choice',prompt:'Choose the action happening now.',options:['Tom is drinking tea.','Tom drinks tea every morning.','Tom drank tea yesterday.'],answer:'Tom is drinking tea.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-2',type:'input',prompt:'Use sit in the Present Continuous: She ___ on the sofa now.',answers:['is sitting'],modelAnswer:'She is sitting on the sofa now.',rule:'continuousSpelling',source:'Present Continuous'},
  {id:'4-3',type:'choice',prompt:'Complete: They ___ lunch at the moment.',options:['are cooking','is cooking','cook'],answer:'are cooking',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-4',type:'choice',prompt:'Choose the correct negative sentence.',options:['I am not watching TV now.','I not watching TV now.','I do not watching TV now.'],answer:'I am not watching TV now.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-5',type:'order',prompt:'Build a sentence about an action happening now.',tokens:['lunch.','cooking','is','He'],answer:'He is cooking lunch.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-6',type:'input',prompt:'Complete: We ___ listening to music now.',answers:['are'],modelAnswer:'We are listening to music now.',rule:'presentContinuous',source:'Present Continuous'},
  {id:'4-7',type:'choice',prompt:'Choose the sentence about a temporary action today.',options:['I usually walk, but today I am taking the bus.','I usually walking, but today I take bus.','I am usually walk, but today taking the bus.'],answer:'I usually walk, but today I am taking the bus.',rule:'continuousNow',source:'Present Simple vs Present Continuous'},
  {id:'4-8',type:'choice',prompt:'Choose the correct question.',options:['What are they doing?','What they are doing?','What do they doing?'],answer:'What are they doing?',rule:'presentContinuous',source:'Present Continuous questions'},
  {id:'4-9',type:'input',prompt:'Use wash in the Present Continuous: My father is ___ the car.',answers:['washing'],modelAnswer:'My father is washing the car.',rule:'continuousSpelling',source:'Present Continuous'},
  {id:'4-10',type:'choice',prompt:'Choose the correct sentence.',options:['She is reading a book now.','She reading a book now.','She does reading a book now.'],answer:'She is reading a book now.',rule:'presentContinuous',source:'Present Continuous'}
 ]},
 {id:'plans',title:'l5',goal:'g5',person:'Anna',role:'Anna · weekend plans',speakingPrompt:'Tell your partner three plans for this weekend. Ask: “What are you going to do?”',audioTitle:'Weekend plans',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695be23dcea4e43e7fe7e661_Listening%20A1%20Elementary.%20Weekend%20plans%20(Anna).mp3',transcript:['Hi. I’m Anna.','This weekend I have simple plans.','On Saturday morning, I’m going to clean my apartment and do the laundry.','Then I’m going to go to the supermarket and buy food for the week.','In the afternoon, I’m going to meet my friend in a café.','We’re going to drink coffee and talk.','In the evening, I’m going to cook pasta at home and watch a movie.','On Sunday, I’m going to sleep a little longer.','Then I’m going to take a walk in the park and listen to music.','If the weather is good, I’m going to take some photos.','I want a calm weekend.'],vocabulary:[['weekend',''],['do the laundry',''],['supermarket',''],['in the afternoon',''],['take a walk',''],['calm','']],examples:['I am going to meet my friend.','We are going to drink coffee.','She is going to take some photos.'],rules:['goingTo','goingToPlans'],items:[
  {id:'5-1',type:'choice',prompt:'Choose the correct plan for tomorrow.',options:['I am going to clean my apartment.','I going to clean my apartment.','I am going clean my apartment.'],answer:'I am going to clean my apartment.',rule:'goingTo',source:'Be going to'},
  {id:'5-2',type:'input',prompt:'Complete: She ___ going to meet her friend.',answers:['is'],modelAnswer:'She is going to meet her friend.',rule:'goingTo',source:'Be going to'},
  {id:'5-3',type:'choice',prompt:'Complete: We ___ going to cook dinner.',options:['are','is','am'],answer:'are',rule:'goingTo',source:'Be going to'},
  {id:'5-4',type:'choice',prompt:'Choose the correct negative.',options:['They are not going to work on Sunday.','They do not going to work on Sunday.','They not are going to work on Sunday.'],answer:'They are not going to work on Sunday.',rule:'goingTo',source:'Be going to'},
  {id:'5-5',type:'order',prompt:'Build Anna’s plan for Saturday.',tokens:['my','meet','friend.','to','going','am','I'],answer:'I am going to meet my friend.',rule:'goingTo',source:'Be going to'},
  {id:'5-6',type:'choice',prompt:'Choose the standard yes/no question about a plan.',options:['Are you going to take a walk?','Do you going to take a walk?','You are going to take a walk?'],answer:'Are you going to take a walk?',rule:'goingTo',source:'Be going to questions'},
  {id:'5-7',type:'input',prompt:'Use watch after going to: He is going to ___ a movie tonight.',answers:['watch'],modelAnswer:'He is going to watch a movie tonight.',rule:'goingTo',source:'Be going to'},
  {id:'5-8',type:'choice',prompt:'Choose the correct short answer: “Are they going to shop?”',options:['Yes, they are.','Yes, they do.','Yes, they going.'],answer:'Yes, they are.',rule:'goingTo',source:'Be going to'},
  {id:'5-9',type:'input',prompt:'Complete: I ___ going to listen to music.',answers:['am'],modelAnswer:'I am going to listen to music.',rule:'goingTo',source:'Be going to'},
  {id:'5-10',type:'choice',prompt:'Which sentence describes an intention decided before speaking?',options:['I am going to visit my friend on Saturday.','I visit my friend last Saturday.','I am visiting my friend every Saturday.'],answer:'I am going to visit my friend on Saturday.',rule:'goingToPlans',source:'Be going to'}
 ]},
 {id:'free-time',title:'l6',goal:'g6',person:'Anna',role:'Anna · free time',speakingPrompt:'Talk about two things you enjoy doing in your free time. Ask your partner: “What do you like doing after work?”',audioTitle:'Free time — Anna',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695a8a6c2b74305d156712cb_Listening%20A1%20Elementary.%20Free%20time%20(Anna).mp3',transcript:["Hello. My name is Anna.","In my free time, I like simple things.","After work, I usually go home and rest.","I often make tea and listen to music.","Sometimes I watch a short comedy on my phone.","On weekdays, I don’t go out a lot, because I feel tired.","But I always try to do one nice thing.","For example, I read an easy book for ten or fifteen minutes.","On Fridays, I sometimes meet my friend in a café.","We talk and drink coffee.","At the weekend, I have more free time.","I like walking in the park and taking photos.","If the weather is bad, I stay at home and cook pasta or soup.","Free time helps me feel happy and calm."],vocabulary:[['free time',''],['rest',''],['comedy',''],['take photos',''],['café',''],['calm','']],examples:['I enjoy reading simple stories.','She likes walking in the park.','I like taking photos.'],rules:['likeIng','enjoyIng'],items:[
  {id:'6-1',type:'choice',prompt:'Complete: I enjoy ___ simple stories.',options:['reading','read','to read'],answer:'reading',rule:'enjoyIng',source:'Verbs + -ing'},
  {id:'6-2',type:'input',prompt:'Use listen after likes: Anna likes ___ to music.',answers:['listening'],modelAnswer:'Anna likes listening to music.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-3',type:'choice',prompt:'Choose the correct sentence.',options:['Anna likes taking photos.','Anna likes take photos.','Anna likes to taking photos.'],answer:'Anna likes taking photos.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-4',type:'input',prompt:'Use drink after enjoy: We enjoy ___ coffee in a café.',answers:['drinking'],modelAnswer:'We enjoy drinking coffee in a café.',rule:'enjoyIng',source:'Verbs + -ing'},
  {id:'6-5',type:'choice',prompt:'Choose the correct negative.',options:['I don’t like waiting in long lines.','I don’t like wait in long lines.','I not like waiting in long lines.'],answer:'I don’t like waiting in long lines.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-6',type:'order',prompt:'Build a sentence about Anna’s free time.',tokens:['the','walking','likes','park.','Anna','in'],answer:'Anna likes walking in the park.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-7',type:'choice',prompt:'Complete: She doesn’t mind ___ a short book.',options:['reading','read','to reading'],answer:'reading',rule:'enjoyIng',source:'Verbs + -ing'},
  {id:'6-8',type:'input',prompt:'Use take after like: I like ___ photos in the park.',answers:['taking'],modelAnswer:'I like taking photos in the park.',rule:'likeIng',source:'Verbs + -ing'},
  {id:'6-9',type:'choice',prompt:'Choose the correct question.',options:['Do you like walking in the park?','Are you like walking in the park?','Do you like walk in the park?'],answer:'Do you like walking in the park?',rule:'likeIng',source:'Present Simple questions + -ing'},
  {id:'6-10',type:'choice',prompt:'Choose the correct sentence.',options:['Anna enjoys reading easy books.','Anna enjoys read easy books.','Anna enjoys to read easy books.'],answer:'Anna enjoys reading easy books.',rule:'enjoyIng',source:'Verbs + -ing'}
 ]}
);
lessons[3].listeningItems=[
 {id:'4-l1',type:'choice',prompt:'What is Tom’s wife doing?',options:['She is studying Spanish.','She is cooking lunch.','She is washing the car.'],answer:'She is studying Spanish.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l2',type:'choice',prompt:'What is Tom’s son doing?',options:['He is cooking lunch.','He is reading a book.','He is listening to a lesson.'],answer:'He is cooking lunch.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l3',type:'choice',prompt:'What is Tom’s daughter doing?',options:['She is doing her homework.','She is washing the car.','She is making tea.'],answer:'She is doing her homework.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l4',type:'choice',prompt:'What is Tom’s father doing?',options:['He is washing the car.','He is writing new words.','He is cooking pasta.'],answer:'He is washing the car.',rule:'listen',source:'What we are doing right now'},
 {id:'4-l5',type:'choice',prompt:'What is Tom doing?',options:['He is drinking tea and working on his computer.','He is playing football.','He is studying Spanish.'],answer:'He is drinking tea and working on his computer.',rule:'listen',source:'What we are doing right now'}
];
lessons[4].listeningItems=[
 {id:'5-l1',type:'choice',prompt:'What is Anna going to do on Saturday morning?',options:['Clean her apartment and do the laundry.','Meet her friend in a café.','Take a walk in the park.'],answer:'Clean her apartment and do the laundry.',rule:'listen',source:'Weekend plans'},
 {id:'5-l2',type:'choice',prompt:'Where is Anna going to meet her friend?',options:['In a café.','At the supermarket.','In the park.'],answer:'In a café.',rule:'listen',source:'Weekend plans'},
 {id:'5-l3',type:'choice',prompt:'What is Anna going to cook on Saturday evening?',options:['Pasta.','Soup.','Chicken and rice.'],answer:'Pasta.',rule:'listen',source:'Weekend plans'},
 {id:'5-l4',type:'choice',prompt:'What is Anna going to do on Sunday?',options:['Take a walk in the park.','Go to work.','Visit a museum.'],answer:'Take a walk in the park.',rule:'listen',source:'Weekend plans'},
 {id:'5-l5',type:'choice',prompt:'What will Anna do if the weather is good?',options:['Take some photos.','Stay at home.','Do the laundry.'],answer:'Take some photos.',rule:'listen',source:'Weekend plans'}
];
lessons[5].listeningItems=[
 {id:'6-l1',type:'choice',prompt:'What does Anna often do after work?',options:['Make tea and listen to music.','Go to the gym.','Play football.'],answer:'Make tea and listen to music.',rule:'listen',source:'Free time'},
 {id:'6-l2',type:'choice',prompt:'What does Anna like doing at the weekend?',options:['Walking in the park and taking photos.','Going to the gym.','Watching a long movie.'],answer:'Walking in the park and taking photos.',rule:'listen',source:'Free time'},
 {id:'6-l3',type:'choice',prompt:'Who does Anna sometimes meet on Fridays?',options:['A friend.','Her teacher.','Her brother.'],answer:'A friend.',rule:'listen',source:'Free time — Anna'},
 {id:'6-l4',type:'choice',prompt:'What does Anna do if the weather is bad?',options:['She stays at home and cooks pasta or soup.','She goes to the gym.','She takes photos in the park.'],answer:'She stays at home and cooks pasta or soup.',rule:'listen',source:'Free time — Anna'},
 {id:'6-l5',type:'choice',prompt:'How does free time make Anna feel?',options:['Happy and calm.','Angry and tired.','Worried and busy.'],answer:'Happy and calm.',rule:'listen',source:'Free time — Anna'}
];
lessons.push(
 {id:'jobs',title:'l7',goal:'g7',person:'Emma',role:'Emma · barista',speakingPrompt:'Tell the AI Assistant what your job is or what job you would like. Say where you work and name two things you do there. Ask: “What do you do?”',audioTitle:'What’s your job? — Emma',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695941618eada26dfe2d2493_Listening%20A1.%20%20What%E2%80%99s%20your%20job%20(Emma).mp3',transcript:["Hello. My name is Emma.","I work in a café in the city center. I am a barista.","I start work at eight o’clock in the morning.","First, I turn on the coffee machine and clean the tables.","Then I make coffee and tea for customers.","I also prepare simple food like sandwiches and cakes.","During the day, I talk to many people and I try to be friendly.","Sometimes the café is very busy, especially at lunchtime.","It can be tiring, but I like my job because the team is nice.","After work, I feel proud because I help people start their day with a good drink."],vocabulary:[['barista',''],['coffee machine',''],['customer',''],['sandwich',''],['lunchtime',''],['proud','']],examples:['I am a barista.','She works in a café.','They are customers.'],rules:['aAn','pluralNouns'],items:[
  {id:'7-1',type:'choice',prompt:'Complete: Emma is ___ barista.',options:['a','an','— (no article)'],answer:'a',rule:'aAn',source:'A / An and Plurals; Emma audio'},
  {id:'7-2',type:'input',prompt:'Use a or an before the job: He is ___ assistant.',answers:['an'],modelAnswer:'He is an assistant.',rule:'aAn',source:'A / An and Plurals'},
  {id:'7-3',type:'choice',prompt:'Choose the correct sentence about Emma’s job.',options:['She works in a café.','She works in an café.','She works in café.'],answer:'She works in a café.',rule:'aAn',source:'A / An and Plurals; Emma audio'},
  {id:'7-4',type:'input',prompt:'Write the plural of sandwich: Emma prepares two ___.',answers:['sandwiches'],modelAnswer:'Emma prepares two sandwiches.',rule:'pluralNouns',source:'A / An and Plurals; Emma audio'},
  {id:'7-5',type:'order',prompt:'Build the sentence about Emma’s job.',tokens:['barista.','a','is','Emma'],answer:'Emma is a barista.',rule:'aAn',source:'Emma audio'},
  {id:'7-6',type:'choice',prompt:'Choose the correct plural sentence.',options:['They are customers.','They are a customers.','They are an customers.'],answer:'They are customers.',rule:'pluralNouns',source:'A / An and Plurals'},
  {id:'7-7',type:'input',prompt:'Use a or an before the singular noun: This is ___ coffee machine.',answers:['a'],modelAnswer:'This is a coffee machine.',rule:'aAn',source:'A / An and Plurals; Emma audio'},
  {id:'7-8',type:'choice',prompt:'Choose the correct phrase for one item.',options:['an orange','a orange','orange a'],answer:'an orange',rule:'aAn',source:'A / An and Plurals'},
  {id:'7-9',type:'input',prompt:'Write the plural of table: Emma cleans three ___.',answers:['tables'],modelAnswer:'Emma cleans three tables.',rule:'pluralNouns',source:'A / An and Plurals; Emma audio'},
  {id:'7-10',type:'choice',prompt:'Choose the correct sentence about more than one cake.',options:['She prepares cakes.','She prepares a cakes.','She prepares an cakes.'],answer:'She prepares cakes.',rule:'pluralNouns',source:'A / An and Plurals; Emma audio'}],listeningItems:[
  {id:'7-l1',type:'choice',prompt:'What is Emma’s job?',options:['A barista.','A nurse.','A bus driver.'],answer:'A barista.',rule:'listen',source:'What’s your job? — Emma'},
  {id:'7-l2',type:'choice',prompt:'What time does Emma start work?',options:['At eight o’clock.','At six o’clock.','At ten o’clock.'],answer:'At eight o’clock.',rule:'listen',source:'What’s your job? — Emma'},
  {id:'7-l3',type:'choice',prompt:'What does Emma do first?',options:['She turns on the coffee machine and cleans the tables.','She prepares cakes.','She goes home.'],answer:'She turns on the coffee machine and cleans the tables.',rule:'listen',source:'What’s your job? — Emma'},
  {id:'7-l4',type:'choice',prompt:'Which simple foods does Emma prepare?',options:['Sandwiches and cakes.','Pasta and soup.','Rice and eggs.'],answer:'Sandwiches and cakes.',rule:'listen',source:'What’s your job? — Emma'},
  {id:'7-l5',type:'choice',prompt:'Why does Emma like her job?',options:['Because the team is nice.','Because she works alone.','Because she finishes at lunchtime.'],answer:'Because the team is nice.',rule:'listen',source:'What’s your job? — Emma'}]},
 {id:'family',title:'l8',goal:'g8',person:'Anna',role:'Anna · family',speakingPrompt:'Tell the AI Assistant about two people in your family or two people you know. Say who they are and one thing each person does. Ask: “Who is in your family?”',audioTitle:'My family — Anna',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695d3023c02646e7af9e9c19_Listening%20A1%20Elementary.%20%20My%20family%20(Anna).mp3',transcript:["Hi, I’m Anna. I want to tell you about my family.","We are four people: my mum, my dad, my younger brother, and me.","My mum is kind and friendly. She works in a small shop near our house.","My dad is a bus driver. He starts work early, so he goes to bed early too.","My brother is twelve years old. He is in school and he likes football and computer games.","We live in a small apartment.","On weekdays, we are busy, but in the evening we eat dinner together.","On weekends, we visit my grandparents or we go for a walk in the park.","I love my family because we help each other and we laugh a lot."],vocabulary:[['younger brother',''],['bus driver',''],['grandparents',''],['together',''],['apartment',''],['laugh','']],examples:['My mum is kind.','His work starts early.','We visit our grandparents.'],rules:['possessiveAdjectives'],items:[
  {id:'8-1',type:'choice',prompt:'Anna is speaking. Complete: ___ mum works in a shop.',options:['My','I','Me'],answer:'My',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns; Anna audio'},
  {id:'8-2',type:'input',prompt:'Use the possessive adjective for he: Anna’s brother likes football. ___ favourite sport is football.',answers:['His'],modelAnswer:'His favourite sport is football.',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns'},
  {id:'8-3',type:'choice',prompt:'Anna’s mum works in a shop. Complete: ___ shop is near their house.',options:['Her','His','She'],answer:'Her',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns; Anna audio'},
  {id:'8-4',type:'order',prompt:'Build a sentence from Anna’s point of view.',tokens:['family','My','dinner','eats','together.'],answer:'My family eats dinner together.',rule:'possessiveAdjectives',source:'Anna audio adapted'},
  {id:'8-5',type:'input',prompt:'Use the possessive adjective for I: I love ___ family.',answers:['my'],modelAnswer:'I love my family.',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns; Anna audio'},
  {id:'8-6',type:'choice',prompt:'Anna speaks about herself and her family. Complete: ___ apartment is small.',options:['Our','We','Us'],answer:'Our',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns; Anna audio'},
  {id:'8-7',type:'choice',prompt:'Anna’s dad is a bus driver. Complete: ___ work starts early.',options:['His','Her','He'],answer:'His',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns; Anna audio'},
  {id:'8-8',type:'input',prompt:'Use the possessive adjective for we: We visit ___ grandparents on weekends.',answers:['our'],modelAnswer:'We visit our grandparents on weekends.',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns; Anna audio'},
  {id:'8-9',type:'choice',prompt:'Choose the correct pair for a female family member.',options:['She → her','She → his','She → my'],answer:'She → her',rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns'},
  {id:'8-10',type:'match',prompt:'Match each subject with its possessive adjective.',pairs:[['I','my'],['he','his'],['she','her']],rule:'possessiveAdjectives',source:'Possessive Adjectives and Pronouns'}],listeningItems:[
  {id:'8-l1',type:'choice',prompt:'How many people does Anna list when she describes her family?',options:['Four.','Three.','Five.'],answer:'Four.',rule:'listen',source:'My family — Anna'},
  {id:'8-l2',type:'choice',prompt:'Where does Anna’s mum work?',options:['In a small shop.','In a café.','In a school.'],answer:'In a small shop.',rule:'listen',source:'My family — Anna'},
  {id:'8-l3',type:'choice',prompt:'What is Anna’s dad’s job?',options:['A bus driver.','A shop assistant.','A teacher.'],answer:'A bus driver.',rule:'listen',source:'My family — Anna'},
  {id:'8-l4',type:'choice',prompt:'What does Anna’s brother like?',options:['Football and computer games.','Music and dancing.','Reading and cooking.'],answer:'Football and computer games.',rule:'listen',source:'My family — Anna'},
  {id:'8-l5',type:'choice',prompt:'What does Anna’s family do on weekends?',options:['Visit her grandparents or walk in the park.','Eat dinner at school.','Go to work early.'],answer:'Visit her grandparents or walk in the park.',rule:'listen',source:'My family — Anna'}]},
 {id:'room',title:'l9',goal:'g9',person:'Sofia',role:'Sofia · bedroom',speakingPrompt:'Describe your room to the AI Assistant. Say what furniture there is and where two things are. Ask: “Is there a desk in your room?”',audioTitle:'Describing a bedroom — Sofia',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695806442e9e533cdb912721_Listening%20A1.%20Lesson%207.people%20describing%20rooms%20in%20their%20houses%20(part1).mp3',transcript:["Hello. My name is Sofia.","I want to tell you about my bedroom.","My bedroom is small, but I like it.","The walls are light blue, and the room is bright in the morning.","There is a bed next to the window.","I have a warm blanket and two pillows.","Near the bed, there is a small table and a lamp.","I also have a wardrobe for my clothes.","In the corner, there is a desk and a chair.","I study English at my desk in the evening.","On the desk, I keep my notebook, a pen, and my phone charger.","I also have a small shelf with books.","My room is clean and quiet.","I feel relaxed there.","Thank you for listening."],vocabulary:[['bedroom',''],['blanket',''],['pillow',''],['wardrobe',''],['shelf',''],['phone charger','']],examples:['There is a bed next to the window.','There are two pillows on the bed.','The notebook is on the desk.'],rules:['thereIsAre','placeWords'],items:[
  {id:'9-1',type:'choice',prompt:'Choose the correct sentence about one bed.',options:['There is a bed next to the window.','There are a bed next to the window.','There is bed next to the window.'],answer:'There is a bed next to the window.',rule:'thereIsAre',source:'There is / There are; Sofia audio'},
  {id:'9-2',type:'input',prompt:'Use there are for two things: There ___ two pillows on the bed.',answers:['are'],modelAnswer:'There are two pillows on the bed.',rule:'thereIsAre',source:'There is / There are; Sofia audio'},
  {id:'9-3',type:'order',prompt:'Build a sentence about one lamp.',tokens:['bed.','the','near','lamp','a','is','There'],answer:'There is a lamp near the bed.',rule:'thereIsAre',source:'There is / There are; Sofia audio'},
  {id:'9-4',type:'choice',prompt:'Sofia’s desk is inside a corner of her bedroom. Choose the natural phrase.',options:['in the corner','on the corner','under the corner'],answer:'in the corner',rule:'placeWords',source:'Prepositions of Place; Sofia audio'},
  {id:'9-5',type:'input',prompt:'Use there is for one thing: There ___ a shelf with books.',answers:['is'],modelAnswer:'There is a shelf with books.',rule:'thereIsAre',source:'There is / There are; Sofia audio'},
  {id:'9-6',type:'choice',prompt:'Sofia keeps her notebook on a surface. Complete: It is ___ the desk.',options:['on','in','under'],answer:'on',rule:'placeWords',source:'Prepositions of Place; Sofia audio'},
  {id:'9-7',type:'choice',prompt:'Choose the correct question about two pillows.',options:['Are there two pillows on the bed?','Is there two pillows on the bed?','There are two pillows on the bed?'],answer:'Are there two pillows on the bed?',rule:'thereIsAre',source:'There is / There are'},
  {id:'9-8',type:'input',prompt:'Use next to to mean beside: The bed is ___ the window.',answers:['next to'],modelAnswer:'The bed is next to the window.',rule:'placeWords',source:'Prepositions of Place; Sofia audio'},
  {id:'9-9',type:'choice',prompt:'Choose the correct sentence about more than one book.',options:['There are books on the shelf.','There is books on the shelf.','There are a books on the shelf.'],answer:'There are books on the shelf.',rule:'thereIsAre',source:'There is / There are; Sofia audio adapted'},
  {id:'9-10',type:'order',prompt:'Build a sentence about the desk.',tokens:['corner.','the','in','desk','a','is','There'],answer:'There is a desk in the corner.',rule:'placeWords',source:'Sofia audio'}],listeningItems:[
  {id:'9-l1',type:'choice',prompt:'What colour are the walls of Sofia’s bedroom?',options:['Light blue.','White.','Green.'],answer:'Light blue.',rule:'listen',source:'Describing a bedroom — Sofia'},
  {id:'9-l2',type:'choice',prompt:'Where is Sofia’s bed?',options:['Next to the window.','Behind the door.','In the kitchen.'],answer:'Next to the window.',rule:'listen',source:'Describing a bedroom — Sofia'},
  {id:'9-l3',type:'choice',prompt:'Which two things does Sofia mention near her bed?',options:['A small table and a lamp.','A desk and a chair.','A wardrobe and a shelf.'],answer:'A small table and a lamp.',rule:'listen',source:'Describing a bedroom — Sofia'},
  {id:'9-l4',type:'choice',prompt:'Where does Sofia study English in the evening?',options:['At her desk.','On her bed.','In the kitchen.'],answer:'At her desk.',rule:'listen',source:'Describing a bedroom — Sofia'},
  {id:'9-l5',type:'choice',prompt:'Which three things does Sofia keep on her desk?',options:['A notebook, a pen and a phone charger.','A lamp, a blanket and a shelf.','Two pillows, a wardrobe and a chair.'],answer:'A notebook, a pen and a phone charger.',rule:'listen',source:'Describing a bedroom — Sofia'}]}
);
lessons.push(
 {id:'transport',title:'l10',goal:'g10',person:'Anna',role:'Anna · city transport',speakingPrompt:'Tell the AI Assistant how you travel around your city. Say where you wait for the bus and when you use a taxi. Ask: “How do you get to work?”',audioTitle:'Transport in the city — Anna',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695a8eb69b05aa42ee04b546_Listening%20A1%20Elementary.%20Transport%20in%20the%20city%20(Anna).mp3',transcript:[
  'Hello. My name is Anna.','In my city, I use public transport every day.','In the morning, I usually take the bus to work.','The bus stop is near my home, so it is easy.','The bus is sometimes crowded, especially at eight o’clock.','I don’t like that, but it is cheap and quick.','When the weather is nice, I sometimes walk instead.','It takes about twenty minutes.','In the evening, I often take the metro because it is faster than the bus.','I always keep my ticket in my bag.','Sometimes there is traffic on the roads, so taxis can be slow.','I use a taxi only when I am late or when it is raining.','For me, the best transport is the metro.'
 ],vocabulary:[['public transport',''],['bus stop',''],['crowded',''],['metro',''],['ticket',''],['traffic','']],examples:['I am at the bus stop.','I am on the bus.','I am in a taxi.'],rules:['transportPoint','transportVehicle'],items:[
  {id:'10-1',type:'choice',prompt:'Choose the preposition for a meeting point: Meet me ___ the bus stop.',options:['at','in','on'],answer:'at',rule:'transportPoint',source:'Grammar 10: Prepositions of Place'},
  {id:'10-2',type:'choice',prompt:'Anna is travelling as a passenger. She is ___ the bus.',options:['on','at','under'],answer:'on',rule:'transportVehicle',source:'Grammar 10: Prepositions of Place'},
  {id:'10-3',type:'input',prompt:'Use in for a taxi: Anna is ___ a taxi.',answers:['in'],modelAnswer:'Anna is in a taxi.',rule:'transportVehicle',source:'Grammar 10: Prepositions of Place'},
  {id:'10-4',type:'choice',prompt:'Choose the preposition for an area: Anna lives ___ the city.',options:['in','on','at'],answer:'in',rule:'transportPoint',source:'Grammar 10: Prepositions of Place'},
  {id:'10-5',type:'order',prompt:'Build the sentence about travelling by bus.',tokens:['bus.','the','on','is','Anna'],answer:'Anna is on the bus.',rule:'transportVehicle',source:'Grammar 10: Prepositions of Place'},
  {id:'10-6',type:'input',prompt:'Use at for a specific point: Anna waits ___ the bus stop.',answers:['at'],modelAnswer:'Anna waits at the bus stop.',rule:'transportPoint',source:'Grammar 10: Prepositions of Place'},
  {id:'10-7',type:'choice',prompt:'Which phrase means travelling inside a taxi?',options:['in a taxi','on a taxi','at a taxi'],answer:'in a taxi',rule:'transportVehicle',source:'Grammar 10: Prepositions of Place'},
  {id:'10-8',type:'input',prompt:'Use on for public transport: Anna is ___ the metro.',answers:['on'],modelAnswer:'Anna is on the metro.',rule:'transportVehicle',source:'Grammar 10: Prepositions of Place'},
  {id:'10-9',type:'choice',prompt:'Choose the preposition for a point: The ticket machine is ___ the station entrance.',options:['at','in','on'],answer:'at',rule:'transportPoint',source:'Grammar 10: Prepositions of Place'},
  {id:'10-10',type:'order',prompt:'Build the sentence about a taxi.',tokens:['taxi.','a','in','am','I'],answer:'I am in a taxi.',rule:'transportVehicle',source:'Grammar 10: Prepositions of Place'}
 ],listeningItems:[
  {id:'10-l1',type:'choice',prompt:'How does Anna usually travel to work in the morning?',options:['By bus.','By taxi.','By bike.'],answer:'By bus.',rule:'listen',source:'Transport in the city — Anna'},
  {id:'10-l2',type:'choice',prompt:'Where is the bus stop?',options:['Near Anna’s home.','Inside her office.','At the park.'],answer:'Near Anna’s home.',rule:'listen',source:'Transport in the city — Anna'},
  {id:'10-l3',type:'choice',prompt:'When is the bus especially crowded?',options:['At eight o’clock.','At lunchtime.','At midnight.'],answer:'At eight o’clock.',rule:'listen',source:'Transport in the city — Anna'},
  {id:'10-l4',type:'choice',prompt:'Why does Anna often take the metro in the evening?',options:['It is faster than the bus.','It is near her school.','She cannot walk.'],answer:'It is faster than the bus.',rule:'listen',source:'Transport in the city — Anna'},
  {id:'10-l5',type:'choice',prompt:'When does Anna use a taxi?',options:['When she is late or it is raining.','Every morning.','Only when the metro is crowded.'],answer:'When she is late or it is raining.',rule:'listen',source:'Transport in the city — Anna'}]},
 {id:'schedule',title:'l11',goal:'g11',person:'Anna',role:'Anna · daily routine',speakingPrompt:'Tell the AI Assistant about your weekday schedule. Say what time you wake up, when you start work and what you do in the evening. Ask: “What time do you start work?”',audioTitle:'Daily routines — Anna',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695e779f2a1010fe56444a17_Listening%20A1%20Elementary.%20Daily%20routines%20(Anna).mp3',transcript:[
  'Hi, I’m Anna. On weekdays, I wake up at 7:00.','I wash my face, brush my teeth, and get dressed.','Then I have breakfast. I usually eat toast and drink coffee.','I leave home at 8:00 and go to work by bus. I start work at 9:00.','At lunchtime, I eat a sandwich or salad and talk to my coworkers.','I finish work at 5:00 and go home.','In the evening, I cook dinner and clean the kitchen.','After that, I relax. I watch a series, read a little, or listen to music.','I go to bed at about 11:00.'
 ],vocabulary:[['weekday',''],['get dressed',''],['lunchtime',''],['coworker',''],['series',''],['go to bed','']],examples:['I wake up at 7:00.','I cook dinner in the evening.','I work on weekdays.'],rules:['timeAtInOn','timeNoPreposition'],items:[
  {id:'11-1',type:'choice',prompt:'Choose the preposition for an exact time: Anna wakes up ___ 7:00.',options:['at','in','on'],answer:'at',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time; Anna audio'},
  {id:'11-2',type:'input',prompt:'Use in before a part of the day: Anna has breakfast ___ the morning.',answers:['in'],modelAnswer:'Anna has breakfast in the morning.',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time'},
  {id:'11-3',type:'choice',prompt:'Anna works on Monday to Friday. She works ___ weekdays.',options:['on','at','in'],answer:'on',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time; Anna audio'},
  {id:'11-4',type:'input',prompt:'Use at with lunchtime: Anna talks to coworkers ___ lunchtime.',answers:['at'],modelAnswer:'Anna talks to coworkers at lunchtime.',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time; Anna audio'},
  {id:'11-5',type:'order',prompt:'Build the sentence with an exact time.',tokens:['eight.','at','home','leave','I'],answer:'I leave home at eight.',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time; Anna audio'},
  {id:'11-6',type:'choice',prompt:'Choose the phrase for the evening in general: Anna relaxes ___ the evening.',options:['in','on','at'],answer:'in',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time; Anna audio'},
  {id:'11-7',type:'input',prompt:'Use every without a preposition: Anna takes the bus ___ weekday.',answers:['every'],modelAnswer:'Anna takes the bus every weekday.',rule:'timeNoPreposition',source:'Grammar 12: Prepositions of Time'},
  {id:'11-8',type:'choice',prompt:'Choose the phrase without an extra preposition.',options:['next Monday','on next Monday','in next Monday'],answer:'next Monday',rule:'timeNoPreposition',source:'Grammar 12: Prepositions of Time'},
  {id:'11-9',type:'input',prompt:'Use on before a specific day: I rest ___ Saturday.',answers:['on'],modelAnswer:'I rest on Saturday.',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time'},
  {id:'11-10',type:'choice',prompt:'Choose the correct phrase for a specific time.',options:['at 9:00','in 9:00','on 9:00'],answer:'at 9:00',rule:'timeAtInOn',source:'Grammar 12: Prepositions of Time'}
 ],listeningItems:[
  {id:'11-l1',type:'choice',prompt:'What time does Anna wake up on weekdays?',options:['At 7:00.','At 8:00.','At 9:00.'],answer:'At 7:00.',rule:'listen',source:'Daily routines — Anna'},
  {id:'11-l2',type:'choice',prompt:'How does Anna travel to work?',options:['By bus.','By bike.','By metro.'],answer:'By bus.',rule:'listen',source:'Daily routines — Anna'},
  {id:'11-l3',type:'choice',prompt:'What time does Anna start work?',options:['At 9:00.','At 8:00.','At 5:00.'],answer:'At 9:00.',rule:'listen',source:'Daily routines — Anna'},
  {id:'11-l4',type:'choice',prompt:'What does Anna do at lunchtime?',options:['She eats a sandwich or salad and talks to coworkers.','She goes home and cooks dinner.','She listens to music in her room.'],answer:'She eats a sandwich or salad and talks to coworkers.',rule:'listen',source:'Daily routines — Anna'},
  {id:'11-l5',type:'choice',prompt:'What time does Anna go to bed?',options:['At about 11:00.','At 9:00.','At 5:00.'],answer:'At about 11:00.',rule:'listen',source:'Daily routines — Anna'}]},
 {id:'languages',title:'l12',goal:'g12',person:'Emma',role:'Emma · languages',speakingPrompt:'Tell the AI Assistant where you are from and which languages you speak or study. Ask: “Where are you from?” and “What languages do you speak?”',audioTitle:'Countries, nationalities, and languages — Emma',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/69593224763c6f46416b9942_Listening%20A1.%20Lesson%207.Countries%2C%20nationalities%2C%20and%20languages%20(Emma).mp3',transcript:[
  'Hello. My name is Emma.','I am from Canada, and I am Canadian.','My city is Toronto.','My first language is English, but I also study French.','In Canada, many people speak English and French, so French is very useful.','I learn French at a language school two evenings a week.','It is not easy, but I like it.','My teacher is from France, and she speaks French very clearly.','I want to travel to Paris one day, so I practice every day.','I listen to short videos and repeat simple phrases.','I also have friends from different countries.','My friend Sofia is from Mexico.','She is Mexican, and she speaks Spanish.','We sometimes teach each other new words.','I think languages are fun and helpful.'
 ],vocabulary:[['nationality',''],['first language',''],['useful',''],['language school',''],['phrase',''],['practice','']],examples:['Where are you from?','What language do you speak?','Where does Emma learn French?'],rules:['questionsWithBe','questionsWithDo'],items:[
  {id:'12-1',type:'choice',prompt:'Ask about a place of origin: ___ is Emma from?',options:['Where','When','How old'],answer:'Where',rule:'questionsWithBe',source:'Grammar 16: Questions with Be and Do; Emma audio'},
  {id:'12-2',type:'input',prompt:'Use be to ask about Emma: Where ___ Emma from?',answers:['is'],modelAnswer:'Where is Emma from?',rule:'questionsWithBe',source:'Grammar 16: Questions with Be and Do'},
  {id:'12-3',type:'choice',prompt:'Ask about a language Emma speaks: What language ___ she speak?',options:['does','is','do'],answer:'does',rule:'questionsWithDo',source:'Grammar 16: Questions with Be and Do'},
  {id:'12-4',type:'order',prompt:'Build a question about your teacher’s country.',tokens:['from?','teacher','your','is','Where'],answer:'Where is your teacher from?',rule:'questionsWithBe',source:'Grammar 16: Questions with Be and Do'},
  {id:'12-5',type:'choice',prompt:'Ask another person about a language: ___ you speak French?',options:['Do','Does','Are'],answer:'Do',rule:'questionsWithDo',source:'Grammar 16: Questions with Be and Do'},
  {id:'12-6',type:'input',prompt:'Use do before you: What language ___ you speak?',answers:['do'],modelAnswer:'What language do you speak?',rule:'questionsWithDo',source:'Grammar 16: Questions with Be and Do'},
  {id:'12-7',type:'choice',prompt:'Ask about Emma’s regular classes: When ___ she study French?',options:['does','is','do'],answer:'does',rule:'questionsWithDo',source:'Grammar 16: Questions with Be and Do; Emma audio'},
  {id:'12-8',type:'input',prompt:'Use be to ask about nationality: ___ Emma Canadian?',answers:['Is'],modelAnswer:'Is Emma Canadian?',rule:'questionsWithBe',source:'Grammar 16: Questions with Be and Do; Emma audio'},
  {id:'12-9',type:'choice',prompt:'Choose the correctly formed question about Emma’s school.',options:['Where does she learn French?','Where she learns French?','Where is she learn French?'],answer:'Where does she learn French?',rule:'questionsWithDo',source:'Grammar 16: Questions with Be and Do; Emma audio'},
  {id:'12-10',type:'order',prompt:'Build a question about the listener’s language.',tokens:['French?','speak','you','Do'],answer:'Do you speak French?',rule:'questionsWithDo',source:'Grammar 16: Questions with Be and Do'}
 ],listeningItems:[
  {id:'12-l1',type:'choice',prompt:'Which country is Emma from?',options:['Canada.','France.','Mexico.'],answer:'Canada.',rule:'listen',source:'Countries, nationalities, and languages — Emma'},
  {id:'12-l2',type:'choice',prompt:'Which language does Emma study?',options:['French.','Spanish.','Japanese.'],answer:'French.',rule:'listen',source:'Countries, nationalities, and languages — Emma'},
  {id:'12-l3',type:'choice',prompt:'How often does Emma learn French at a language school?',options:['Two evenings a week.','Every morning.','Once a month.'],answer:'Two evenings a week.',rule:'listen',source:'Countries, nationalities, and languages — Emma'},
  {id:'12-l4',type:'choice',prompt:'Where is Emma’s teacher from?',options:['France.','Canada.','Mexico.'],answer:'France.',rule:'listen',source:'Countries, nationalities, and languages — Emma'},
  {id:'12-l5',type:'choice',prompt:'What language does Emma’s friend Sofia speak?',options:['Spanish.','French.','English.'],answer:'Spanish.',rule:'listen',source:'Countries, nationalities, and languages — Emma'}]}
);
lessons.push(
 {id:'describing-people',title:'l13',goal:'g13',person:'Anna',role:'Anna · Alex',speakingPrompt:'Describe someone you know. Say what they are like and one thing they do for you. Ask: “What is your friend like?”',audioTitle:'Describing people — Anna',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695a9866ac968c6b738ac842_Listening%20A1%20Elementary.%20Describing%20people%20(Anna).mp3',transcript:[
  'Hello. My name is Anna.','I want to tell you about my husband.','His name is Alex.','He is thirty-one years old, and he is very kind.','He works in an office, and he usually comes home at six o’clock.','When he comes home, he says hello and asks about my day.','Alex helps me a lot.','He often cooks dinner, especially on Fridays.','He makes pasta or rice with chicken.','After dinner, he usually washes the dishes.','On weekends, we go for a walk in the park or visit my parents.','Alex is calm and friendly, and he makes me feel safe and happy.'
 ],vocabulary:[['husband',''],['kind',''],['office',''],['calm',''],['friendly',''],['safe','']],examples:['Alex is a kind person.','Alex is calm and friendly.','Anna feels happy.'],rules:['adjectiveBefore','adjectiveAfter','adjectiveNoPlural'],items:[
  {id:'13-1',type:'choice',prompt:'Choose the natural word order.',options:['Alex is a kind person.','Alex is a person kind.','Alex is a kindness person.'],answer:'Alex is a kind person.',rule:'adjectiveBefore',source:'Grammar 6: Adjectives'},
  {id:'13-2',type:'input',prompt:'Complete with the adjective after be: Alex is very ___. (kind)',answers:['kind'],modelAnswer:'Alex is very kind.',rule:'adjectiveAfter',source:'Grammar 6: Adjectives; Describing people'},
  {id:'13-3',type:'choice',prompt:'Choose the correct sentence with two people.',options:['They are friendly people.','They are friendlies people.','They are people friendly.'],answer:'They are friendly people.',rule:'adjectiveNoPlural',source:'Grammar 6: Adjectives'},
  {id:'13-4',type:'order',prompt:'Build a sentence describing Alex.',tokens:['kind.','very','is','Alex'],answer:'Alex is very kind.',rule:'adjectiveAfter',source:'Grammar 6: Adjectives; Describing people'},
  {id:'13-5',type:'choice',prompt:'Which question asks about someone’s character?',options:['Is Alex friendly?','Is friendly Alex?','Does Alex friendly?'],answer:'Is Alex friendly?',rule:'adjectiveAfter',source:'Grammar 6: Adjectives'},
  {id:'13-6',type:'input',prompt:'Use an adjective after feel: Anna feels ___. (happy)',answers:['happy'],modelAnswer:'Anna feels happy.',rule:'adjectiveAfter',source:'Grammar 6: Adjectives; Describing people'},
  {id:'13-7',type:'choice',prompt:'Choose the adjective before a noun.',options:['a calm person','a person calm','a calmly person'],answer:'a calm person',rule:'adjectiveBefore',source:'Grammar 6: Adjectives'},
  {id:'13-8',type:'input',prompt:'Adjectives do not take plural -s: They are ___ people. (kind)',answers:['kind'],modelAnswer:'They are kind people.',rule:'adjectiveNoPlural',source:'Grammar 6: Adjectives'},
  {id:'13-9',type:'choice',prompt:'Choose the sentence with feel + adjective.',options:['I feel safe.','I feel safely.','I feel a safe.'],answer:'I feel safe.',rule:'adjectiveAfter',source:'Grammar 6: Adjectives'},
  {id:'13-10',type:'order',prompt:'Build a sentence about Anna’s feelings.',tokens:['happy.','feels','Anna'],answer:'Anna feels happy.',rule:'adjectiveAfter',source:'Grammar 6: Adjectives'}
 ],listeningItems:[
  {id:'13-l1',type:'choice',prompt:'Who is Alex?',options:['Anna’s husband.','Anna’s brother.','Anna’s father.'],answer:'Anna’s husband.',rule:'listen',source:'Describing people — Anna'},
  {id:'13-l2',type:'choice',prompt:'How old is Alex?',options:['Thirty-one.','Twenty-one.','Forty-one.'],answer:'Thirty-one.',rule:'listen',source:'Describing people — Anna'},
  {id:'13-l3',type:'choice',prompt:'Where does Alex work?',options:['In an office.','In a café.','In a hospital.'],answer:'In an office.',rule:'listen',source:'Describing people — Anna'},
  {id:'13-l4',type:'choice',prompt:'What does Alex often do, especially on Fridays?',options:['Cook dinner.','Wash the car.','Play football.'],answer:'Cook dinner.',rule:'listen',source:'Describing people — Anna'},
  {id:'13-l5',type:'choice',prompt:'Which words does Anna use to describe Alex?',options:['Calm and friendly.','Loud and angry.','Tired and busy.'],answer:'Calm and friendly.',rule:'listen',source:'Describing people — Anna'}]},
 {id:'apartment-articles',title:'l14',goal:'g14',person:'Anna',role:'Anna · apartment',speakingPrompt:'Describe your home. Mention a room for the first time, then say something about the room. Ask: “What is your favourite room?”',audioTitle:'My apartment — Anna',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695e62ec1bf79e8cd864b4ff_Listening%20A1%20Elementary.%20My%20apartment%20(Anna).mp3',transcript:[
  'Hi, I’m Anna. I live in a small apartment in the city.','It is on the third floor, and it is bright.','I have a living room, a bedroom, a kitchen, and a bathroom.','My living room is my favorite place. I have a sofa, a small table, and a TV.','In the bedroom, I have a bed, a wardrobe, and a mirror.','My kitchen is small, but it is comfortable. I cook simple food there, like pasta, soup, and eggs.','I also have a balcony. In the morning, I drink coffee on the balcony and look at the street.','My apartment is not big, but it feels warm and cozy.'
 ],vocabulary:[['apartment',''],['third floor',''],['wardrobe',''],['mirror',''],['balcony',''],['cozy','']],examples:['I have a balcony. The balcony is bright.','Anna lives in an apartment.','Anna likes coffee.'],rules:['articleFirst','articleSpecific','articleZero'],items:[
  {id:'14-1',type:'choice',prompt:'First mention of one apartment: Anna lives in ___ apartment.',options:['an','a','the'],answer:'an',rule:'articleFirst',source:'Grammar 5: Articles; My apartment'},
  {id:'14-2',type:'input',prompt:'First mention of one balcony: Anna has ___ balcony.',answers:['a'],modelAnswer:'Anna has a balcony.',rule:'articleFirst',source:'Grammar 5: Articles; My apartment'},
  {id:'14-3',type:'choice',prompt:'The balcony is already mentioned: She drinks coffee on ___ balcony.',options:['the','a','an'],answer:'the',rule:'articleSpecific',source:'Grammar 5: Articles; My apartment'},
  {id:'14-4',type:'input',prompt:'One specific floor: Anna lives on ___ third floor.',answers:['the'],modelAnswer:'Anna lives on the third floor.',rule:'articleSpecific',source:'Grammar 5: Articles; My apartment'},
  {id:'14-5',type:'choice',prompt:'Choose the sentence about coffee in general.',options:['Anna likes coffee.','Anna likes a coffee.','Anna likes the coffee.'],answer:'Anna likes coffee.',rule:'articleZero',source:'Grammar 5: Articles'},
  {id:'14-6',type:'order',prompt:'Build a sentence introducing a room.',tokens:['kitchen.','a','has','Anna'],answer:'Anna has a kitchen.',rule:'articleFirst',source:'Grammar 5: Articles'},
  {id:'14-7',type:'choice',prompt:'First mention of one small table: She has ___ small table.',options:['a','an','the'],answer:'a',rule:'articleFirst',source:'Grammar 5: Articles; My apartment'},
  {id:'14-8',type:'input',prompt:'The table is already mentioned: ___ table is small.',answers:['The'],modelAnswer:'The table is small.',rule:'articleSpecific',source:'Grammar 5: Articles'},
  {id:'14-9',type:'choice',prompt:'Choose the sentence about rooms in general.',options:['Rooms can be bright.','A rooms can be bright.','The rooms can be bright.'],answer:'Rooms can be bright.',rule:'articleZero',source:'Grammar 5: Articles'},
  {id:'14-10',type:'order',prompt:'Build a sentence about a specific room.',tokens:['bedroom','bright.','is','The'],answer:'The bedroom is bright.',rule:'articleSpecific',source:'Grammar 5: Articles'}
 ],listeningItems:[
  {id:'14-l1',type:'choice',prompt:'Which floor is Anna’s apartment on?',options:['The third floor.','The first floor.','The fifth floor.'],answer:'The third floor.',rule:'listen',source:'My apartment — Anna'},
  {id:'14-l2',type:'choice',prompt:'Which room is Anna’s favourite place?',options:['The living room.','The bathroom.','The bedroom.'],answer:'The living room.',rule:'listen',source:'My apartment — Anna'},
  {id:'14-l3',type:'choice',prompt:'What does Anna have in her bedroom?',options:['A bed, a wardrobe and a mirror.','A sofa, a TV and a table.','A cooker, a fridge and a sink.'],answer:'A bed, a wardrobe and a mirror.',rule:'listen',source:'My apartment — Anna'},
  {id:'14-l4',type:'choice',prompt:'What food does Anna say she cooks in her kitchen?',options:['Pasta, soup and eggs.','Rice, chicken and fish.','Bread, salad and fruit.'],answer:'Pasta, soup and eggs.',rule:'listen',source:'My apartment — Anna'},
  {id:'14-l5',type:'choice',prompt:'Where does Anna drink coffee in the morning?',options:['On the balcony.','In the bathroom.','In the bedroom.'],answer:'On the balcony.',rule:'listen',source:'My apartment — Anna'}]},
 {id:'village-there-it',title:'l15',goal:'g15',person:'Isabella',role:'Isabella · village',speakingPrompt:'Describe your town or village. Say what places there are and what the place is like. Ask: “Is there a shop near you?”',audioTitle:'Living in a village — Isabella',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/695bee6f5bd8940575593275_Listening%20A1%20Elementary.%20Living%20in%20a%20village%20(Isabella).mp3',transcript:[
  'Hi, I’m Isabella. I live in a small village.','It is quiet and peaceful. There are not many cars, so the streets are calm.','In the morning, I hear birds, not traffic. I like that.','My house is small, but it has a garden. In spring and summer, I grow tomatoes and herbs. I also have flowers.','In the village, people know each other. My neighbors say hello and sometimes they help me.','We have a small shop, a post office, and a bus stop.','We do not have a big supermarket, so I go to the city once a week.','In the evenings, I walk near the fields and watch the sunset.','Village life is simple, and I feel relaxed.'
 ],vocabulary:[['village',''],['peaceful',''],['neighbor',''],['post office',''],['field',''],['sunset','']],examples:['There is a shop in the village.','It is quiet.','There are not many cars.'],rules:['thereExists','itRefers','itWeatherTime'],items:[
  {id:'15-1',type:'choice',prompt:'Introduce a shop for the first time: ___ a shop in the village.',options:['There is','It is','There are'],answer:'There is',rule:'thereExists',source:'Grammar 9: There vs It'},
  {id:'15-2',type:'input',prompt:'Refer back to the village: ___ is quiet and peaceful.',answers:['It'],modelAnswer:'It is quiet and peaceful.',rule:'itRefers',source:'Grammar 9: There vs It; Living in a village'},
  {id:'15-3',type:'choice',prompt:'Talk about several cars existing: ___ not many cars.',options:['There are','It is','There is'],answer:'There are',rule:'thereExists',source:'Grammar 9: There vs It; Living in a village'},
  {id:'15-4',type:'order',prompt:'Build a sentence introducing a place.',tokens:['office.','post','a','is','There'],answer:'There is a post office.',rule:'thereExists',source:'Grammar 9: There vs It'},
  {id:'15-5',type:'choice',prompt:'First mention: There is a garden. ___ has flowers.',options:['It','There','They'],answer:'It',rule:'itRefers',source:'Grammar 9: There vs It'},
  {id:'15-6',type:'input',prompt:'Describe the weather: ___ is sunny today.',answers:['It'],modelAnswer:'It is sunny today.',rule:'itWeatherTime',source:'Grammar 9: There vs It'},
  {id:'15-7',type:'choice',prompt:'Ask if a bus stop exists nearby.',options:['Is there a bus stop near here?','Is it a bus stop near here?','Are there a bus stop near here?'],answer:'Is there a bus stop near here?',rule:'thereExists',source:'Grammar 9: There vs It'},
  {id:'15-8',type:'input',prompt:'Talk about the time: ___ is seven o’clock.',answers:['It'],modelAnswer:'It is seven o’clock.',rule:'itWeatherTime',source:'Grammar 9: There vs It'},
  {id:'15-9',type:'choice',prompt:'First mention: There are two shops. ___ are small.',options:['They','It','There'],answer:'They',rule:'itRefers',source:'Grammar 9: There vs It'},
  {id:'15-10',type:'order',prompt:'Build a sentence describing the village.',tokens:['quiet.','is','It'],answer:'It is quiet.',rule:'itRefers',source:'Grammar 9: There vs It'}
 ],listeningItems:[
  {id:'15-l1',type:'choice',prompt:'Where does Isabella live?',options:['In a small village.','In a large city.','Near a busy station.'],answer:'In a small village.',rule:'listen',source:'Living in a village — Isabella'},
  {id:'15-l2',type:'choice',prompt:'What does Isabella hear in the morning instead of traffic?',options:['Birds.','Trains.','Music.'],answer:'Birds.',rule:'listen',source:'Living in a village — Isabella'},
  {id:'15-l3',type:'choice',prompt:'What does Isabella grow in her garden in spring and summer?',options:['Tomatoes and herbs.','Apples and pears.','Rice and potatoes.'],answer:'Tomatoes and herbs.',rule:'listen',source:'Living in a village — Isabella'},
  {id:'15-l4',type:'choice',prompt:'Which places are in Isabella’s village?',options:['A small shop, a post office and a bus stop.','A cinema, a bank and a museum.','A supermarket, an airport and a train station.'],answer:'A small shop, a post office and a bus stop.',rule:'listen',source:'Living in a village — Isabella'},
  {id:'15-l5',type:'choice',prompt:'How often does Isabella go to the city?',options:['Once a week.','Every day.','Once a year.'],answer:'Once a week.',rule:'listen',source:'Living in a village — Isabella'}]}
);
const speakingSentences=[
 ['My name is Anna.','I am a student.'],
 ['I work in a supermarket.','I go to work by bike.'],
 ['I work in a café.','I wake up at seven.'],
 ['She is sitting on the sofa.','He is cooking lunch.'],
 ['I am going to meet my friend.','We are going to drink coffee.'],
 ['I like walking in the park.','I enjoy reading easy books.'],
 ['I am a barista.','I make coffee for customers.'],
 ['My dad is a bus driver.','We eat dinner together.'],
 ['There is a bed next to the window.','There are two pillows on the bed.'],
 ['I take the bus to work.','I am on the metro.'],
 ['I wake up at seven.','I cook dinner in the evening.'],
 ['I am from Canada.','I study French at a language school.'],
 ['Alex is a kind person.','Anna feels happy with Alex.'],
 ['I have a balcony.','The balcony is bright.'],
 ['There is a shop in the village.','It is quiet and peaceful.']
];
lessons.forEach((lesson,index)=>{lesson.speakingSentences=speakingSentences[index];});
const data={version:7,lessons};if(typeof module==='object'&&module.exports)module.exports=data;else root.EvoCourseBank=data;
})(typeof globalThis==='object'?globalThis:this);
