(function(root){
'use strict';
const lessons=[
 {id:'introduce',title:'l1',goal:'g1',person:'Daniel',role:'Daniel · student',speakingPrompt:'Introduce yourself as a new student. Say your name, country and role. Ask your partner their name and country.',audioTitle:'Students in a new class',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953ca29a25e926ab54497e9_Listening%20A1.%20Lesson%202.%20Students%20in%20a%20new%20class.mp3',transcript:["Hello.","My name is Anna, and I want to tell you about my new language class.","I study Japanese at a language school in the city.","Our class is small. There are eight students.","Our teacher’s name is Mr Tanaka.","He is from Japan, and he is forty-five years old.","He is very kind and friendly.","He loves music, and sometimes he plays the guitar in class.","The students in my class are from different countries.","One student is Maria. She is from Mexico.","She is twenty years old, and she is a university student.","She likes dancing and music.","Another student is Paul. He is from Canada.","He is thirty years old, and he works as a waiter.","He likes football and video games.","We also have a student from France.","Her name is Silvie. She is a nurse, and she loves anime and Japan.","I really like my class.","The students are friendly, and the teacher is great.","I enjoy learning Japanese, and I am happy to be in this class."],vocabulary:[['class','класс'],['student','студент'],['teacher','учитель'],['friendly','дружелюбный'],['country','страна'],['nurse','медсестра']],examples:["Hi! I'm Anna.",'My name is Anna.',"I'm a student."],rules:['be','my','student'],items:[
  {id:'1-1',type:'choice',prompt:'You meet Anna for the first time. Choose a greeting.',options:['Hi!','Goodbye!'],answer:'Hi!',rule:'greeting',source:'new bridge'},
  {id:'1-2',type:'choice',prompt:'I ___ Anna.',options:['is','are','am'],answer:'am',rule:'be',source:'S1 adapted'},
  {id:'1-3',type:'choice',prompt:'___ name is Anna.',options:['I','My'],answer:'My',rule:'my',source:'S9.1 adapted'},
  {id:'1-4',type:'match',prompt:'Match the full forms with their short forms.',pairs:[['I am',"I'm"],['My name is',"My name's"]],rule:'short',source:'S1 adapted + bridge'},
  {id:'1-5',type:'order',prompt:'Introduce yourself as a student.',tokens:['student.','a',"I'm"],answer:"I'm a student.",rule:'student',source:'S1 adapted'},
  {id:'1-6',type:'input',prompt:'Correct the sentence: I student.',answers:['I am a student',"I'm a student"],rule:'student',source:'S1 adapted'},
  {id:'1-7',type:'input',prompt:'You are Daniel. Complete: I am ___ (or write the full sentence).',answers:['Daniel','I am Daniel',"I'm Daniel"],rule:'be',source:'S1 + bridge'},
  {id:'1-8',type:'choice',prompt:'Choose the correct sentence.',options:['She is from France.','She are from France.','She am from France.'],answer:'She is from France.',rule:'be',source:'to be practice'},
  {id:'1-10',type:'input',prompt:'Complete the sentence: I am ___ Armenia.',answers:['from'],modelAnswer:'I am from Armenia.',rule:'be',source:'guided gap-fill'}]},
 {id:'daily',title:'l2',goal:'g2',person:'Michael',role:'Michael · shop assistant',speakingPrompt:'Tell your partner about your job and weekday routine. Ask what they do and when they start their day.',audioTitle:'Tell me about your life',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/6953f72489bec422321a323b_speech_1767110387213.mp3',transcript:["Hello.","My name is Michael.","I am thirty years old.","I live in a small town near the sea.","I live in a flat with my wife.","We do not have children.","I work in a supermarket.","I am a shop assistant.","I help customers and work at the cash desk.","I like my job because my colleagues are friendly.","On weekdays, I wake up at six thirty.","I take a shower and get dressed.","Then I have breakfast at home.","I usually drink coffee and eat a sandwich.","I go to work by bike.","It takes about ten minutes.","I start work at eight o’clock.","After work, I go home and rest.","In the evening, I cook dinner with my wife.","We watch TV or talk about our day.","On weekends, I do not work.","I like walking near the sea.","Sometimes I meet my friends and play football.","I also like listening to music.","I am learning English now.","I study English at home.","I want to travel and meet new people in the future.","Thank you for listening."],vocabulary:[['weekday','будний день'],['supermarket','супермаркет'],['customer','клиент'],['cash desk','касса'],['colleague','коллега'],['future','будущее']],examples:['I work in a supermarket.','I usually drink coffee.','I go to work by bike.'],rules:['presentSimple','frequency','doQuestion'],items:[
  {id:'2-1',type:'choice',prompt:'Where does Michael work?',options:['In a café','In a supermarket','At a school'],answer:'In a supermarket',rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-2',type:'choice',prompt:'What time does Michael wake up on weekdays?',options:['At six thirty','At seven thirty','At eight o’clock'],answer:'At six thirty',rule:'frequency',source:'Listening A1 Tell me about your life'},
  {id:'2-3',type:'order',prompt:'Build the sentence about Michael’s transport.',tokens:['bike.','work','to','go','I','by'],answer:'I go to work by bike.',rule:'wordOrder',source:'Listening A1 Tell me about your life'},
  {id:'2-4',type:'input',prompt:'Complete: I usually drink ___ and eat a sandwich.',answers:['coffee'],rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-5',type:'choice',prompt:'Choose the correct negative sentence.',options:["We don't have children.","We doesn't have children.","We not have children."],answer:"We don't have children.",rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-6',type:'choice',prompt:'Choose the correct question about Michael’s routine.',options:['What time does he start work?','What time he starts work?','What time do he start work?'],answer:'What time does he start work?',rule:'doQuestion',source:'Listening A1 Tell me about your life'},
  {id:'2-7',type:'input',prompt:'Complete: On weekends, Michael ___ work.',answers:["doesn't",'does not'],rule:'presentSimple',source:'Listening A1 Tell me about your life'},
  {id:'2-8',type:'order',prompt:'Put the words in order to describe a regular action.',tokens:['English.','study','I','every day'],answer:'I study English every day.',rule:'frequency',source:'guided transfer from Listening A1 Tell me about your life'}]},
 {id:'meet',title:'l3',goal:'g3',person:'Anna',role:'Anna · café worker',speakingPrompt:'Describe a typical day and what you do in your free time. Ask your partner about their evenings or weekends.',audioTitle:'My Daily Life',audio:'https://cdn.prod.website-files.com/67aa2baa0c65412632c4b3d1/69538927b8f13a47a81c7924_Listening%20A1.%20Lesson%201.%20My%20daily%20life.mp3',transcript:["Hello.","My name is Anna.","I am twenty-six years old.","I live in a small city.","I live with my parents and my younger brother.","My family is very friendly.","I work in a café near my home.","I like my job because the people are nice.","Every day, I wake up at seven o’clock.","I wash my face and brush my teeth.","Then I have breakfast.","For breakfast, I usually drink coffee and eat toast.","Sometimes I eat eggs or fruit.","I leave home at eight o’clock.","I go to work by bus.","The bus ride takes about twenty minutes.","At work, I make coffee and serve customers.","I talk to people and smile a lot.","I finish work at four o’clock.","After work, I go home.","In the evening, I like to relax.","I watch TV or listen to music.","Sometimes I read a book.","I like reading simple stories.","I also like learning English.","On weekends, I do not work.","I meet my friends or stay at home.","We go for a walk or drink tea together.","I like weekends very much.","Thank you for listening."],vocabulary:[['routine','распорядок'],['café','кафе'],['customer','клиент'],['wake up','просыпаться'],['serve','обслуживать'],['relax','отдыхать']],examples:['I wake up at seven o’clock.','I go to work by bus.','I finish work at four.'],rules:['presentSimple','frequency','wordOrder'],items:[
  {id:'3-1',type:'choice',prompt:'Where does Anna work?',options:['In a café','In a supermarket','At a school'],answer:'In a café',rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-2',type:'input',prompt:'Complete: Anna is ___ years old.',answers:['twenty-six','26'],rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-3',type:'order',prompt:'Build the sentence about Anna’s transport.',tokens:['bus.','by','work','to','go','I'],answer:'I go to work by bus.',rule:'wordOrder',source:'Listening A1 My Daily Life'},
  {id:'3-4',type:'choice',prompt:'What time does Anna wake up?',options:['At six o’clock','At seven o’clock','At eight o’clock'],answer:'At seven o’clock',rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-5',type:'input',prompt:'Complete: For breakfast, Anna usually drinks ___.',answers:['coffee'],rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-6',type:'choice',prompt:'What time does Anna finish work?',options:['At two o’clock','At four o’clock','At eight o’clock'],answer:'At four o’clock',rule:'presentSimple',source:'Listening A1 My Daily Life'},
  {id:'3-7',type:'choice',prompt:'What does Anna do at weekends?',options:['She works in a café.','She meets friends or stays at home.','She goes to school.'],answer:'She meets friends or stays at home.',rule:'frequency',source:'Listening A1 My Daily Life'},
  {id:'3-8',type:'choice',prompt:'Choose the correct sentence about free time.',options:['She reads a book in the evening.','She read a book in the evening every day.','She is read a book in the evening.'],answer:'She reads a book in the evening.',rule:'presentSimple',source:'Present Simple practice'}]}
];
lessons[0].listeningItems=[
 {id:'1-l1',type:'choice',prompt:'Where is Mr Tanaka from?',options:['Japan','Canada','France'],answer:'Japan',rule:'listen',source:'Students in a new class'},
 {id:'1-l2',type:'choice',prompt:'How many students are in the class?',options:['Six','Eight','Ten'],answer:'Eight',rule:'listen',source:'Students in a new class'},
 {id:'1-l3',type:'choice',prompt:'Where is Maria from?',options:['Mexico','Japan','France'],answer:'Mexico',rule:'listen',source:'Students in a new class'},
 {id:'1-l4',type:'choice',prompt:'What does Paul do?',options:['He is a waiter.','He is a nurse.','He is a teacher.'],answer:'He is a waiter.',rule:'listen',source:'Students in a new class'},
 {id:'1-l5',type:'choice',prompt:'What instrument does Mr Tanaka sometimes play?',options:['The guitar','The piano','The violin'],answer:'The guitar',rule:'listen',source:'Students in a new class'},
 {id:'1-l6',type:'choice',prompt:'What does Silvie do?',options:['She is a nurse.','She is a student.','She is a waiter.'],answer:'She is a nurse.',rule:'listen',source:'Students in a new class'}
];
lessons[1].items=[
 {id:'2-1',type:'choice',prompt:'Choose the correct sentence.',options:['I work in a supermarket.','I works in a supermarket.','I am work in a supermarket.'],answer:'I work in a supermarket.',rule:'presentSimple',source:'Present Simple'},
 {id:'2-2',type:'choice',prompt:'Complete: Michael ___ at six thirty.',options:['wake up','wakes up','waking up'],answer:'wakes up',rule:'presentSimple',source:'Present Simple'},
 {id:'2-3',type:'order',prompt:'Build the sentence.',tokens:['coffee.','usually','drink','I'],answer:'I usually drink coffee.',rule:'frequency',source:'Present Simple'},
 {id:'2-4',type:'choice',prompt:'Choose the correct negative.',options:["We don't have children.","We doesn't have children.","We not have children."],answer:"We don't have children.",rule:'presentSimple',source:'Present Simple'},
 {id:'2-5',type:'choice',prompt:'Choose the correct question.',options:['What time does he start work?','What time he starts work?','What time do he start work?'],answer:'What time does he start work?',rule:'doQuestion',source:'Present Simple questions'},
 {id:'2-6',type:'input',prompt:'Complete: He ___ (work) in a supermarket.',answers:['works'],rule:'presentSimple',source:'Present Simple'},
 {id:'2-7',type:'choice',prompt:'Where does the frequency adverb go?',options:['I usually drink coffee.','I drink usually coffee.','Usually I coffee drink.'],answer:'I usually drink coffee.',rule:'frequency',source:'Adverbs of frequency'},
 {id:'2-8',type:'order',prompt:'Put the words in order to describe a regular action.',tokens:['English.','study','I','every day'],answer:'I study English every day.',rule:'frequency',source:'guided transfer from Listening A1 Tell me about your life'},
 {id:'2-9',type:'input',prompt:'Complete with a frequency word: I ___ study English.',answers:['always','usually','often','sometimes','rarely','never'],modelAnswer:'I usually study English.',rule:'frequency',source:'guided gap-fill'},
 {id:'2-10',type:'input',prompt:'Complete the question: Do you ___ English every day?',answers:['study','practice','learn'],modelAnswer:'Do you study English every day?',rule:'doQuestion',source:'guided gap-fill'}
];
lessons[1].listeningItems=[
 {id:'2-l1',type:'choice',prompt:'Where does Michael work?',options:['In a café','In a supermarket','At a school'],answer:'In a supermarket',rule:'listen',source:'Tell me about your life'},
 {id:'2-l2',type:'choice',prompt:'What time does Michael wake up on weekdays?',options:['At six thirty','At seven thirty','At eight o’clock'],answer:'At six thirty',rule:'listen',source:'Tell me about your life'},
 {id:'2-l3',type:'choice',prompt:'How does Michael go to work?',options:['By bike','By bus','By car'],answer:'By bike',rule:'listen',source:'Tell me about your life'},
 {id:'2-l4',type:'choice',prompt:'What does Michael usually have for breakfast?',options:['Coffee and a sandwich','Tea and toast','Eggs and fruit'],answer:'Coffee and a sandwich',rule:'listen',source:'Tell me about your life'},
 {id:'2-l5',type:'choice',prompt:'What does Michael want to do in the future?',options:['Travel and meet new people','Move to the city','Work in a café'],answer:'Travel and meet new people',rule:'listen',source:'Tell me about your life'}
];
lessons[2].items=[
 {id:'3-1',type:'choice',prompt:'Choose the correct sentence.',options:['Anna works in a café.','Anna work in a café.','Anna is work in a café.'],answer:'Anna works in a café.',rule:'presentSimple',source:'Present Simple'},
 {id:'3-2',type:'input',prompt:'Complete: Anna ___ up at seven o’clock.',answers:['wakes'],rule:'presentSimple',source:'Present Simple'},
 {id:'3-3',type:'order',prompt:'Build the sentence.',tokens:['bus.','by','work','to','go','I'],answer:'I go to work by bus.',rule:'wordOrder',source:'English word order'},
 {id:'3-4',type:'choice',prompt:'Choose the correct frequency sentence.',options:['She usually drinks coffee.','She drinks usually coffee.','Usually she coffee drinks.'],answer:'She usually drinks coffee.',rule:'frequency',source:'Adverbs of frequency'},
 {id:'3-5',type:'choice',prompt:'Choose the correct negative.',options:["Anna doesn't work at weekends.","Anna don't work at weekends.","Anna isn't work at weekends."],answer:"Anna doesn't work at weekends.",rule:'presentSimple',source:'Present Simple'},
 {id:'3-6',type:'choice',prompt:'Complete: ___ Anna read simple stories?',options:['Do','Does','Is'],answer:'Does',rule:'doQuestion',source:'Present Simple questions'},
 {id:'3-7',type:'input',prompt:'Complete: She ___ (watch) TV in the evening.',answers:['watches'],rule:'presentSimple',source:'Present Simple'},
 {id:'3-8',type:'choice',prompt:'Choose the correct sentence about free time.',options:['She reads a book in the evening.','She read a book in the evening every day.','She is read a book in the evening.'],answer:'She reads a book in the evening.',rule:'presentSimple',source:'Present Simple practice'},
 {id:'3-9',type:'input',prompt:'Complete the sentence: She ___ to work by bus.',answers:['goes','travels'],modelAnswer:'She goes to work by bus.',rule:'presentSimple',source:'guided gap-fill'},
 {id:'3-10',type:'input',prompt:'Complete the question: Do you ___ books in your free time?',answers:['read','buy','borrow'],modelAnswer:'Do you read books in your free time?',rule:'doQuestion',source:'guided gap-fill'}
];
lessons[2].listeningItems=[
 {id:'3-l1',type:'choice',prompt:'Where does Anna work?',options:['In a café','In a supermarket','At a school'],answer:'In a café',rule:'listen',source:'My Daily Life'},
 {id:'3-l2',type:'choice',prompt:'What time does Anna wake up?',options:['At six o’clock','At seven o’clock','At eight o’clock'],answer:'At seven o’clock',rule:'listen',source:'My Daily Life'},
 {id:'3-l3',type:'choice',prompt:'How does Anna go to work?',options:['By bus','By bike','By train'],answer:'By bus',rule:'listen',source:'My Daily Life'},
 {id:'3-l4',type:'choice',prompt:'What time does Anna finish work?',options:['At two o’clock','At four o’clock','At eight o’clock'],answer:'At four o’clock',rule:'listen',source:'My Daily Life'},
 {id:'3-l5',type:'choice',prompt:'What does Anna sometimes do at weekends?',options:['She meets her friends or stays at home.','She works in a café.','She goes to school.'],answer:'She meets her friends or stays at home.',rule:'listen',source:'My Daily Life'}
];
const data={version:3,lessons};if(typeof module==='object'&&module.exports)module.exports=data;else root.EvoCourseBank=data;
})(typeof globalThis==='object'?globalThis:this);
