(function(root){
'use strict';
const I=root.EvoCourseI18n;
if(!I||!I.ui)throw Error('Load i18n.js before i18n-22-30.js');
// Translate explanations and headings. English forms and examples stay English.
const ruleKeys=['pastBe','pastForms','pastDid','connectWords','manner','compareAdj','superlative','haveGot','thisIt','ownerS','canAbility','imperatives','objectPronouns','verbTo','simpleOrNow','someAny','quantity','willFuture'];
const forms=[
'I/he/she/it → was; you/we/they → were. wasn’t/weren’t. Was/Were + subject?',
'clean → cleaned; stop → stopped; study → studied; go → went; have → had; take → took.',
'Did + subject + base verb? Subject + didn’t + base verb. Did you go? I didn’t go.',
'and / but / or / so / because. I was tired, so I stayed home. I stayed home because I was tired.',
'slow → slowly; careful → carefully; good → well; fast → fast. A careful driver drives carefully.',
'cheap → cheaper; expensive → more expensive; good → better; bad → worse. A is cheaper than B.',
'the cheapest / the biggest / the most expensive / the best / the worst. A is the cheapest of three cars.',
'I/you/we/they have got; he/she/it has got. Have you got…? She hasn’t got…',
'This is my kitchen. It is bright. These are my books. They are new.',
'Anna’s kitchen; my parents’ house. Whose kitchen is this? It’s Anna’s.',
'can/can’t + base verb. I can swim. Can you help me? Yes, I can. No, I can’t.',
'Drink water. Don’t run here. Let’s take a break. Let’s not run.',
'I → me; he → him; she → her; we → us; they → them; you/it → you/it. She helps us.',
'want/need/would like + to + base verb; enjoy/don’t mind + verb-ing. I want to run. I enjoy running.',
'I run every day. I am running now. I like coffee ✓; I am liking coffee ✗.',
'a book / some books / some water. We haven’t got any books. Have you got any water?',
'How many books? How much water? a few books / a little water / a lot of books or water / no books.',
'will/won’t + base verb. I’ll help. I think it will rain. Will you come? Shall we go?'
];
const topics={
en:['Last weekend','Describe completed actions in the past.','Last summer','Ask past questions and connect ideas.','My last holiday','Talk about a trip and how things happened.','Comparing cars','Compare things and make a decision.','My favourite room','Describe possessions and nearby objects.','A fitness trainer’s job','Use can, instructions and object pronouns.','Activities and habits','Choose verb forms for wishes, habits and now.','Schools and quantities','Talk about countable nouns and amounts.','Cinema and final practice','Make offers, suggestions and predictions.'],
ru:['Прошлые выходные','Опишите завершённые действия в прошлом.','Прошлое лето','Задавайте вопросы о прошлом и связывайте мысли.','Мой последний отпуск','Расскажите о поездке и способе действия.','Сравниваем автомобили','Сравните предметы и примите решение.','Моя любимая комната','Опишите принадлежность и предметы рядом.','Работа фитнес-тренера','Используйте can, инструкции и объектные местоимения.','Занятия и привычки','Выбирайте формы для желаний, привычек и действий сейчас.','Школа и количество','Говорите об исчисляемых существительных и количестве.','Кино и итоговая практика','Делайте предложения, приглашения и прогнозы.'],
es:['El fin de semana pasado','Describe acciones terminadas en el pasado.','El verano pasado','Haz preguntas del pasado y conecta ideas.','Mis últimas vacaciones','Habla de un viaje y de cómo ocurrieron las cosas.','Comparar coches','Compara cosas y toma una decisión.','Mi habitación favorita','Describe posesiones y objetos cercanos.','El trabajo de una entrenadora','Usa can, instrucciones y pronombres de objeto.','Actividades y hábitos','Elige formas para deseos, hábitos y acciones actuales.','Escuelas y cantidades','Habla de nombres contables y cantidades.','Cine y práctica final','Haz ofertas, sugerencias y predicciones.'],
pt:['O fim de semana passado','Descreva ações concluídas no passado.','O verão passado','Faça perguntas no passado e conecte ideias.','Minhas últimas férias','Fale sobre uma viagem e como as coisas aconteceram.','Comparando carros','Compare coisas e tome uma decisão.','Meu cômodo favorito','Descreva posses e objetos próximos.','O trabalho de uma treinadora','Use can, instruções e pronomes de objeto.','Atividades e hábitos','Escolha formas para desejos, hábitos e ações atuais.','Escolas e quantidades','Fale sobre nomes contáveis e quantidades.','Cinema e prática final','Faça ofertas, sugestões e previsões.'],
de:['Letztes Wochenende','Beschreibe abgeschlossene Handlungen in der Vergangenheit.','Letzten Sommer','Stelle Fragen zur Vergangenheit und verbinde Gedanken.','Mein letzter Urlaub','Erzähle von einer Reise und wie etwas geschah.','Autos vergleichen','Vergleiche Dinge und triff eine Entscheidung.','Mein Lieblingszimmer','Beschreibe Besitz und Dinge in deiner Nähe.','Die Arbeit einer Fitnesstrainerin','Nutze can, Anweisungen und Objektpronomen.','Aktivitäten und Gewohnheiten','Wähle Verbformen für Wünsche, Gewohnheiten und jetzt.','Schulen und Mengen','Sprich über zählbare Nomen und Mengen.','Kino und Abschlussübung','Mache Angebote, Vorschläge und Vorhersagen.'],
fr:['Le week-end dernier','Décris des actions terminées dans le passé.','L’été dernier','Pose des questions au passé et relie les idées.','Mes dernières vacances','Parle d’un voyage et de la manière d’agir.','Comparer des voitures','Compare des choses et prends une décision.','Ma pièce préférée','Décris les possessions et les objets proches.','Le métier de coach sportif','Utilise can, des consignes et les pronoms compléments.','Activités et habitudes','Choisis les formes pour les souhaits, les habitudes et maintenant.','Écoles et quantités','Parle des noms dénombrables et des quantités.','Cinéma et pratique finale','Fais des offres, des suggestions et des prédictions.'],
it:['Lo scorso fine settimana','Descrivi azioni concluse nel passato.','L’estate scorsa','Fai domande sul passato e collega le idee.','Le mie ultime vacanze','Parla di un viaggio e di come sono avvenute le cose.','Confrontare automobili','Confronta cose e prendi una decisione.','La mia stanza preferita','Descrivi possesso e oggetti vicini.','Il lavoro di una personal trainer','Usa can, istruzioni e pronomi complemento.','Attività e abitudini','Scegli le forme per desideri, abitudini e azioni attuali.','Scuole e quantità','Parla di nomi numerabili e quantità.','Cinema e pratica finale','Fai offerte, proposte e previsioni.'],
hy:['Անցած հանգստյան օրերը','Նկարագրեք անցյալում ավարտված գործողությունները։','Անցած ամառը','Հարցրեք անցյալի մասին և կապեք մտքերը։','Իմ վերջին արձակուրդը','Պատմեք ճանապարհորդության և գործողությունների ձևի մասին։','Մեքենաների համեմատություն','Համեմատեք առարկաները և որոշում կայացրեք։','Իմ սիրելի սենյակը','Նկարագրեք պատկանելությունն ու մոտ գտնվող առարկաները։','Ֆիթնես մարզչի աշխատանքը','Օգտագործեք can, հրահանգներ և խնդիր դերանուններ։','Զբաղմունքներ և սովորություններ','Ընտրեք ցանկության, սովորության և ներկա գործողության բայաձևերը։','Դպրոցներ և քանակներ','Խոսեք հաշվելի գոյականների և քանակների մասին։','Կինո և ամփոփիչ վարժություն','Արեք առաջարկներ և կանխատեսումներ։'],
'zh-Hans':['上个周末','描述过去已完成的动作。','去年夏天','询问过去的事情并连接想法。','我的上次假期','谈论旅行和动作发生的方式。','比较汽车','比较事物并作出决定。','我最喜欢的房间','描述所属关系和附近的物品。','健身教练的工作','使用 can、指令和宾格代词。','活动与习惯','选择表达愿望、习惯和当前动作的形式。','学校与数量','谈论可数名词和数量。','电影与最后练习','提出帮助、建议和预测。'],
ja:['先週末','過去に完了した動作を説明します。','去年の夏','過去について質問し、考えをつなぎます。','前回の休暇','旅行と動作の様子について話します。','車を比較する','物を比較して決定します。','お気に入りの部屋','所有と近くにある物を説明します。','フィットネストレーナーの仕事','can、指示、目的格代名詞を使います。','活動と習慣','希望、習慣、今の動作に合う形を選びます。','学校と数量','可算名詞と量について話します。','映画と最後の練習','申し出、提案、予測をします。'],
ko:['지난 주말','과거에 끝난 행동을 설명하세요.','지난여름','과거를 질문하고 생각을 연결하세요.','지난 휴가','여행과 행동의 방식을 이야기하세요.','자동차 비교','사물을 비교하고 결정하세요.','내가 좋아하는 방','소유와 가까운 물건을 설명하세요.','피트니스 트레이너의 일','can, 지시문, 목적격 대명사를 사용하세요.','활동과 습관','희망, 습관, 현재 행동에 맞는 형태를 고르세요.','학교와 수량','셀 수 있는 명사와 양을 이야기하세요.','영화와 마지막 연습','제안, 권유, 예측을 하세요.'],
hi:['पिछला सप्ताहांत','बीते समय की पूरी हुई क्रियाएँ बताएँ।','पिछली गर्मियाँ','अतीत के प्रश्न पूछें और विचार जोड़ें।','मेरी पिछली छुट्टी','यात्रा और काम करने के तरीके के बारे में बताएँ।','कारों की तुलना','चीज़ों की तुलना करें और निर्णय लें।','मेरा पसंदीदा कमरा','स्वामित्व और पास की वस्तुएँ बताएँ।','फिटनेस प्रशिक्षक का काम','can, निर्देश और कर्म सर्वनाम प्रयोग करें।','गतिविधियाँ और आदतें','इच्छा, आदत और अभी के लिए क्रिया रूप चुनें।','स्कूल और मात्रा','गणनीय संज्ञाओं और मात्रा पर बात करें।','सिनेमा और अंतिम अभ्यास','प्रस्ताव, सुझाव और अनुमान दें।'],
bn:['গত সপ্তাহান্ত','অতীতে শেষ হওয়া কাজ বর্ণনা করুন।','গত গ্রীষ্ম','অতীত নিয়ে প্রশ্ন করুন এবং ভাবনা যুক্ত করুন।','আমার শেষ ছুটি','ভ্রমণ ও কাজের ধরন নিয়ে বলুন।','গাড়ির তুলনা','জিনিসের তুলনা করে সিদ্ধান্ত নিন।','আমার প্রিয় ঘর','মালিকানা ও কাছের বস্তু বর্ণনা করুন।','ফিটনেস প্রশিক্ষকের কাজ','can, নির্দেশ ও কর্ম সর্বনাম ব্যবহার করুন।','কাজ ও অভ্যাস','ইচ্ছা, অভ্যাস ও বর্তমান কাজের জন্য রূপ বাছুন।','স্কুল ও পরিমাণ','গণনীয় বিশেষ্য ও পরিমাণ নিয়ে বলুন।','সিনেমা ও শেষ অনুশীলন','প্রস্তাব, পরামর্শ ও অনুমান দিন।'],
ur:['گزشتہ ہفتے کا اختتام','ماضی میں مکمل ہوئے کام بیان کریں۔','گزشتہ گرمیوں کا موسم','ماضی کے سوال پوچھیں اور خیالات جوڑیں۔','میری پچھلی چھٹی','سفر اور کام کے طریقے کے بارے میں بتائیں۔','گاڑیوں کا موازنہ','چیزوں کا موازنہ کریں اور فیصلہ کریں۔','میرا پسندیدہ کمرہ','ملکیت اور قریب کی چیزیں بیان کریں۔','فٹنس ٹرینر کا کام','can، ہدایات اور مفعولی ضمیر استعمال کریں۔','سرگرمیاں اور عادتیں','خواہش، عادت اور موجودہ عمل کے لیے فعل کی شکل چنیں۔','اسکول اور مقدار','قابل شمار اسم اور مقدار پر بات کریں۔','سنیما اور آخری مشق','پیشکش، تجاویز اور پیش گوئیاں کریں۔'],
ar:['عطلة نهاية الأسبوع الماضية','صف الأفعال المكتملة في الماضي.','الصيف الماضي','اسأل عن الماضي واربط الأفكار.','عطلتي الأخيرة','تحدث عن رحلة وكيفية حدوث الأفعال.','مقارنة السيارات','قارن الأشياء واتخذ قرارًا.','غرفتي المفضلة','صف الملكية والأشياء القريبة.','عمل مدرّبة اللياقة','استخدم can والتعليمات وضمائر المفعول.','الأنشطة والعادات','اختر الصيغ للرغبات والعادات والأفعال الحالية.','المدارس والكميات','تحدث عن الأسماء المعدودة والكميات.','السينما والتدريب الختامي','قدّم عروضًا واقتراحات وتوقعات.'],
id:['Akhir pekan lalu','Jelaskan tindakan yang selesai di masa lalu.','Musim panas lalu','Tanyakan masa lalu dan hubungkan ide.','Liburan terakhir saya','Ceritakan perjalanan dan cara melakukan sesuatu.','Membandingkan mobil','Bandingkan benda dan buat keputusan.','Ruangan favorit saya','Jelaskan kepemilikan dan benda di dekatmu.','Pekerjaan pelatih kebugaran','Gunakan can, instruksi dan kata ganti objek.','Aktivitas dan kebiasaan','Pilih bentuk untuk keinginan, kebiasaan dan saat ini.','Sekolah dan jumlah','Bicarakan kata benda terhitung dan jumlah.','Bioskop dan latihan akhir','Buat tawaran, saran dan prediksi.'],
tr:['Geçen hafta sonu','Geçmişte tamamlanan eylemleri anlatın.','Geçen yaz','Geçmiş hakkında soru sorun ve fikirleri bağlayın.','Son tatilim','Bir yolculuğu ve eylemlerin nasıl yapıldığını anlatın.','Arabaları karşılaştırma','Nesneleri karşılaştırın ve karar verin.','En sevdiğim oda','Sahipliği ve yakındaki nesneleri anlatın.','Fitness eğitmeninin işi','can, talimatlar ve nesne zamirlerini kullanın.','Etkinlikler ve alışkanlıklar','İstek, alışkanlık ve şimdiki eylem için biçim seçin.','Okullar ve miktarlar','Sayılabilir isimler ve miktarlar hakkında konuşun.','Sinema ve son alıştırma','Teklif, öneri ve tahmin yapın.'],
vi:['Cuối tuần trước','Mô tả hành động đã hoàn thành trong quá khứ.','Mùa hè trước','Hỏi về quá khứ và liên kết ý tưởng.','Kỳ nghỉ gần nhất','Kể về chuyến đi và cách hành động diễn ra.','So sánh ô tô','So sánh đồ vật và đưa ra quyết định.','Căn phòng yêu thích','Mô tả sự sở hữu và đồ vật ở gần.','Công việc huấn luyện viên','Dùng can, câu hướng dẫn và đại từ tân ngữ.','Hoạt động và thói quen','Chọn dạng cho mong muốn, thói quen và hiện tại.','Trường học và số lượng','Nói về danh từ đếm được và lượng.','Điện ảnh và luyện tập cuối','Đưa ra lời đề nghị, gợi ý và dự đoán.'],
kk:['Өткен демалыс','Өткендегі аяқталған әрекеттерді сипаттаңыз.','Өткен жаз','Өткен шақ туралы сұрақ қойып, ойларды байланыстырыңыз.','Соңғы демалысым','Сапар мен әрекеттің қалай болғанын айтыңыз.','Көліктерді салыстыру','Заттарды салыстырып, шешім қабылдаңыз.','Сүйікті бөлмем','Иелік пен жақын заттарды сипаттаңыз.','Фитнес жаттықтырушысының жұмысы','can, нұсқаулар және толықтауыш есімдіктерін қолданыңыз.','Әрекеттер мен әдеттер','Қалау, әдет және қазіргі әрекетке лайық түрді таңдаңыз.','Мектептер және мөлшер','Саналатын зат есімдер мен мөлшер туралы айтыңыз.','Кино және қорытынды жаттығу','Ұсыныстар мен болжамдар жасаңыз.'],
uz:['O‘tgan dam olish kunlari','O‘tmishda tugagan harakatlarni tasvirlang.','O‘tgan yoz','O‘tmish haqida so‘rang va fikrlarni bog‘lang.','Oxirgi ta’tilim','Safar va harakatning qanday bo‘lganini ayting.','Mashinalarni taqqoslash','Narsalarni taqqoslang va qaror qiling.','Sevimli xonam','Egalik va yaqin narsalarni tasvirlang.','Fitnes murabbiyining ishi','can, ko‘rsatmalar va to‘ldiruvchi olmoshlarini ishlating.','Mashg‘ulotlar va odatlar','Istak, odat va hozirgi harakat uchun shakl tanlang.','Maktablar va miqdorlar','Sanaladigan otlar va miqdorlar haqida gapiring.','Kino va yakuniy mashq','Takliflar, maslahatlar va taxminlar bildiring.']
};
const labels={
en:['Past forms of be','Regular and irregular past verbs','Past questions and negatives: use the base verb','Addition, contrast, choice, result and reason','Adjectives describe nouns; adverbs describe actions','Compare two things','Compare one thing with a whole group','Possession with have got','This introduces something nearby; it refers back','Ownership: singular ’s, regular plural s’','Ability or permission: can + base verb','Instructions and suggestions','Subject before the verb; object after a verb or preposition','Choose the second verb’s form','Habit versus an action now; like describes a state','Countable singular, affirmative some, negative/question any','Many/a few for countable nouns; much/a little for uncountable nouns','Decisions now, promises, offers and predictions'],
ru:['Прошедшие формы be','Правильные и неправильные глаголы в прошлом','Вопросы и отрицания в прошлом: начальная форма глагола','Добавление, противопоставление, выбор, результат и причина','Прилагательное описывает предмет; наречие — действие','Сравнение двух предметов','Сравнение одного предмета со всей группой','Обладание с have got','This вводит близкий предмет; it отсылает к упомянутому','Принадлежность: единственное число ’s, обычное множественное s’','Способность или разрешение: can + начальная форма','Инструкции и предложения','Подлежащее перед глаголом; дополнение после глагола или предлога','Выберите форму второго глагола','Привычка или действие сейчас; like описывает состояние','Исчисляемое единственное число, some в утверждении, any в отрицании и вопросе','Many/a few — исчисляемые; much/a little — неисчисляемые','Решения сейчас, обещания, помощь и прогнозы'],
es:['Pasado de be','Verbos regulares e irregulares en pasado','Preguntas y negaciones en pasado: verbo base','Adición, contraste, elección, resultado y causa','Adjetivos para nombres; adverbios para acciones','Compara dos cosas','Compara una cosa con todo un grupo','Posesión con have got','This presenta algo cercano; it retoma lo mencionado','Posesión: singular ’s, plural regular s’','Capacidad o permiso: can + verbo base','Instrucciones y sugerencias','Sujeto antes del verbo; objeto después de verbo o preposición','Elige la forma del segundo verbo','Hábito o acción actual; like expresa un estado','Singular contable, some afirmativo, any negativo o interrogativo','Many/a few para contables; much/a little para incontables','Decisiones inmediatas, promesas, ofertas y predicciones'],
pt:['Passado de be','Verbos regulares e irregulares no passado','Perguntas e negativas no passado: verbo base','Adição, contraste, escolha, resultado e motivo','Adjetivos descrevem nomes; advérbios descrevem ações','Compare duas coisas','Compare uma coisa com todo um grupo','Posse com have got','This apresenta algo próximo; it retoma o mencionado','Posse: singular ’s, plural regular s’','Capacidade ou permissão: can + verbo base','Instruções e sugestões','Sujeito antes do verbo; objeto após verbo ou preposição','Escolha a forma do segundo verbo','Hábito ou ação atual; like expressa um estado','Singular contável, some afirmativo, any negativo ou interrogativo','Many/a few para contáveis; much/a little para incontáveis','Decisões imediatas, promessas, ofertas e previsões'],
de:['Vergangenheit von be','Regelmäßige und unregelmäßige Vergangenheitsformen','Fragen und Verneinungen im Past Simple: Grundform','Ergänzung, Gegensatz, Wahl, Folge und Grund','Adjektive beschreiben Nomen; Adverbien beschreiben Handlungen','Vergleiche zwei Dinge','Vergleiche ein Ding mit einer ganzen Gruppe','Besitz mit have got','This führt etwas Nahes ein; it verweist auf Bekanntes','Besitz: Einzahl ’s, regelmäßige Mehrzahl s’','Fähigkeit oder Erlaubnis: can + Grundform','Anweisungen und Vorschläge','Subjekt vor dem Verb; Objekt nach Verb oder Präposition','Wähle die Form des zweiten Verbs','Gewohnheit oder Handlung jetzt; like beschreibt einen Zustand','Zählbare Einzahl, some positiv, any negativ oder in Fragen','Many/a few für zählbare; much/a little für unzählbare Nomen','Sofortige Entscheidungen, Versprechen, Angebote und Vorhersagen'],
fr:['Passé de be','Verbes réguliers et irréguliers au passé','Questions et négations au passé : verbe de base','Ajout, contraste, choix, résultat et raison','Adjectifs pour les noms ; adverbes pour les actions','Compare deux choses','Compare une chose à tout un groupe','Possession avec have got','This présente un objet proche ; it reprend ce qui est mentionné','Possession : singulier ’s, pluriel régulier s’','Capacité ou permission : can + verbe de base','Consignes et suggestions','Sujet avant le verbe ; complément après un verbe ou une préposition','Choisis la forme du second verbe','Habitude ou action actuelle ; like exprime un état','Singulier dénombrable, some affirmatif, any négatif ou interrogatif','Many/a few pour dénombrables ; much/a little pour indénombrables','Décisions immédiates, promesses, offres et prédictions'],
it:['Passato di be','Verbi regolari e irregolari al passato','Domande e negazioni al passato: verbo base','Aggiunta, contrasto, scelta, risultato e motivo','Aggettivi per i nomi; avverbi per le azioni','Confronta due cose','Confronta una cosa con un intero gruppo','Possesso con have got','This presenta un oggetto vicino; it riprende quello menzionato','Possesso: singolare ’s, plurale regolare s’','Capacità o permesso: can + verbo base','Istruzioni e proposte','Soggetto prima del verbo; complemento dopo verbo o preposizione','Scegli la forma del secondo verbo','Abitudine o azione attuale; like esprime uno stato','Singolare numerabile, some affermativo, any negativo o interrogativo','Many/a few per numerabili; much/a little per non numerabili','Decisioni immediate, promesse, offerte e previsioni'],
hy:['be բայի անցյալ ձևերը','Կանոնավոր և անկանոն բայերը անցյալում','Անցյալի հարցեր և ժխտումներ՝ բայի սկզբնական ձև','Հավելում, հակադրություն, ընտրություն, արդյունք և պատճառ','Ածականը նկարագրում է առարկան, մակբայը՝ գործողությունը','Համեմատեք երկու առարկա','Համեմատեք առարկան ամբողջ խմբի հետ','Ունենալը՝ have got ձևով','This-ը ներկայացնում է մոտ առարկա, it-ը՝ արդեն նշվածը','Պատկանելություն՝ եզակի ’s, կանոնավոր հոգնակի s’','Կարողություն կամ թույլտվություն՝ can + բայի սկզբնական ձև','Հրահանգներ և առաջարկներ','Ենթական՝ բայից առաջ, խնդիրը՝ բայից կամ նախդիրից հետո','Ընտրեք երկրորդ բայի ձևը','Սովորություն կամ գործողություն հիմա, like-ը վիճակ է նկարագրում','Հաշվելի եզակի, some՝ հաստատում, any՝ ժխտում կամ հարց','Many/a few՝ հաշվելի, much/a little՝ անհաշվելի','Որոշումներ հիմա, խոստումներ, առաջարկներ և կանխատեսումներ'],
'zh-Hans':['be 的过去式','规则和不规则动词的过去式','过去时疑问与否定：使用动词原形','添加、对比、选择、结果和原因','形容词描述名词；副词描述动作','比较两件事物','将一件事物与整组比较','用 have got 表达拥有','This 引入近处事物；it 指代前文','所属关系：单数 ’s，规则复数 s’','能力或许可：can + 动词原形','指令和建议','主语在动词前；宾语在动词或介词后','选择第二个动词的形式','习惯或当前动作；like 表达状态','可数单数；肯定用 some，否定或疑问用 any','可数用 many/a few；不可数用 much/a little','当下决定、承诺、提供帮助和预测'],
ja:['be の過去形','規則動詞と不規則動詞の過去形','過去の疑問と否定：動詞の原形','追加、対比、選択、結果、理由','形容詞は名詞を、副詞は動作を説明','二つの物を比較','一つの物をグループ全体と比較','have got で所有を表す','This は近くの物を紹介し、it は既出の物を指す','所有：単数 ’s、規則的な複数 s’','能力や許可：can + 動詞の原形','指示と提案','主語は動詞の前、目的語は動詞や前置詞の後','二つ目の動詞の形を選ぶ','習慣と今の動作；like は状態を表す','可算単数；肯定の some、否定・疑問の any','可算に many/a few、不可算に much/a little','今の決定、約束、申し出、予測'],
ko:['be의 과거형','규칙·불규칙 동사의 과거형','과거의 질문과 부정: 동사원형 사용','추가, 대조, 선택, 결과, 이유','형용사는 명사, 부사는 행동을 설명','두 사물 비교','한 사물을 전체 집단과 비교','have got으로 소유 표현','This는 가까운 것을 소개하고 it은 앞의 것을 지칭','소유: 단수 ’s, 규칙 복수 s’','능력이나 허가: can + 동사원형','지시와 제안','주어는 동사 앞, 목적어는 동사나 전치사 뒤','두 번째 동사의 형태 선택','습관과 현재 행동; like는 상태를 표현','셀 수 있는 단수, 긍정 some, 부정·질문 any','가산에 many/a few, 불가산에 much/a little','즉석 결정, 약속, 제안, 예측'],
hi:['be के भूतकाल रूप','नियमित और अनियमित भूतकाल क्रियाएँ','भूतकाल के प्रश्न और नकार: क्रिया का मूल रूप','जोड़, विरोध, विकल्प, परिणाम और कारण','विशेषण संज्ञा बताते हैं; क्रिया विशेषण काम का तरीका','दो चीज़ों की तुलना','एक चीज़ की पूरे समूह से तुलना','have got से स्वामित्व','This पास की चीज़ बताता है; it पहले कही चीज़','स्वामित्व: एकवचन ’s, नियमित बहुवचन s’','क्षमता या अनुमति: can + मूल क्रिया','निर्देश और सुझाव','कर्ता क्रिया से पहले; कर्म क्रिया या पूर्वसर्ग के बाद','दूसरी क्रिया का रूप चुनें','आदत या अभी का काम; like एक अवस्था बताता है','गणनीय एकवचन, हाँ में some, नकार या प्रश्न में any','गणनीय के लिए many/a few; अगणनीय के लिए much/a little','अभी के निर्णय, वादे, प्रस्ताव और अनुमान'],
bn:['be-এর অতীত রূপ','নিয়মিত ও অনিয়মিত অতীত ক্রিয়া','অতীতের প্রশ্ন ও নেতিবাচক বাক্য: ক্রিয়ার মূল রূপ','যোগ, বৈপরীত্য, পছন্দ, ফল ও কারণ','বিশেষণ বস্তু বর্ণনা করে; ক্রিয়া বিশেষণ কাজের ধরন','দুটি জিনিসের তুলনা','একটি জিনিসের পুরো দলের সঙ্গে তুলনা','have got দিয়ে মালিকানা','This কাছের বস্তু পরিচয় করায়; it আগের বস্তুকে বোঝায়','মালিকানা: একবচনে ’s, নিয়মিত বহুবচনে s’','সামর্থ্য বা অনুমতি: can + মূল ক্রিয়া','নির্দেশ ও প্রস্তাব','কর্তা ক্রিয়ার আগে; কর্ম ক্রিয়া বা পদান্বয়ের পরে','দ্বিতীয় ক্রিয়ার রূপ বাছুন','অভ্যাস বা বর্তমান কাজ; like অবস্থা বোঝায়','গণনীয় একবচন, ইতিবাচকে some, নেতিবাচক বা প্রশ্নে any','গণনীয়ে many/a few; অগণনীয়ে much/a little','তাৎক্ষণিক সিদ্ধান্ত, প্রতিশ্রুতি, প্রস্তাব ও অনুমান'],
ur:['be کی ماضی کی شکلیں','ماضی کے باقاعدہ اور بے قاعدہ افعال','ماضی کے سوال اور نفی: فعل کی بنیادی شکل','اضافہ، تضاد، انتخاب، نتیجہ اور وجہ','صفت اسم کو بتاتی ہے؛ متعلق فعل کام کا طریقہ','دو چیزوں کا موازنہ','ایک چیز کا پورے گروہ سے موازنہ','have got سے ملکیت','This قریب کی چیز متعارف کرتا ہے؛ it پہلے ذکر شدہ چیز','ملکیت: واحد ’s، باقاعدہ جمع s’','صلاحیت یا اجازت: can + بنیادی فعل','ہدایات اور تجاویز','فاعل فعل سے پہلے؛ مفعول فعل یا حرف جار کے بعد','دوسرے فعل کی شکل چنیں','عادت یا موجودہ کام؛ like کیفیت بتاتا ہے','قابل شمار واحد، مثبت میں some، نفی یا سوال میں any','قابل شمار کے لیے many/a few؛ ناقابل شمار کے لیے much/a little','فوری فیصلے، وعدے، پیشکشیں اور پیش گوئیاں'],
ar:['صيغ be في الماضي','الأفعال المنتظمة وغير المنتظمة في الماضي','أسئلة الماضي والنفي: استخدم الفعل الأساسي','الإضافة والتباين والاختيار والنتيجة والسبب','الصفات تصف الأسماء؛ الظروف تصف الأفعال','قارن شيئين','قارن شيئًا بالمجموعة كلها','الملكية باستخدام have got','This يقدم شيئًا قريبًا؛ it يعود إلى المذكور','الملكية: المفرد ’s، الجمع المنتظم s’','القدرة أو الإذن: can + الفعل الأساسي','التعليمات والاقتراحات','الفاعل قبل الفعل؛ المفعول بعد فعل أو حرف جر','اختر صيغة الفعل الثاني','عادة أو فعل الآن؛ like يصف حالة','مفرد معدود، some للإثبات، any للنفي أو السؤال','Many/a few للمعدود؛ much/a little لغير المعدود','قرارات فورية ووعود وعروض وتوقعات'],
id:['Bentuk lampau be','Kata kerja lampau beraturan dan tidak beraturan','Pertanyaan dan negasi lampau: kata kerja dasar','Penambahan, pertentangan, pilihan, hasil dan alasan','Kata sifat menjelaskan benda; kata keterangan menjelaskan tindakan','Bandingkan dua benda','Bandingkan satu benda dengan seluruh kelompok','Kepemilikan dengan have got','This memperkenalkan benda dekat; it merujuk kembali','Kepemilikan: tunggal ’s, jamak beraturan s’','Kemampuan atau izin: can + kata kerja dasar','Instruksi dan saran','Subjek sebelum kata kerja; objek setelah kata kerja atau preposisi','Pilih bentuk kata kerja kedua','Kebiasaan atau tindakan kini; like menyatakan keadaan','Tunggal terhitung, some positif, any negatif atau pertanyaan','Many/a few untuk terhitung; much/a little untuk tak terhitung','Keputusan langsung, janji, tawaran dan prediksi'],
tr:['be fiilinin geçmiş biçimleri','Düzenli ve düzensiz geçmiş fiiller','Geçmiş sorular ve olumsuzluk: yalın fiil','Ekleme, karşıtlık, seçim, sonuç ve neden','Sıfat isimleri, zarf eylemleri anlatır','İki şeyi karşılaştırın','Bir şeyi tüm grupla karşılaştırın','have got ile sahiplik','This yakını tanıtır; it önceki şeyi belirtir','Sahiplik: tekil ’s, düzenli çoğul s’','Yetenek veya izin: can + yalın fiil','Talimatlar ve öneriler','Özne fiilden önce; nesne fiil veya edattan sonra','İkinci fiilin biçimini seçin','Alışkanlık veya şimdiki eylem; like durum anlatır','Sayılabilir tekil, olumlu some, olumsuz veya soruda any','Sayılabilir için many/a few; sayılamaz için much/a little','Anlık kararlar, sözler, teklifler ve tahminler'],
vi:['Dạng quá khứ của be','Động từ quá khứ có quy tắc và bất quy tắc','Câu hỏi và phủ định quá khứ: động từ nguyên mẫu','Bổ sung, đối lập, lựa chọn, kết quả và lý do','Tính từ mô tả danh từ; trạng từ mô tả hành động','So sánh hai đồ vật','So sánh một vật với cả nhóm','Sở hữu với have got','This giới thiệu vật ở gần; it chỉ lại vật đã nói','Sở hữu: số ít ’s, số nhiều có quy tắc s’','Khả năng hoặc cho phép: can + động từ nguyên mẫu','Hướng dẫn và gợi ý','Chủ ngữ trước động từ; tân ngữ sau động từ hoặc giới từ','Chọn dạng của động từ thứ hai','Thói quen hoặc hành động hiện tại; like chỉ trạng thái','Số ít đếm được, some khẳng định, any phủ định hoặc câu hỏi','Many/a few cho đếm được; much/a little cho không đếm được','Quyết định tức thì, lời hứa, đề nghị và dự đoán'],
kk:['be етістігінің өткен шақ түрлері','Өткен шақтағы дұрыс және бұрыс етістіктер','Өткен шақ сұрақтары мен болымсыздық: бастапқы етістік','Қосу, қарама-қарсылық, таңдау, нәтиже және себеп','Сын есім затты, үстеу әрекетті сипаттайды','Екі затты салыстырыңыз','Бір затты бүкіл топпен салыстырыңыз','have got арқылы иелік','This жақын затты таныстырады; it аталған затқа сілтейді','Иелік: жекеше ’s, қалыпты көпше s’','Қабілет не рұқсат: can + бастапқы етістік','Нұсқаулар мен ұсыныстар','Бастауыш етістіктен бұрын; толықтауыш етістік не предлогтан кейін','Екінші етістіктің түрін таңдаңыз','Әдет немесе қазір әрекет; like күйді білдіреді','Саналатын жекеше, болымды some, болымсыз не сұрақ any','Саналатынға many/a few; саналмайтынға much/a little','Қазіргі шешімдер, уәделер, ұсыныстар және болжамдар'],
uz:['be fe’lining o‘tgan zamon shakllari','O‘tgan zamondagi to‘g‘ri va noto‘g‘ri fe’llar','O‘tgan zamon savol va inkori: asosiy fe’l','Qo‘shish, qarama-qarshilik, tanlov, natija va sabab','Sifat otni, ravish harakatni tasvirlaydi','Ikki narsani taqqoslang','Bir narsani butun guruh bilan taqqoslang','have got bilan egalik','This yaqin narsani tanishtiradi; it oldingi narsaga ishora qiladi','Egalik: birlik ’s, odatiy ko‘plik s’','Qobiliyat yoki ruxsat: can + asosiy fe’l','Ko‘rsatmalar va takliflar','Ega fe’ldan oldin; to‘ldiruvchi fe’l yoki predlogdan keyin','Ikkinchi fe’l shaklini tanlang','Odat yoki hozirgi harakat; like holatni bildiradi','Sanaladigan birlik, tasdiqda some, inkor yoki savolda any','Sanaladigan uchun many/a few; sanalmaydigan uchun much/a little','Hozirgi qarorlar, va’dalar, takliflar va taxminlar']
};
const endings={en:'A1 course · 30 lessons',ru:'Курс A1 · 30 уроков',es:'Curso A1 · 30 lecciones',pt:'Curso A1 · 30 lições',de:'A1-Kurs · 30 Lektionen',fr:'Cours A1 · 30 leçons',it:'Corso A1 · 30 lezioni',hy:'A1 դասընթաց · 30 դաս','zh-Hans':'A1 课程 · 30 课',ja:'A1コース · 全30課',ko:'A1 과정 · 30개 수업',hi:'A1 पाठ्यक्रम · 30 पाठ',bn:'A1 কোর্স · 30টি পাঠ',ur:'A1 کورس · 30 اسباق',ar:'دورة A1 · 30 درسًا',id:'Kursus A1 · 30 pelajaran',tr:'A1 kursu · 30 ders',vi:'Khóa A1 · 30 bài học',kk:'A1 курсы · 30 сабақ',uz:'A1 kursi · 30 dars'};
const completion={"en":"A1 course complete!","ru":"Курс A1 завершён!","es":"¡Curso A1 completado!","pt":"Curso A1 concluído!","de":"A1-Kurs abgeschlossen!","fr":"Cours A1 terminé !","it":"Corso A1 completato!","hy":"A1 դասընթացն ավարտված է։","zh-Hans":"A1 课程已完成！","ja":"A1コース修了！","ko":"A1 과정 완료!","hi":"A1 पाठ्यक्रम पूरा हुआ!","bn":"A1 কোর্স সম্পন্ন!","ur":"A1 کورس مکمل ہو گیا!","ar":"اكتملت دورة A1!","id":"Kursus A1 selesai!","tr":"A1 kursu tamamlandı!","vi":"Đã hoàn thành khóa A1!","kk":"A1 курсы аяқталды!","uz":"A1 kursi yakunlandi!"};
for(const {code} of I.languages){
 const values=topics[code],names=labels[code];
 if(!values||values.length!==18||!names||names.length!==ruleKeys.length||!endings[code])throw Error('Missing final A1 translation: '+code);
 for(let index=0;index<9;index++){I.ui[code]['l'+(index+22)]=values[index*2];I.ui[code]['g'+(index+22)]=values[index*2+1];}
 ruleKeys.forEach((key,index)=>{I.ui[code][key]=names[index]+': '+forms[index];I.ui[code][key+'Short']=names[index];});
 I.ui[code].pilot=endings[code];
 I.ui[code].moduleDone=completion[code];
}
})(typeof globalThis==='object'?globalThis:this);
