(function(root){
'use strict';
const I=root.EvoCourseI18n;if(!I)return;
const keys=['l10','g10','l11','g11','l12','g12','transportPoint','transportVehicle','timeAtInOn','timeNoPreposition','questionsWithBe','questionsWithDo','pilot'];
const words={
 en:['Around the city','Use at, in and on to talk about places and transport.','My daily schedule','Talk about clock times, days and parts of the day.','Countries and languages','Ask where someone is from and which languages they speak.','Use at for a specific point, such as at the bus stop, and in for an area, such as in the city.','Use on for buses and the metro, but in for a taxi or car.','Use at for clock times (at 7:00), in for parts of the day (in the evening), and on for days (on Monday).','Do not add at, in or on before every, next, last or this: every weekday, next Monday.','With be, put am, is or are before the subject: Where is Emma from?','For other Present Simple verbs, use do or does + subject + base verb: What language does she speak?','Prototype · 12 A1 lessons · the rest of the course is in development.'],
 ru:['По городу','Используйте at, in и on для мест и транспорта.','Мой распорядок дня','Говорите о времени, днях и частях суток.','Страны и языки','Спросите, откуда человек и на каких языках он говорит.','Для конкретного места используйте at: at the bus stop. Для территории — in: in the city.','В автобусе и метро используйте on, а в такси и машине — in.','Для точного времени используйте at (at 7:00), для частей суток — in (in the evening), для дней — on (on Monday).','Перед every, next, last и this не ставьте at, in или on: every weekday, next Monday.','В вопросе с be ставьте am, is или are перед подлежащим: Where is Emma from?','С другими глаголами в Present Simple используйте do или does + подлежащее + начальную форму глагола: What language does she speak?','Прототип · 12 уроков A1 · остальная часть курса в разработке.'],
 es:['Por la ciudad','Usa at, in y on para hablar de lugares y transportes.','Mi rutina diaria','Habla de horas, días y momentos del día.','Países e idiomas','Pregunta de dónde es alguien y qué idiomas habla.','Usa at para un punto concreto, como at the bus stop, e in para una zona, como in the city.','Usa on para el autobús y el metro, pero in para un taxi o coche.','Usa at para las horas (at 7:00), in para los momentos del día (in the evening) y on para los días (on Monday).','No añadas at, in ni on antes de every, next, last o this: every weekday, next Monday.','Con be, coloca am, is o are antes del sujeto: Where is Emma from?','Con otros verbos en Present Simple, usa do o does + sujeto + verbo base: What language does she speak?','Prototipo · 12 lecciones A1 · el resto del curso está en desarrollo.'],
 pt:['Pela cidade','Use at, in e on para falar de lugares e transportes.','Minha rotina diária','Fale sobre horas, dias e partes do dia.','Países e idiomas','Pergunte de onde alguém é e que idiomas fala.','Use at para um ponto específico, como at the bus stop, e in para uma área, como in the city.','Use on para ônibus e metrô, mas in para táxi ou carro.','Use at para horas (at 7:00), in para partes do dia (in the evening) e on para dias (on Monday).','Não use at, in ou on antes de every, next, last ou this: every weekday, next Monday.','Com be, coloque am, is ou are antes do sujeito: Where is Emma from?','Com outros verbos no Present Simple, use do ou does + sujeito + verbo base: What language does she speak?','Protótipo · 12 aulas A1 · o restante do curso está em desenvolvimento.'],
 de:['Unterwegs in der Stadt','Verwende at, in und on für Orte und Verkehrsmittel.','Mein Tagesablauf','Sprich über Uhrzeiten, Tage und Tageszeiten.','Länder und Sprachen','Frage, woher jemand kommt und welche Sprachen er spricht.','Verwende at für einen bestimmten Punkt wie at the bus stop und in für ein Gebiet wie in the city.','Verwende on für Bus und Metro, aber in für Taxi und Auto.','Verwende at für Uhrzeiten (at 7:00), in für Tageszeiten (in the evening) und on für Tage (on Monday).','Setze vor every, next, last oder this kein at, in oder on: every weekday, next Monday.','Bei be steht am, is oder are vor dem Subjekt: Where is Emma from?','Bei anderen Verben im Present Simple verwende do oder does + Subjekt + Grundform: What language does she speak?','Prototyp · 12 A1-Lektionen · der Rest des Kurses wird entwickelt.'],
 fr:['En ville','Utilise at, in et on pour parler des lieux et des transports.','Ma routine quotidienne','Parle des heures, des jours et des moments de la journée.','Pays et langues','Demande d’où vient une personne et quelles langues elle parle.','Utilise at pour un point précis, comme at the bus stop, et in pour une zone, comme in the city.','Utilise on pour le bus et le métro, mais in pour un taxi ou une voiture.','Utilise at pour les heures (at 7:00), in pour les moments de la journée (in the evening) et on pour les jours (on Monday).','Ne mets pas at, in ou on avant every, next, last ou this : every weekday, next Monday.','Avec be, place am, is ou are avant le sujet : Where is Emma from?','Avec les autres verbes au Present Simple, utilise do ou does + sujet + base verbale : What language does she speak?','Prototype · 12 leçons A1 · la suite du cours est en préparation.'],
 it:['In giro per la città','Usa at, in e on per parlare di luoghi e trasporti.','La mia routine quotidiana','Parla di orari, giorni e momenti della giornata.','Paesi e lingue','Chiedi da dove viene una persona e quali lingue parla.','Usa at per un punto preciso, come at the bus stop, e in per un’area, come in the city.','Usa on per autobus e metro, ma in per taxi e auto.','Usa at per gli orari (at 7:00), in per le parti del giorno (in the evening) e on per i giorni (on Monday).','Non aggiungere at, in o on prima di every, next, last o this: every weekday, next Monday.','Con be, metti am, is o are prima del soggetto: Where is Emma from?','Con gli altri verbi al Present Simple, usa do o does + soggetto + forma base: What language does she speak?','Prototipo · 12 lezioni A1 · il resto del corso è in preparazione.'],
 hy:['Քաղաքում','Վայրերի և փոխադրամիջոցների մասին խոսելիս օգտագործեք at, in և on։','Իմ օրվա ռեժիմը','Խոսեք ժամերի, օրերի և օրվա հատվածների մասին։','Երկրներ և լեզուներ','Հարցրեք՝ որտեղից է մարդը և ինչ լեզուներով է խոսում։','Կոնկրետ կետի համար օգտագործեք at, օրինակ՝ at the bus stop, իսկ տարածքի համար՝ in, օրինակ՝ in the city։','Ավտոբուսի և մետրոյի համար օգտագործեք on, իսկ տաքսու և մեքենայի համար՝ in։','Ժամերի համար օգտագործեք at (at 7:00), օրվա հատվածների համար՝ in (in the evening), օրերի համար՝ on (on Monday)։','every, next, last և this բառերից առաջ մի դրեք at, in կամ on՝ every weekday, next Monday։','be բայով հարցում am, is կամ are ձևը դրեք ենթակայից առաջ՝ Where is Emma from?','Present Simple-ի մյուս բայերի հետ օգտագործեք do կամ does + ենթակա + բայի հիմնական ձև՝ What language does she speak?','Նախատիպ · A1-ի 12 դաս · դասընթացի մնացած մասը մշակվում է։'],
 'zh-Hans':['城市出行','用 at、in 和 on 表达地点与交通方式。','我的日常安排','谈论钟点、日期和一天中的时段。','国家与语言','询问别人来自哪里、会说哪些语言。','表示具体地点用 at，如 at the bus stop；表示区域用 in，如 in the city。','乘坐公交车或地铁用 on；乘坐出租车或汽车用 in。','钟点用 at（at 7:00），一天中的时段用 in（in the evening），星期几用 on（on Monday）。','every、next、last 或 this 前不要加 at、in、on：every weekday、next Monday。','使用 be 提问时，把 am、is 或 are 放在主语前：Where is Emma from?','其他一般现在时动词提问时，用 do 或 does + 主语 + 动词原形：What language does she speak?','预览版 · 12 节 A1 课程 · 其余课程正在制作中。'],
 ja:['街の移動','場所や交通手段には at、in、on を使い分けます。','毎日の予定','時刻、曜日、時間帯について話します。','国と言語','出身地や話す言語を尋ねます。','特定の地点には at（at the bus stop）、地域には in（in the city）を使います。','バスや地下鉄には on、タクシーや車には in を使います。','時刻には at（at 7:00）、時間帯には in（in the evening）、曜日には on（on Monday）を使います。','every、next、last、this の前に at、in、on は付けません：every weekday、next Monday。','be の疑問文では am、is、are を主語の前に置きます：Where is Emma from?','一般動詞の現在形の疑問文では do または does + 主語 + 動詞の原形を使います：What language does she speak?','試作版 · A1 全12レッスン · 続きは制作中です。'],
 ko:['도시에서 이동하기','장소와 교통수단을 말할 때 at, in, on을 사용합니다.','나의 하루 일정','시각, 요일, 하루 중 시간을 말합니다.','나라와 언어','상대의 출신과 사용하는 언어를 묻습니다.','특정 지점에는 at(at the bus stop), 지역에는 in(in the city)을 씁니다.','버스와 지하철에는 on, 택시와 자동차에는 in을 씁니다.','시각에는 at(at 7:00), 하루 중 시간에는 in(in the evening), 요일에는 on(on Monday)을 씁니다.','every, next, last, this 앞에는 at, in, on을 쓰지 않습니다: every weekday, next Monday.','be 동사 의문문에서는 am, is, are를 주어 앞에 놓습니다: Where is Emma from?','다른 현재형 동사에는 do 또는 does + 주어 + 동사원형을 씁니다: What language does she speak?','미리보기 · A1 12개 수업 · 나머지 과정은 제작 중입니다.'],
 hi:['शहर में आना-जाना','स्थान और यातायात के लिए at, in और on का प्रयोग करें।','मेरी दिनचर्या','समय, दिन और दिन के हिस्सों के बारे में बोलें।','देश और भाषाएँ','पूछें कि कोई कहाँ से है और कौन-सी भाषाएँ बोलता है।','किसी निश्चित स्थान के लिए at, जैसे at the bus stop; क्षेत्र के लिए in, जैसे in the city, प्रयोग करें।','बस और मेट्रो के लिए on, लेकिन टैक्सी और कार के लिए in प्रयोग करें।','घड़ी के समय के लिए at (at 7:00), दिन के हिस्से के लिए in (in the evening), और दिनों के लिए on (on Monday) प्रयोग करें।','every, next, last या this से पहले at, in या on न लगाएँ: every weekday, next Monday।','be वाले प्रश्न में am, is या are को कर्ता से पहले रखें: Where is Emma from?','Present Simple के अन्य क्रियापदों के साथ do या does + कर्ता + क्रिया का मूल रूप प्रयोग करें: What language does she speak?','प्रोटोटाइप · A1 के 12 पाठ · बाकी पाठ तैयार किए जा रहे हैं।'],
 bn:['শহরে চলাচল','স্থান ও যানবাহন বোঝাতে at, in এবং on ব্যবহার করুন।','আমার দৈনন্দিন সময়সূচি','সময়, দিন ও দিনের বিভিন্ন ভাগ নিয়ে বলুন।','দেশ ও ভাষা','কেউ কোথা থেকে এসেছেন এবং কোন ভাষায় কথা বলেন তা জিজ্ঞেস করুন।','নির্দিষ্ট জায়গার জন্য at, যেমন at the bus stop; এলাকার জন্য in, যেমন in the city ব্যবহার করুন।','বাস ও মেট্রোর জন্য on, কিন্তু ট্যাক্সি ও গাড়ির জন্য in ব্যবহার করুন।','ঘড়ির সময়ের জন্য at (at 7:00), দিনের ভাগের জন্য in (in the evening), আর দিনের জন্য on (on Monday) ব্যবহার করুন।','every, next, last বা this-এর আগে at, in বা on বসাবেন না: every weekday, next Monday।','be দিয়ে প্রশ্নে am, is বা are কর্তার আগে বসে: Where is Emma from?','Present Simple-এর অন্য ক্রিয়ার প্রশ্নে do বা does + কর্তা + মূল ক্রিয়া ব্যবহার করুন: What language does she speak?','নমুনা · A1-এর ১২টি পাঠ · বাকি কোর্স তৈরি হচ্ছে।'],
 ur:['شہر میں آمد و رفت','جگہوں اور سواریوں کے لیے at، in اور on استعمال کریں۔','میرا روزانہ کا معمول','وقت، دنوں اور دن کے حصوں کے بارے میں بات کریں۔','ممالک اور زبانیں','پوچھیں کہ کوئی کہاں سے ہے اور کون سی زبانیں بولتا ہے۔','کسی خاص مقام کے لیے at، جیسے at the bus stop، اور علاقے کے لیے in، جیسے in the city استعمال کریں۔','بس اور میٹرو کے لیے on، لیکن ٹیکسی یا کار کے لیے in استعمال کریں۔','گھڑی کے وقت کے لیے at (at 7:00)، دن کے حصوں کے لیے in (in the evening)، اور دنوں کے لیے on (on Monday) استعمال کریں۔','every، next، last یا this سے پہلے at، in یا on نہ لگائیں: every weekday، next Monday۔','be کے سوال میں am، is یا are کو فاعل سے پہلے رکھیں: Where is Emma from?','Present Simple کے دوسرے افعال کے لیے do یا does + فاعل + فعل کی بنیادی شکل استعمال کریں: What language does she speak?','ابتدائی نمونہ · A1 کے 12 اسباق · باقی کورس تیار ہو رہا ہے۔'],
 ar:['التنقل في المدينة','استخدم at وin وon للتحدث عن الأماكن ووسائل النقل.','روتيني اليومي','تحدث عن الساعة والأيام وأوقات اليوم.','البلدان واللغات','اسأل عن بلد الشخص واللغات التي يتحدث بها.','استخدم at لمكان محدد، مثل at the bus stop، وin لمنطقة، مثل in the city.','استخدم on للحافلة والمترو، وin لسيارة الأجرة أو السيارة.','استخدم at للساعة (at 7:00)، وin لأوقات اليوم (in the evening)، وon للأيام (on Monday).','لا تضف at أو in أو on قبل every أو next أو last أو this: every weekday، next Monday.','في السؤال مع be، ضع am أو is أو are قبل الفاعل: Where is Emma from?','مع الأفعال الأخرى في Present Simple، استخدم do أو does + الفاعل + الفعل في صورته الأساسية: What language does she speak?','نسخة تجريبية · 12 درسًا A1 · بقية الدورة قيد الإعداد.'],
 id:['Keliling kota','Gunakan at, in, dan on untuk tempat dan transportasi.','Rutinitas harian saya','Bicarakan jam, hari, dan waktu dalam sehari.','Negara dan bahasa','Tanyakan asal seseorang dan bahasa yang mereka gunakan.','Gunakan at untuk titik tertentu, seperti at the bus stop, dan in untuk wilayah, seperti in the city.','Gunakan on untuk bus dan metro, tetapi in untuk taksi atau mobil.','Gunakan at untuk jam (at 7:00), in untuk bagian hari (in the evening), dan on untuk hari (on Monday).','Jangan tambahkan at, in, atau on sebelum every, next, last, atau this: every weekday, next Monday.','Dalam pertanyaan dengan be, letakkan am, is, atau are sebelum subjek: Where is Emma from?','Dengan kata kerja lain dalam Present Simple, gunakan do atau does + subjek + bentuk dasar kata kerja: What language does she speak?','Prototipe · 12 pelajaran A1 · sisanya sedang dibuat.'],
 tr:['Şehirde ulaşım','Yerleri ve ulaşımı anlatırken at, in ve on kullan.','Günlük programım','Saatler, günler ve günün bölümleri hakkında konuş.','Ülkeler ve diller','Birinin nereli olduğunu ve hangi dilleri konuştuğunu sor.','Belirli bir nokta için at (at the bus stop), bir alan için in (in the city) kullan.','Otobüs ve metro için on, taksi ve araba için in kullan.','Saatler için at (at 7:00), günün bölümleri için in (in the evening), günler için on (on Monday) kullan.','every, next, last veya this önüne at, in ya da on ekleme: every weekday, next Monday.','be ile soruda am, is veya are öznenin önüne gelir: Where is Emma from?','Present Simple içindeki diğer fiillerle do veya does + özne + fiilin yalın hâlini kullan: What language does she speak?','Prototip · 12 A1 dersi · kursun kalanı hazırlanıyor.'],
 vi:['Đi lại trong thành phố','Dùng at, in và on để nói về địa điểm và phương tiện.','Lịch sinh hoạt hằng ngày','Nói về giờ, ngày và các buổi trong ngày.','Quốc gia và ngôn ngữ','Hỏi một người đến từ đâu và nói những ngôn ngữ nào.','Dùng at cho một điểm cụ thể như at the bus stop, và in cho một khu vực như in the city.','Dùng on cho xe buýt và tàu điện, nhưng in cho taxi hoặc ô tô.','Dùng at với giờ (at 7:00), in với buổi trong ngày (in the evening), và on với ngày (on Monday).','Không thêm at, in hoặc on trước every, next, last hoặc this: every weekday, next Monday.','Với be, đặt am, is hoặc are trước chủ ngữ: Where is Emma from?','Với động từ khác ở Present Simple, dùng do hoặc does + chủ ngữ + động từ nguyên mẫu: What language does she speak?','Bản thử · 12 bài A1 · phần còn lại đang được xây dựng.'],
 kk:['Қаладағы көлік','Орындар мен көлік туралы айтқанда at, in және on қолданыңыз.','Менің күн тәртібім','Сағат, күндер және тәулік мезгілдері туралы айтыңыз.','Елдер мен тілдер','Адамның қайдан екенін және қандай тілде сөйлейтінін сұраңыз.','Нақты нүкте үшін at (at the bus stop), аумақ үшін in (in the city) қолданыңыз.','Автобус пен метрода on, такси мен көлікте in қолданыңыз.','Сағатпен at (at 7:00), тәулік мезгілімен in (in the evening), күнмен on (on Monday) қолданыңыз.','every, next, last немесе this сөздерінің алдына at, in не on қоймаңыз: every weekday, next Monday.','be етістігімен сұрақта am, is немесе are бастауыштың алдында тұрады: Where is Emma from?','Present Simple шағындағы басқа етістіктермен do немесе does + бастауыш + етістіктің негізгі түрін қолданыңыз: What language does she speak?','Прототип · A1 деңгейінің 12 сабағы · қалған курс әзірленуде.'],
 uz:['Shahar bo‘ylab','Joylar va transport haqida gapirganda at, in va on dan foydalaning.','Mening kundalik tartibim','Soatlar, kunlar va kunning qismlari haqida gapiring.','Mamlakatlar va tillar','Kimning qayerdan ekanini va qaysi tillarda gapirishini so‘rang.','Aniq nuqta uchun at (at the bus stop), hudud uchun in (in the city) ishlating.','Avtobus va metro uchun on, taksi yoki mashina uchun in ishlating.','Soat uchun at (at 7:00), kunning qismi uchun in (in the evening), kun uchun on (on Monday) ishlating.','every, next, last yoki this oldidan at, in yoki on qo‘ymang: every weekday, next Monday.','be bilan savolda am, is yoki are egadan oldin keladi: Where is Emma from?','Present Simple dagi boshqa fe’llar bilan do yoki does + ega + fe’lning asosiy shaklini ishlating: What language does she speak?','Prototip · A1 uchun 12 dars · qolgan kurs tayyorlanmoqda.']
};
const labels={
 en:['Use the English prompt below to practise this topic with AI Assistant.','Show transcript','Replay lesson audio'],
 ru:['Используйте английскую подсказку ниже, чтобы потренировать эту тему с AI Assistant.','Открыть транскрипцию','Повторно прослушать аудио урока'],
 es:['Usa la indicación en inglés de abajo para practicar este tema con AI Assistant.','Mostrar transcripción','Volver a escuchar el audio'],
 pt:['Use a sugestão em inglês abaixo para praticar este tema com o AI Assistant.','Mostrar transcrição','Ouvir o áudio novamente'],
 de:['Nutze die englische Aufgabe unten, um dieses Thema mit AI Assistant zu üben.','Transkript anzeigen','Lektionsaudio erneut abspielen'],
 fr:['Utilisez la consigne en anglais ci-dessous pour pratiquer ce sujet avec AI Assistant.','Afficher la transcription','Réécouter l’audio de la leçon'],
 it:['Usa la traccia in inglese qui sotto per esercitarti su questo tema con AI Assistant.','Mostra la trascrizione','Riascolta l’audio della lezione'],
 hy:['Ստորև բերված անգլերեն հուշումով այս թեման վարժեք AI Assistant-ի հետ։','Ցույց տալ տեքստը','Կրկին լսել դասի աուդիոն'],
 'zh-Hans':['使用下方的英语提示，与 AI Assistant 练习本课话题。','显示音频文本','重听本课音频'],
 ja:['下の英語の指示を使い、AI Assistant とこのテーマを練習しましょう。','文字起こしを表示','レッスン音声をもう一度聞く'],
 ko:['아래 영어 안내를 따라 AI Assistant와 이 주제를 연습하세요.','대본 보기','수업 오디오 다시 듣기'],
 hi:['नीचे दिए अंग्रेज़ी संकेत से AI Assistant के साथ इस विषय पर बोलने का अभ्यास करें।','प्रतिलेख दिखाएँ','पाठ का ऑडियो फिर सुनें'],
 bn:['নিচের ইংরেজি নির্দেশনা দিয়ে AI Assistant-এর সঙ্গে এই বিষয়ে কথা বলার অনুশীলন করুন।','লিখিত পাঠ দেখুন','পাঠের অডিও আবার শুনুন'],
 ur:['نیچے دی گئی انگریزی ہدایت سے AI Assistant کے ساتھ اس موضوع پر بولنے کی مشق کریں۔','تحریری متن دکھائیں','سبق کی آڈیو دوبارہ سنیں'],
 ar:['استخدم التعليمات الإنجليزية أدناه للتدرّب على هذا الموضوع مع AI Assistant.','عرض النص المكتوب','أعِد تشغيل صوت الدرس'],
 id:['Gunakan petunjuk bahasa Inggris di bawah untuk berlatih topik ini bersama AI Assistant.','Tampilkan transkrip','Putar ulang audio pelajaran'],
 tr:['Aşağıdaki İngilizce yönergeyle bu konuyu AI Assistant ile konuşarak çalış.','Metni göster','Ders sesini tekrar dinle'],
 vi:['Dùng gợi ý tiếng Anh bên dưới để luyện nói chủ đề này với AI Assistant.','Hiện bản chép lời','Nghe lại âm thanh bài học'],
 kk:['Төмендегі ағылшын нұсқаулығымен осы тақырыпты AI Assistant арқылы сөйлеп жаттықтырыңыз.','Мәтінді көрсету','Сабақ аудиосын қайта тыңдау'],
 uz:['Quyidagi inglizcha ko‘rsatma bilan bu mavzuni AI Assistant orqali gapirib mashq qiling.','Matnni ko‘rsatish','Dars audiosini qayta tinglash']
};
for(const [code,strings] of Object.entries(words)){
 if(strings.length!==keys.length||labels[code]?.length!==3||!I.ui[code])throw Error('Missing A1 course translation: '+code);
 Object.assign(I.ui[code],Object.fromEntries(keys.map((key,index)=>[key,strings[index]])),Object.fromEntries(['speakingText','transcriptLabel','replayAudio'].map((key,index)=>[key,labels[code][index]])));
}
})(typeof globalThis==='object'?globalThis:this);
