(function(root){
'use strict';
const I=root.EvoCourseI18n;
if(!I||!I.ui)throw Error('EvoCourseI18n must load before i18n-extra.js');
const additions={
en:{module:'A1 Foundations',l4:'What are we doing now?',g4:'Describe actions happening right now.',l5:'Weekend plans',g5:'Talk about plans you have already decided to do.',l6:'Free time and hobbies',g6:'Talk about activities you enjoy.',pilot:'Prototype · 6 A1 lessons · the rest of the course is in development.',presentContinuous:'Form the Present Continuous with am/is/are + verb-ing. Match am, is or are to the subject.',continuousNow:'Use the Present Continuous for actions happening now or temporary situations. Use the Present Simple for habits.',goingTo:'Form be going to with am/is/are + going to + base verb.',goingToPlans:'Use be going to for plans decided before speaking and predictions based on what you can see.',likeIng:'This lesson practises like + verb-ing. Like can also be followed by to + verb.',enjoyIng:'After enjoy and don’t mind, use a verb ending in -ing.'},
es:{module:'Fundamentos de A1',l4:'¿Qué estamos haciendo ahora?',g4:'Describe acciones que están ocurriendo ahora.',l5:'Planes para el fin de semana',g5:'Habla de planes que ya has decidido hacer.',l6:'Tiempo libre y aficiones',g6:'Habla de las actividades que disfrutas.',pilot:'Prototipo · 6 lecciones de A1 · el resto del curso está en desarrollo.',presentContinuous:'Forma el presente continuo con am/is/are + verbo en -ing. Elige am, is o are según el sujeto.',continuousNow:'Usa el presente continuo para acciones que ocurren ahora o situaciones temporales. Usa el presente simple para hábitos.',goingTo:'Forma be going to con am/is/are + going to + verbo base.',goingToPlans:'Usa be going to para planes decididos antes de hablar y predicciones basadas en lo que ves.',likeIng:'En esta lección practicamos like + verbo en -ing. Like también puede ir seguido de to + verbo.',enjoyIng:'Después de enjoy y don’t mind, usa un verbo terminado en -ing.'},
pt:{module:'Fundamentos do A1',l4:'O que estamos fazendo agora?',g4:'Descreva ações que estão acontecendo agora.',l5:'Planos para o fim de semana',g5:'Fale sobre planos que você já decidiu realizar.',l6:'Tempo livre e hobbies',g6:'Fale sobre atividades de que você gosta.',pilot:'Protótipo · 6 lições de A1 · o restante do curso está em desenvolvimento.',presentContinuous:'Forme o presente contínuo com am/is/are + verbo em -ing. Escolha am, is ou are de acordo com o sujeito.',continuousNow:'Use o presente contínuo para ações acontecendo agora ou situações temporárias. Use o presente simples para hábitos.',goingTo:'Forme be going to com am/is/are + going to + verbo base.',goingToPlans:'Use be going to para planos decididos antes de falar e previsões baseadas no que você vê.',likeIng:'Nesta lição, praticamos like + verbo em -ing. Like também pode ser seguido por to + verbo.',enjoyIng:'Depois de enjoy e don’t mind, use um verbo terminado em -ing.'},
de:{module:'A1-Grundlagen',l4:'Was machen wir gerade?',g4:'Beschreibe Handlungen, die gerade stattfinden.',l5:'Wochenendpläne',g5:'Sprich über Pläne, die du bereits beschlossen hast.',l6:'Freizeit und Hobbys',g6:'Sprich über Aktivitäten, die dir Spaß machen.',pilot:'Prototyp · 6 A1-Lektionen · der restliche Kurs wird entwickelt.',presentContinuous:'Bilde das Present Continuous mit am/is/are + Verb-ing. Wähle am, is oder are passend zum Subjekt.',continuousNow:'Verwende das Present Continuous für Handlungen, die gerade stattfinden, oder für vorübergehende Situationen. Für Gewohnheiten verwendest du das Present Simple.',goingTo:'Bilde be going to mit am/is/are + going to + Grundform.',goingToPlans:'Verwende be going to für vorher gefasste Pläne und Vorhersagen aufgrund sichtbarer Hinweise.',likeIng:'In dieser Lektion üben wir like + Verb-ing. Nach like kann auch to + Verb stehen.',enjoyIng:'Nach enjoy und don’t mind folgt ein Verb mit der Endung -ing.'},
fr:{module:'Bases de l’A1',l4:'Que faisons-nous en ce moment ?',g4:'Décris des actions qui se passent maintenant.',l5:'Projets pour le week-end',g5:'Parle de projets que tu as déjà décidé de réaliser.',l6:'Temps libre et loisirs',g6:'Parle des activités que tu aimes faire.',pilot:'Prototype · 6 leçons A1 · le reste du cours est en préparation.',presentContinuous:'Forme le présent continu avec am/is/are + verbe en -ing. Choisis am, is ou are selon le sujet.',continuousNow:'Utilise le présent continu pour les actions en cours ou les situations temporaires. Utilise le présent simple pour les habitudes.',goingTo:'Forme be going to avec am/is/are + going to + verbe à la base.',goingToPlans:'Utilise be going to pour les projets déjà décidés et les prédictions fondées sur des indices visibles.',likeIng:'Cette leçon pratique like + verbe en -ing. Like peut aussi être suivi de to + verbe.',enjoyIng:'Après enjoy et don’t mind, utilise un verbe terminé en -ing.'},
it:{module:'Fondamenti A1',l4:'Cosa stiamo facendo adesso?',g4:'Descrivi le azioni che stanno accadendo ora.',l5:'Programmi per il fine settimana',g5:'Parla dei programmi che hai già deciso di fare.',l6:'Tempo libero e hobby',g6:'Parla delle attività che ti piace fare.',pilot:'Prototipo · 6 lezioni A1 · il resto del corso è in preparazione.',presentContinuous:'Forma il present continuous con am/is/are + verbo in -ing. Scegli am, is o are in base al soggetto.',continuousNow:'Usa il present continuous per azioni in corso o situazioni temporanee. Usa il present simple per le abitudini.',goingTo:'Forma be going to con am/is/are + going to + verbo base.',goingToPlans:'Usa be going to per programmi già decisi e previsioni basate su ciò che vedi.',likeIng:'In questa lezione esercitiamo like + verbo in -ing. Like può essere seguito anche da to + verbo.',enjoyIng:'Dopo enjoy e don’t mind, usa un verbo che termina in -ing.'},
ru:{module:'Основы A1',l4:'Что мы делаем сейчас?',g4:'Опишите действия, которые происходят сейчас.',l5:'Планы на выходные',g5:'Расскажите о планах, которые уже решили осуществить.',l6:'Свободное время и увлечения',g6:'Расскажите о занятиях, которые вам нравятся.',pilot:'Прототип · 6 уроков A1 · остальная часть курса в разработке.',presentContinuous:'Present Continuous: am/is/are + глагол с окончанием -ing. Выбирайте am, is или are по подлежащему.',continuousNow:'Present Continuous описывает действия сейчас и временные ситуации. Present Simple — привычки.',goingTo:'Be going to: am/is/are + going to + начальная форма глагола.',goingToPlans:'Be going to используйте для заранее принятых планов и прогнозов на основе видимых признаков.',likeIng:'В этом уроке тренируем like + глагол с -ing. После like также возможно to + глагол.',enjoyIng:'После enjoy и don’t mind используйте глагол с окончанием -ing.'},
hy:{module:'A1-ի հիմունքներ',l4:'Ի՞նչ ենք անում հիմա։',g4:'Նկարագրեք այն գործողությունները, որոնք կատարվում են հիմա։',l5:'Հանգստյան օրերի ծրագրեր',g5:'Խոսեք ծրագրերի մասին, որոնք արդեն որոշել եք իրականացնել։',l6:'Ազատ ժամանակ և նախասիրություններ',g6:'Խոսեք այն զբաղմունքների մասին, որոնք ձեզ դուր են գալիս։',pilot:'Նախատիպ · A1-ի 6 դաս · դասընթացի մնացած մասը մշակվում է։',presentContinuous:'Present Continuous-ը կազմվում է am/is/are + բայի -ing ձևով։ Ընտրեք am, is կամ are՝ ըստ ենթակայի։',continuousNow:'Present Continuous-ն օգտագործվում է այս պահին կատարվող գործողությունների և ժամանակավոր իրավիճակների համար։ Սովորությունների համար օգտագործեք Present Simple։',goingTo:'Be going to-ն կազմվում է am/is/are + going to + բայի հիմնական ձևով։',goingToPlans:'Be going to-ն օգտագործեք նախապես որոշված ծրագրերի և տեսանելի փաստերի վրա հիմնված կանխատեսումների համար։',likeIng:'Այս դասում վարժվում ենք like + -ing ձևով։ Like-ից հետո հնարավոր է նաև to + բայ։',enjoyIng:'Enjoy և don’t mind բայերից հետո օգտագործեք -ing-ով ավարտվող բայ։'},
'zh-Hans':{module:'A1基础课程',l4:'我们现在在做什么？',g4:'描述正在发生的动作。',l5:'周末计划',g5:'谈谈你已经决定要做的计划。',l6:'空闲时间与爱好',g6:'谈谈你喜欢做的活动。',pilot:'试用版 · 6节A1课程 · 其余课程正在开发中。',presentContinuous:'现在进行时的结构是 am/is/are + 动词-ing。根据主语选择 am、is 或 are。',continuousNow:'现在进行时用于正在发生的动作或暂时的情况。习惯用一般现在时。',goingTo:'be going to 的结构是 am/is/are + going to + 动词原形。',goingToPlans:'be going to 用于说话前已决定的计划，以及根据眼前迹象作出的预测。',likeIng:'本课练习 like + 动词-ing。Like 后面也可以接 to + 动词。',enjoyIng:'Enjoy 和 don’t mind 后面接动词-ing。'},
ja:{module:'A1の基礎',l4:'今、何をしていますか？',g4:'今起きている動作を説明しましょう。',l5:'週末の予定',g5:'すでに決めている予定について話しましょう。',l6:'自由時間と趣味',g6:'好きな活動について話しましょう。',pilot:'試作版 · A1の6レッスン · コースの続きは開発中です。',presentContinuous:'現在進行形は am/is/are + 動詞-ing で作ります。主語に合わせて am、is、are を選びます。',continuousNow:'現在進行形は今行っている動作や一時的な状況に使います。習慣には現在形を使います。',goingTo:'be going to は am/is/are + going to + 動詞の原形で作ります。',goingToPlans:'be going to は事前に決めた予定や、目に見える状況に基づく予測に使います。',likeIng:'このレッスンでは like + 動詞-ing を練習します。Like の後に to + 動詞を使うこともできます。',enjoyIng:'enjoy と don’t mind の後には動詞-ing を使います。'},
ko:{module:'A1 기초',l4:'지금 무엇을 하고 있나요?',g4:'지금 일어나고 있는 동작을 설명해 보세요.',l5:'주말 계획',g5:'이미 하기로 정한 계획을 이야기해 보세요.',l6:'여가 시간과 취미',g6:'좋아하는 활동을 이야기해 보세요.',pilot:'시범 과정 · A1 레슨 6개 · 나머지 과정은 개발 중입니다.',presentContinuous:'현재진행형은 am/is/are + 동사-ing로 만듭니다. 주어에 맞게 am, is, are를 고르세요.',continuousNow:'현재진행형은 지금 진행 중인 동작이나 일시적인 상황에 씁니다. 습관에는 현재형을 씁니다.',goingTo:'be going to는 am/is/are + going to + 동사 원형으로 만듭니다.',goingToPlans:'be going to는 말하기 전에 정한 계획과 눈에 보이는 근거에 따른 예측에 씁니다.',likeIng:'이 레슨에서는 like + 동사-ing를 연습합니다. Like 뒤에는 to + 동사도 올 수 있습니다.',enjoyIng:'enjoy와 don’t mind 뒤에는 동사-ing를 씁니다.'},
hi:{module:'A1 की बुनियाद',l4:'हम अभी क्या कर रहे हैं?',g4:'अभी हो रही गतिविधियों का वर्णन करें।',l5:'सप्ताहांत की योजनाएँ',g5:'उन योजनाओं के बारे में बताएँ जिन्हें आपने पहले ही तय किया है।',l6:'खाली समय और शौक',g6:'उन गतिविधियों के बारे में बताएँ जिन्हें करना आपको पसंद है।',pilot:'प्रोटोटाइप · A1 के 6 पाठ · बाकी पाठ्यक्रम विकसित किया जा रहा है।',presentContinuous:'Present Continuous बनाने के लिए am/is/are + क्रिया-ing का प्रयोग करें। कर्ता के अनुसार am, is या are चुनें।',continuousNow:'अभी चल रही गतिविधियों या अस्थायी स्थितियों के लिए Present Continuous और आदतों के लिए Present Simple का प्रयोग करें।',goingTo:'Be going to का रूप am/is/are + going to + क्रिया का मूल रूप है।',goingToPlans:'पहले से तय योजनाओं और दिखाई देने वाले संकेतों पर आधारित अनुमान के लिए be going to का प्रयोग करें।',likeIng:'इस पाठ में like + क्रिया-ing का अभ्यास है। Like के बाद to + क्रिया भी आ सकता है।',enjoyIng:'Enjoy और don’t mind के बाद क्रिया-ing का प्रयोग करें।'},
bn:{module:'A1-এর ভিত্তি',l4:'আমরা এখন কী করছি?',g4:'এখন ঘটছে এমন কাজের বর্ণনা দিন।',l5:'সপ্তাহান্তের পরিকল্পনা',g5:'আগেই ঠিক করা পরিকল্পনা সম্পর্কে বলুন।',l6:'অবসর ও শখ',g6:'যে কাজগুলো করতে ভালো লাগে সেগুলো বলুন।',pilot:'প্রোটোটাইপ · ৬টি A1 পাঠ · বাকি কোর্স তৈরি হচ্ছে।',presentContinuous:'Present Continuous গঠন করতে am/is/are + verb-ing ব্যবহার করুন। কর্তার সঙ্গে মিলিয়ে am, is বা are বেছে নিন।',continuousNow:'এখন চলমান কাজ বা সাময়িক অবস্থার জন্য Present Continuous এবং অভ্যাসের জন্য Present Simple ব্যবহার করুন।',goingTo:'Be going to গঠন: am/is/are + going to + verb-এর মূল রূপ।',goingToPlans:'আগে থেকে ঠিক করা পরিকল্পনা এবং দৃশ্যমান লক্ষণের ভিত্তিতে অনুমানের জন্য be going to ব্যবহার করুন।',likeIng:'এই পাঠে like + verb-ing অনুশীলন করা হয়েছে। Like-এর পরে to + verb-ও হতে পারে।',enjoyIng:'Enjoy এবং don’t mind-এর পরে verb-ing ব্যবহার করুন।'},
ur:{module:'A1 کی بنیاد',l4:'ہم ابھی کیا کر رہے ہیں؟',g4:'اس وقت جاری کاموں کی وضاحت کریں۔',l5:'ہفتے کے آخر کے منصوبے',g5:'ان منصوبوں کے بارے میں بتائیں جن کا فیصلہ آپ پہلے ہی کر چکے ہیں۔',l6:'فارغ وقت اور مشاغل',g6:'ان سرگرمیوں کے بارے میں بتائیں جو آپ کو پسند ہیں۔',pilot:'نمونہ کورس · A1 کے 6 اسباق · باقی کورس تیار ہو رہا ہے۔',presentContinuous:'Present Continuous بنانے کے لیے am/is/are + فعل-ing استعمال کریں۔ فاعل کے مطابق am، is یا are چنیں۔',continuousNow:'ابھی جاری کاموں یا عارضی حالات کے لیے Present Continuous اور عادتوں کے لیے Present Simple استعمال کریں۔',goingTo:'Be going to کی ساخت am/is/are + going to + فعل کی بنیادی شکل ہے۔',goingToPlans:'پہلے سے طے شدہ منصوبوں اور نظر آنے والے شواہد پر مبنی پیش گوئی کے لیے be going to استعمال کریں۔',likeIng:'اس سبق میں like + فعل-ing کی مشق ہے۔ Like کے بعد to + فعل بھی آ سکتا ہے۔',enjoyIng:'Enjoy اور don’t mind کے بعد فعل-ing استعمال کریں۔'},
ar:{module:'أساسيات A1',l4:'ماذا نفعل الآن؟',g4:'صف الأفعال التي تحدث الآن.',l5:'خطط عطلة نهاية الأسبوع',g5:'تحدث عن خطط قررت تنفيذها مسبقًا.',l6:'وقت الفراغ والهوايات',g6:'تحدث عن الأنشطة التي تستمتع بها.',pilot:'نسخة تجريبية · 6 دروس A1 · بقية الدورة قيد الإعداد.',presentContinuous:'كوّن المضارع المستمر باستخدام am/is/are + فعل ينتهي بـ -ing. اختر am أو is أو are بحسب الفاعل.',continuousNow:'استخدم المضارع المستمر للأفعال الجارية الآن أو الحالات المؤقتة، والمضارع البسيط للعادات.',goingTo:'تُكوَّن be going to باستخدام am/is/are + going to + الفعل بصيغته الأساسية.',goingToPlans:'استخدم be going to للخطط التي قررتها مسبقًا والتوقعات المبنية على دلائل واضحة.',likeIng:'نتدرّب في هذا الدرس على like + فعل ينتهي بـ -ing. ويمكن أيضًا أن يأتي بعد like مصدر مع to.',enjoyIng:'استخدم فعلًا ينتهي بـ -ing بعد enjoy و don’t mind.'},
id:{module:'Dasar-dasar A1',l4:'Apa yang sedang kita lakukan?',g4:'Jelaskan kegiatan yang sedang berlangsung sekarang.',l5:'Rencana akhir pekan',g5:'Ceritakan rencana yang sudah kamu putuskan.',l6:'Waktu luang dan hobi',g6:'Ceritakan kegiatan yang kamu sukai.',pilot:'Prototipe · 6 pelajaran A1 · bagian kursus lainnya sedang dikembangkan.',presentContinuous:'Bentuk present continuous dengan am/is/are + kata kerja-ing. Pilih am, is, atau are sesuai subjek.',continuousNow:'Gunakan present continuous untuk kegiatan yang sedang berlangsung atau keadaan sementara. Gunakan present simple untuk kebiasaan.',goingTo:'Bentuk be going to adalah am/is/are + going to + kata kerja dasar.',goingToPlans:'Gunakan be going to untuk rencana yang sudah diputuskan dan prediksi berdasarkan tanda yang terlihat.',likeIng:'Pelajaran ini melatih like + kata kerja-ing. Like juga dapat diikuti to + kata kerja.',enjoyIng:'Setelah enjoy dan don’t mind, gunakan kata kerja berakhiran -ing.'},
tr:{module:'A1 temelleri',l4:'Şu anda ne yapıyoruz?',g4:'Şu anda gerçekleşen eylemleri anlatın.',l5:'Hafta sonu planları',g5:'Yapmaya önceden karar verdiğiniz planlardan bahsedin.',l6:'Boş zaman ve hobiler',g6:'Yapmaktan hoşlandığınız etkinlikleri anlatın.',pilot:'Prototip · 6 A1 dersi · kursun geri kalanı hazırlanıyor.',presentContinuous:'Present Continuous, am/is/are + fiil-ing ile kurulur. Özneye göre am, is veya are seçin.',continuousNow:'Şu anda gerçekleşen eylemler veya geçici durumlar için Present Continuous, alışkanlıklar için Present Simple kullanın.',goingTo:'Be going to, am/is/are + going to + fiilin yalın hâliyle kurulur.',goingToPlans:'Önceden kararlaştırılmış planlar ve görünen kanıtlara dayalı tahminler için be going to kullanın.',likeIng:'Bu derste like + fiil-ing yapısını çalışıyoruz. Like sonrasında to + fiil de kullanılabilir.',enjoyIng:'Enjoy ve don’t mind sonrasında -ing ile biten bir fiil kullanın.'},
vi:{module:'Nền tảng A1',l4:'Chúng ta đang làm gì?',g4:'Mô tả những hành động đang diễn ra.',l5:'Kế hoạch cuối tuần',g5:'Kể về những việc bạn đã quyết định sẽ làm.',l6:'Thời gian rảnh và sở thích',g6:'Kể về những hoạt động bạn thích.',pilot:'Bản thử nghiệm · 6 bài học A1 · các phần còn lại đang được phát triển.',presentContinuous:'Dùng am/is/are + động từ-ing để tạo thì hiện tại tiếp diễn. Chọn am, is hoặc are theo chủ ngữ.',continuousNow:'Dùng hiện tại tiếp diễn cho hành động đang xảy ra hoặc tình huống tạm thời. Dùng hiện tại đơn cho thói quen.',goingTo:'Cấu trúc be going to là am/is/are + going to + động từ nguyên mẫu.',goingToPlans:'Dùng be going to cho kế hoạch đã quyết định trước và dự đoán dựa trên dấu hiệu có thể thấy.',likeIng:'Bài này luyện cấu trúc like + động từ-ing. Sau like cũng có thể dùng to + động từ.',enjoyIng:'Sau enjoy và don’t mind, dùng động từ kết thúc bằng -ing.'},
kk:{module:'A1 негіздері',l4:'Қазір не істеп жатырмыз?',g4:'Дәл қазір болып жатқан әрекеттерді сипаттаңыз.',l5:'Демалыс күнінің жоспарлары',g5:'Алдын ала шешіп қойған жоспарларыңыз туралы айтыңыз.',l6:'Бос уақыт және хобби',g6:'Өзіңізге ұнайтын істер туралы айтыңыз.',pilot:'Прототип · A1 деңгейіндегі 6 сабақ · курстың қалған бөлігі әзірленуде.',presentContinuous:'Present Continuous формасы: am/is/are + етістік-ing. Бастауышқа сай am, is немесе are таңдаңыз.',continuousNow:'Қазір болып жатқан әрекеттер мен уақытша жағдайларға Present Continuous, әдеттерге Present Simple қолданыңыз.',goingTo:'Be going to формасы: am/is/are + going to + етістіктің негізгі түрі.',goingToPlans:'Алдын ала шешілген жоспарлар мен көзге көрінетін белгілерге негізделген болжамдарға be going to қолданыңыз.',likeIng:'Бұл сабақта like + етістік-ing құрылымын жаттығамыз. Like сөзінен кейін to + етістік те келе алады.',enjoyIng:'Enjoy және don’t mind сөздерінен кейін -ing жалғауы бар етістікті қолданыңыз.'},
uz:{module:'A1 asoslari',l4:'Hozir nima qilyapmiz?',g4:'Hozir sodir bo‘layotgan harakatlarni tasvirlang.',l5:'Dam olish kunlari rejalari',g5:'Oldindan qaror qilgan rejalaringiz haqida gapiring.',l6:'Bo‘sh vaqt va sevimli mashg‘ulotlar',g6:'Sizga yoqadigan mashg‘ulotlar haqida gapiring.',pilot:'Prototip · A1 darajasidagi 6 ta dars · kursning qolgan qismi ishlab chiqilmoqda.',presentContinuous:'Present Continuous am/is/are + fe’l-ing bilan tuziladi. Ega bilan mos am, is yoki are ni tanlang.',continuousNow:'Hozir davom etayotgan harakatlar yoki vaqtinchalik holatlar uchun Present Continuous, odatlar uchun Present Simple ishlatiladi.',goingTo:'Be going to shakli: am/is/are + going to + fe’lning asosiy shakli.',goingToPlans:'Oldindan qaror qilingan rejalar va ko‘rinib turgan belgilarga asoslangan taxminlar uchun be going to ishlatiladi.',likeIng:'Bu darsda like + fe’l-ing shaklini mashq qilamiz. Like dan keyin to + fe’l ham kelishi mumkin.',enjoyIng:'Enjoy va don’t mind dan keyin -ing bilan tugaydigan fe’l ishlatiladi.'}
};
const speaking={en:'Open AI Assistant and practise speaking about this lesson’s topic.',es:'Abre AI Assistant y practica hablando sobre el tema de esta lección.',pt:'Abra o AI Assistant e pratique a conversação sobre o tema desta aula.',de:'Öffne den AI Assistant und übe das Sprechen über das Thema dieser Lektion.',fr:'Ouvre AI Assistant et entraîne-toi à parler du sujet de cette leçon.',it:'Apri AI Assistant e fai pratica parlando dell’argomento di questa lezione.',ru:'Откройте AI Assistant и потренируйтесь говорить на тему этого урока.',hy:'Բացեք AI Assistant-ը և վարժվեք այս դասի թեմայով խոսել։','zh-Hans':'打开 AI Assistant，练习谈论本课主题。',ja:'AI Assistantを開いて、このレッスンのテーマについて話す練習をしましょう。',ko:'AI Assistant를 열고 이 레슨의 주제로 말하기를 연습하세요.',hi:'AI Assistant खोलें और इस पाठ के विषय पर बोलने का अभ्यास करें。',bn:'AI Assistant খুলে এই পাঠের বিষয় নিয়ে কথা বলার অনুশীলন করুন।',ur:'AI Assistant کھولیں اور اس سبق کے موضوع پر بات کرنے کی مشق کریں۔',ar:'افتح AI Assistant وتدرّب على التحدث عن موضوع هذا الدرس.',id:'Buka AI Assistant dan berlatihlah berbicara tentang topik pelajaran ini.',tr:'AI Assistant’ı açın ve bu dersin konusu hakkında konuşma pratiği yapın.',vi:'Mở AI Assistant và luyện nói về chủ đề của bài học này.',kk:'AI Assistant-ті ашып, осы сабақтың тақырыбы туралы сөйлеуді жаттықтырыңыз.',uz:'AI Assistant-ni oching va ushbu dars mavzusida gapirishni mashq qiling.'};
const spelling={
 en:'Use am/is/are + verb-ing. Double the final t in sit → sitting; add -ing to wash → washing.',
 es:'Usa am/is/are + verbo en -ing. Duplica la t final en sit → sitting; añade -ing a wash → washing.',
 pt:'Use am/is/are + verbo em -ing. Duplique o t final em sit → sitting; acrescente -ing a wash → washing.',
 de:'Verwende am/is/are + Verb-ing. Verdopple das letzte t bei sit → sitting; hänge -ing an wash → washing.',
 fr:'Utilise am/is/are + verbe en -ing. Double le t final de sit → sitting ; ajoute -ing à wash → washing.',
 it:'Usa am/is/are + verbo in -ing. Raddoppia la t finale in sit → sitting; aggiungi -ing a wash → washing.',
 ru:'Используйте am/is/are + глагол с -ing. В sit → sitting удваивается t; к wash → washing добавляется -ing.',
 hy:'Օգտագործեք am/is/are + բայի -ing ձևը։ sit → sitting ձևում վերջին t-ն կրկնապատկվում է, իսկ wash → washing ձևում ավելացվում է -ing։',
 'zh-Hans':'使用 am/is/are + 动词-ing。sit → sitting 要双写末尾的 t；wash → washing 直接加 -ing。',
 ja:'am/is/are + 動詞-ing を使います。sit → sitting は最後の t を重ね、wash → washing は -ing を付けます。',
 ko:'am/is/are + 동사-ing를 사용합니다. sit → sitting은 마지막 t를 한 번 더 쓰고, wash → washing은 -ing를 붙입니다.',
 hi:'am/is/are + क्रिया-ing का प्रयोग करें। sit → sitting में अंतिम t दोहराएँ; wash → washing में -ing जोड़ें।',
 bn:'am/is/are + verb-ing ব্যবহার করুন। sit → sitting-এ শেষের t দ্বিগুণ হয়; wash → washing-এ -ing যোগ হয়।',
 ur:'am/is/are + فعل-ing استعمال کریں۔ sit → sitting میں آخری t دگنا ہوتا ہے؛ wash → washing میں -ing لگتا ہے۔',
 ar:'استخدم am/is/are + فعل ينتهي بـ -ing. في sit → sitting نضاعف حرف t الأخير، وفي wash → washing نضيف -ing.',
 id:'Gunakan am/is/are + kata kerja-ing. Gandakan t terakhir pada sit → sitting; tambahkan -ing pada wash → washing.',
 tr:'am/is/are + fiil-ing kullanın. sit → sitting için son t harfini iki kez yazın; wash → washing için -ing ekleyin.',
 vi:'Dùng am/is/are + động từ-ing. Gấp đôi chữ t cuối trong sit → sitting; thêm -ing vào wash → washing.',
 kk:'am/is/are + етістік-ing қолданыңыз. sit → sitting сөзінде соңғы t екі еселенеді; wash → washing сөзіне -ing жалғанады.',
 uz:'am/is/are + fe’l-ing ishlating. sit → sitting shaklida oxirgi t ikki marta yoziladi; wash → washing shaklida -ing qo‘shiladi.'
};
for(const [lang,values] of Object.entries(additions)){Object.assign(I.ui[lang],values);I.ui[lang].speakingText=speaking[lang];I.ui[lang].continuousSpelling=spelling[lang];}
})(typeof globalThis==='object'?globalThis:this);
