(function(root){
'use strict';
const I=root.EvoCourseI18n;
if(!I||!I.ui)throw Error('Load i18n.js before i18n-16-18.js');
const keys=['l16','g16','l17','g17','l18','g18','likeGeneral','wouldLikeOffer','frequencyPosition','howOften'];
const lines={
 en:['What are they wearing?','Describe clothes and actions happening now.','At the restaurant','Use like for general preferences and would like for offers and requests.','Shopping habits','Ask and answer how often someone shops.','Use like for a general preference: I like soup. Use Do you like…? to ask for an opinion.','Use I’d like… to ask for something now. Use Would you like…? to offer it.','Put always and sometimes before the main verb: I always compare prices.','How often…? asks about frequency. Answer with once a month, every day, or a similar phrase.'],
 ru:['Во что они одеты?','Опишите одежду и действия, происходящие сейчас.','В ресторане','Различайте like для общих предпочтений и would like для предложений и просьб.','Покупки','Спрашивайте и отвечайте, как часто человек ходит за покупками.','Like выражает общее предпочтение: I like soup. Do you like…? спрашивает мнение.','I’d like… — просьба о чём-то сейчас. Would you like…? — предложение.','Ставьте always и sometimes перед основным глаголом: I always compare prices.','How often…? спрашивает о частоте. Ответьте: once a month, every day и т. п.'],
 es:['¿Qué llevan puesto?','Describe ropa y acciones que ocurren ahora.','En el restaurante','Usa like para preferencias generales y would like para ofrecer o pedir algo.','Hábitos de compra','Pregunta y responde con qué frecuencia compra alguien.','Like expresa una preferencia general: I like soup. Do you like…? pregunta por una opinión.','I’d like… sirve para pedir algo ahora. Would you like…? sirve para ofrecerlo.','Coloca always y sometimes antes del verbo principal: I always compare prices.','How often…? pregunta por la frecuencia. Responde con once a month, every day, etc.'],
 pt:['O que estão vestindo?','Descreva roupas e ações que acontecem agora.','No restaurante','Use like para preferências gerais e would like para ofertas e pedidos.','Hábitos de compras','Pergunte e responda com que frequência alguém faz compras.','Like expressa uma preferência geral: I like soup. Do you like…? pergunta uma opinião.','I’d like… pede algo agora. Would you like…? oferece algo.','Coloque always e sometimes antes do verbo principal: I always compare prices.','How often…? pergunta a frequência. Responda com once a month, every day etc.'],
 de:['Was tragen sie?','Beschreibe Kleidung und Handlungen, die jetzt stattfinden.','Im Restaurant','Verwende like für allgemeine Vorlieben und would like für Angebote und Bitten.','Einkaufsgewohnheiten','Frage und antworte, wie oft jemand einkauft.','Like beschreibt eine allgemeine Vorliebe: I like soup. Do you like…? fragt nach einer Meinung.','I’d like… ist eine Bitte um etwas jetzt. Would you like…? ist ein Angebot.','Setze always und sometimes vor das Hauptverb: I always compare prices.','How often…? fragt nach der Häufigkeit. Antworte mit once a month, every day usw.'],
 fr:['Que portent-ils ?','Décris les vêtements et les actions en cours.','Au restaurant','Utilise like pour les goûts généraux et would like pour les offres et les demandes.','Habitudes d’achat','Demande et indique à quelle fréquence une personne fait des achats.','Like exprime un goût général : I like soup. Do you like…? demande un avis.','I’d like… sert à demander quelque chose maintenant. Would you like…? sert à l’offrir.','Place always et sometimes avant le verbe principal : I always compare prices.','How often…? demande la fréquence. Réponds avec once a month, every day, etc.'],
 it:['Che cosa indossano?','Descrivi abiti e azioni che avvengono ora.','Al ristorante','Usa like per i gusti generali e would like per offerte e richieste.','Abitudini di acquisto','Chiedi e spiega quanto spesso una persona fa acquisti.','Like indica una preferenza generale: I like soup. Do you like…? chiede un’opinione.','I’d like… serve a chiedere qualcosa ora. Would you like…? serve a offrirla.','Metti always e sometimes prima del verbo principale: I always compare prices.','How often…? chiede la frequenza. Rispondi con once a month, every day, ecc.'],
 hy:['Ի՞նչ են նրանք հագել','Նկարագրեք հագուստն ու հիմա կատարվող գործողությունները։','Ռեստորանում','Ընդհանուր նախընտրության համար օգտագործեք like, առաջարկի կամ խնդրանքի համար՝ would like։','Գնումների սովորություններ','Հարցրեք և պատասխանեք, թե մարդը որքան հաճախ է գնումներ անում։','Like-ը ցույց է տալիս ընդհանուր նախընտրություն՝ I like soup. Do you like…? հարցնում է կարծիք։','I’d like… ձևով հիմա ինչ-որ բան եք խնդրում։ Would you like…? ձևով առաջարկում եք։','always և sometimes բառերը դրեք հիմնական բայից առաջ՝ I always compare prices.','How often…? հարցնում է հաճախականությունը։ Պատասխանեք once a month, every day և նման ձևերով։'],
 'zh-Hans':['他们穿着什么？','描述现在穿着的衣服和正在发生的动作。','在餐厅','用 like 表示一般喜好，用 would like 提出邀请或礼貌请求。','购物习惯','询问和回答购物的频率。','like 表示一般喜好：I like soup. Do you like…? 用来询问看法。','I’d like… 表示现在想要某物；Would you like…? 用来提供某物。','always 和 sometimes 放在主要动词前：I always compare prices.','How often…? 询问频率。可用 once a month、every day 等回答。'],
 ja:['何を着ていますか？','今着ている服と起きている動作を説明します。','レストランで','一般的な好みには like、申し出や依頼には would like を使います。','買い物の習慣','どのくらいの頻度で買い物をするか尋ね、答えます。','like は一般的な好みを表します：I like soup. Do you like…? で意見を尋ねます。','I’d like… は今欲しいものを頼みます。Would you like…? は申し出です。','always と sometimes は主動詞の前に置きます：I always compare prices.','How often…? は頻度を尋ねます。once a month、every day などで答えます。'],
 ko:['무엇을 입고 있나요?','지금 입은 옷과 현재 일어나는 행동을 설명하세요.','식당에서','일반적인 취향에는 like, 제안과 요청에는 would like를 사용하세요.','쇼핑 습관','쇼핑을 얼마나 자주 하는지 묻고 답하세요.','like는 일반적인 취향을 나타냅니다: I like soup. Do you like…?는 의견을 묻습니다.','I’d like…는 지금 원하는 것을 요청합니다. Would you like…?는 제안입니다.','always와 sometimes는 본동사 앞에 놓습니다: I always compare prices.','How often…?은 빈도를 묻습니다. once a month, every day 등으로 답하세요.'],
 hi:['वे क्या पहने हुए हैं?','अभी पहने कपड़ों और हो रही क्रियाओं का वर्णन करें।','रेस्तराँ में','सामान्य पसंद के लिए like और प्रस्ताव या अनुरोध के लिए would like प्रयोग करें।','खरीदारी की आदतें','पूछें और बताएं कि कोई कितनी बार खरीदारी करता है।','like सामान्य पसंद बताता है: I like soup. Do you like…? राय पूछता है।','I’d like… से अभी कुछ माँगते हैं। Would you like…? से कुछ प्रस्तावित करते हैं।','always और sometimes को मुख्य क्रिया से पहले रखें: I always compare prices.','How often…? आवृत्ति पूछता है। once a month, every day आदि से उत्तर दें।'],
 bn:['তারা কী পরেছে?','এখনকার পোশাক ও চলমান কাজ বর্ণনা করুন।','রেস্তোরাঁয়','সাধারণ পছন্দে like, প্রস্তাব ও অনুরোধে would like ব্যবহার করুন।','কেনাকাটার অভ্যাস','কেউ কত ঘন ঘন কেনাকাটা করে তা জিজ্ঞেস করুন ও বলুন।','like সাধারণ পছন্দ বোঝায়: I like soup. Do you like…? মতামত জানতে চায়।','I’d like… দিয়ে এখন কিছু চাইতে হয়। Would you like…? দিয়ে প্রস্তাব দিতে হয়।','always ও sometimes মূল ক্রিয়ার আগে বসে: I always compare prices.','How often…? দিয়ে কত ঘন ঘন জানতে চাওয়া হয়। once a month, every day ইত্যাদি দিয়ে উত্তর দিন।'],
 ur:['وہ کیا پہنے ہوئے ہیں؟','اس وقت کے کپڑوں اور جاری کاموں کی وضاحت کریں۔','ریستوران میں','عمومی پسند کے لیے like اور پیشکش یا درخواست کے لیے would like استعمال کریں۔','خریداری کی عادتیں','پوچھیں اور بتائیں کہ کوئی کتنی بار خریداری کرتا ہے۔','like عمومی پسند بتاتا ہے: I like soup. Do you like…? رائے پوچھتا ہے۔','I’d like… سے ابھی کچھ مانگتے ہیں۔ Would you like…? سے پیشکش کرتے ہیں۔','always اور sometimes کو مرکزی فعل سے پہلے رکھیں: I always compare prices.','How often…? تعداد یا وقفہ پوچھتا ہے۔ once a month، every day وغیرہ سے جواب دیں۔'],
 ar:['ماذا يرتدون؟','صِف الملابس والأفعال التي تحدث الآن.','في المطعم','استخدم like للتفضيل العام وwould like للعرض أو الطلب المهذب.','عادات التسوق','اسأل وأجب عن عدد مرات التسوق.','تعبّر like عن تفضيل عام: I like soup. وتسأل Do you like…? عن الرأي.','تستخدم I’d like… لطلب شيء الآن، وWould you like…? لعرضه.','ضع always وsometimes قبل الفعل الرئيسي: I always compare prices.','تسأل How often…? عن التكرار. أجب بعبارات مثل once a month أو every day.'],
 id:['Apa yang mereka kenakan?','Jelaskan pakaian dan kegiatan yang sedang berlangsung.','Di restoran','Gunakan like untuk kesukaan umum dan would like untuk tawaran atau permintaan.','Kebiasaan berbelanja','Tanyakan dan jawab seberapa sering seseorang berbelanja.','Like menyatakan kesukaan umum: I like soup. Do you like…? menanyakan pendapat.','I’d like… meminta sesuatu sekarang. Would you like…? menawarkannya.','Letakkan always dan sometimes sebelum kata kerja utama: I always compare prices.','How often…? menanyakan frekuensi. Jawab dengan once a month, every day, dan sebagainya.'],
 tr:['Ne giyiyorlar?','Şu anda giyilen kıyafetleri ve gerçekleşen eylemleri anlatın.','Restoranda','Genel tercihler için like, teklif ve istekler için would like kullanın.','Alışveriş alışkanlıkları','Birinin ne sıklıkla alışveriş yaptığını sorun ve yanıtlayın.','Like genel tercihi anlatır: I like soup. Do you like…? fikir sorar.','I’d like… şu anda bir şey istemek içindir. Would you like…? teklif içindir.','always ve sometimes sözcüklerini ana fiilden önce koyun: I always compare prices.','How often…? sıklığı sorar. once a month, every day gibi ifadelerle yanıtlayın.'],
 vi:['Họ đang mặc gì?','Miêu tả quần áo và hành động đang diễn ra.','Ở nhà hàng','Dùng like cho sở thích chung và would like để mời hoặc yêu cầu.','Thói quen mua sắm','Hỏi và trả lời ai đó mua sắm bao lâu một lần.','Like diễn tả sở thích chung: I like soup. Do you like…? hỏi ý kiến.','I’d like… dùng để xin thứ gì ngay lúc này. Would you like…? dùng để mời.','Đặt always và sometimes trước động từ chính: I always compare prices.','How often…? hỏi tần suất. Trả lời bằng once a month, every day, v.v.'],
 kk:['Олар не киіп жүр?','Қазір киіп тұрған киім мен болып жатқан әрекеттерді сипаттаңыз.','Мейрамханада','Жалпы ұнатуды like, ұсыныс пен өтінішті would like арқылы білдіріңіз.','Сауда жасау әдеттері','Адамның қаншалықты жиі сауда жасайтынын сұрап, жауап беріңіз.','Like жалпы ұнатуды білдіреді: I like soup. Do you like…? пікірді сұрайды.','I’d like… қазір бір нәрсе сұрауға, Would you like…? ұсынуға қолданылады.','always пен sometimes негізгі етістіктің алдында тұрады: I always compare prices.','How often…? жиілікті сұрайды. once a month, every day сияқты тіркестермен жауап беріңіз.'],
 uz:['Ular nima kiygan?','Hozirgi kiyim va ayni paytdagi harakatlarni tasvirlang.','Restoranda','Umumiy yoqtirish uchun like, taklif va iltimos uchun would like ishlating.','Xarid qilish odatlari','Kimdir qanchalik tez-tez xarid qilishini so‘rang va javob bering.','Like umumiy yoqtirishni bildiradi: I like soup. Do you like…? fikrni so‘raydi.','I’d like… hozir biror narsa so‘rash, Would you like…? taklif qilish uchun.','always va sometimes asosiy fe’ldan oldin keladi: I always compare prices.','How often…? takrorlanish tezligini so‘raydi. once a month, every day kabi javob bering.']
};
for(const [code,values] of Object.entries(lines)){
 if(!I.ui[code]||values.length!==keys.length)throw Error('Missing lesson 16–18 translation: '+code);
 Object.assign(I.ui[code],Object.fromEntries(keys.map((key,index)=>[key,values[index]])));
 const old=I.ui[code].pilot;
 if(old)I.ui[code].pilot=old.replace(/15|۱۵|١٥|१५|১৫|１５/g,match=>({'15':'18','۱۵':'۱۸','١٥':'١٨','१५':'१८','১৫':'১৮','１５':'１８'}[match]));
}
})(typeof globalThis==='object'?globalThis:this);
