(function(root){
'use strict';
const I=root.EvoCourseI18n;
if(!I||!I.ui)throw Error('Load i18n.js before i18n-19-21.js');
const keys=['l19','g19','l20','g20','l21','g21','inviteTo','inviteReply'];
const lines={
en:['Sports and exercise','Practise -ing forms after enjoy and don’t mind.','Invitations','Invite someone and accept or decline politely.','A busy day tomorrow','Describe plans using be going to.','Use Would you like to + base verb to invite someone to do something. Use I’d like to + base verb for your own wish.','Accept with Yes, I’d love to. Decline with No, thank you and a short reason.'],
ru:['Спорт и упражнения','Тренируйте форму -ing после enjoy и don’t mind.','Приглашения','Приглашайте и вежливо соглашайтесь или отказывайтесь.','Завтра — насыщенный день','Описывайте планы с помощью be going to.','Would you like to + начальная форма глагола — приглашение к действию. I’d like to + глагол — собственное желание.','Согласитесь: Yes, I’d love to. Откажитесь: No, thank you и короткая причина.'],
es:['Deportes y ejercicio','Practica la forma -ing después de enjoy y don’t mind.','Invitaciones','Invita y acepta o rechaza con cortesía.','Un día ocupado mañana','Describe planes con be going to.','Usa Would you like to + verbo base para invitar a alguien a una actividad. I’d like to + verbo base expresa tu deseo.','Acepta con Yes, I’d love to. Rechaza con No, thank you y una breve razón.'],
pt:['Esportes e exercícios','Pratique a forma -ing após enjoy e don’t mind.','Convites','Convide alguém e aceite ou recuse com educação.','Um dia cheio amanhã','Descreva planos com be going to.','Use Would you like to + verbo base para convidar alguém a fazer algo. I’d like to + verbo base expressa seu desejo.','Aceite com Yes, I’d love to. Recuse com No, thank you e uma razão curta.'],
de:['Sport und Bewegung','Übe die -ing-Form nach enjoy und don’t mind.','Einladungen','Lade jemanden ein und sage höflich zu oder ab.','Ein voller Tag morgen','Beschreibe Pläne mit be going to.','Would you like to + Grundform lädt zu einer Tätigkeit ein. I’d like to + Grundform drückt deinen Wunsch aus.','Sage zu mit Yes, I’d love to. Sage ab mit No, thank you und einem kurzen Grund.'],
fr:['Sport et exercice','Pratique la forme -ing après enjoy et don’t mind.','Invitations','Invite quelqu’un et accepte ou refuse poliment.','Une journée chargée demain','Décris des projets avec be going to.','Would you like to + verbe de base invite quelqu’un à faire une activité. I’d like to + verbe de base exprime ton souhait.','Accepte avec Yes, I’d love to. Refuse avec No, thank you et une courte raison.'],
it:['Sport ed esercizio','Esercita la forma -ing dopo enjoy e don’t mind.','Inviti','Invita qualcuno e accetta o rifiuta gentilmente.','Una giornata impegnativa domani','Descrivi programmi con be going to.','Would you like to + verbo base invita a fare qualcosa. I’d like to + verbo base esprime il tuo desiderio.','Accetta con Yes, I’d love to. Rifiuta con No, thank you e un breve motivo.'],
hy:['Սպորտ և վարժություններ','Վարժվեք enjoy և don’t mind բառերից հետո -ing ձևն օգտագործել։','Հրավերներ','Հրավիրեք և քաղաքավարի ընդունեք կամ մերժեք հրավերը։','Վաղը զբաղված օր է','Նկարագրեք ծրագրերը be going to ձևով։','Would you like to + բայի սկզբնական ձևը հրավեր է որևէ բան անելու։ I’d like to + բայը հայտնում է ձեր ցանկությունը։','Ընդունեք՝ Yes, I’d love to. Մերժեք՝ No, thank you և կարճ պատճառ։'],
'zh-Hans':['运动与锻炼','练习 enjoy 和 don’t mind 后的 -ing 形式。','邀请','邀请他人，并礼貌地接受或拒绝。','忙碌的明天','用 be going to 描述计划。','用 Would you like to + 动词原形邀请他人做某事。I’d like to + 动词原形表达自己的愿望。','用 Yes, I’d love to 接受邀请；用 No, thank you 加简短原因拒绝。'],
ja:['スポーツと運動','enjoy と don’t mind の後の -ing 形を練習します。','招待','相手を誘い、丁寧に承諾または断ります。','忙しい明日','be going to で予定を説明します。','Would you like to + 動詞の原形で活動に誘います。I’d like to + 動詞の原形で自分の希望を表します。','Yes, I’d love to で承諾します。No, thank you と短い理由で断ります。'],
ko:['스포츠와 운동','enjoy와 don’t mind 뒤의 -ing 형태를 연습하세요.','초대','초대하고 정중하게 수락하거나 거절하세요.','바쁜 내일','be going to로 계획을 설명하세요.','Would you like to + 동사원형으로 활동에 초대하세요. I’d like to + 동사원형은 자신의 바람을 표현합니다.','Yes, I’d love to로 수락하세요. No, thank you와 짧은 이유로 거절하세요.'],
hi:['खेल और व्यायाम','enjoy और don’t mind के बाद -ing रूप का अभ्यास करें।','निमंत्रण','निमंत्रण दें और विनम्रता से स्वीकार या मना करें।','कल का व्यस्त दिन','be going to से योजनाएँ बताएँ।','किसी काम के लिए निमंत्रण देने में Would you like to + क्रिया का मूल रूप प्रयोग करें। I’d like to + मूल रूप अपनी इच्छा बताता है।','Yes, I’d love to से स्वीकार करें। No, thank you और छोटे कारण से मना करें।'],
bn:['খেলাধুলা ও ব্যায়াম','enjoy ও don’t mind-এর পরে -ing রূপ অনুশীলন করুন।','আমন্ত্রণ','আমন্ত্রণ জানান এবং ভদ্রভাবে গ্রহণ বা প্রত্যাখ্যান করুন।','আগামীকাল ব্যস্ত দিন','be going to দিয়ে পরিকল্পনা বর্ণনা করুন।','কাজে আমন্ত্রণ জানাতে Would you like to + ক্রিয়ার মূল রূপ ব্যবহার করুন। I’d like to + মূল রূপ নিজের ইচ্ছা বোঝায়।','Yes, I’d love to দিয়ে গ্রহণ করুন। No, thank you ও ছোট কারণ দিয়ে প্রত্যাখ্যান করুন।'],
ur:['کھیل اور ورزش','enjoy اور don’t mind کے بعد -ing کی شکل کی مشق کریں۔','دعوتیں','دعوت دیں اور شائستگی سے قبول یا انکار کریں۔','کل ایک مصروف دن','be going to سے منصوبے بیان کریں۔','کسی کام کی دعوت کے لیے Would you like to + فعل کی بنیادی شکل استعمال کریں۔ I’d like to + بنیادی شکل اپنی خواہش بتاتی ہے۔','Yes, I’d love to سے قبول کریں۔ No, thank you اور مختصر وجہ سے انکار کریں۔'],
ar:['الرياضة والتمارين','تدرّب على صيغة -ing بعد enjoy وdon’t mind.','الدعوات','ادعُ شخصًا واقبل أو ارفض بأدب.','يوم حافل غدًا','صف الخطط باستخدام be going to.','استخدم Would you like to + الفعل الأساسي لدعوة شخص إلى نشاط. واستخدم I’d like to + الفعل الأساسي للتعبير عن رغبتك.','اقبل بقول Yes, I’d love to. وارفض بقول No, thank you مع سبب قصير.'],
id:['Olahraga dan latihan','Latih bentuk -ing setelah enjoy dan don’t mind.','Undangan','Ajak seseorang dan terima atau tolak dengan sopan.','Hari yang sibuk besok','Jelaskan rencana dengan be going to.','Gunakan Would you like to + kata kerja dasar untuk mengajak seseorang melakukan kegiatan. I’d like to + kata kerja dasar menyatakan keinginanmu.','Terima dengan Yes, I’d love to. Tolak dengan No, thank you dan alasan singkat.'],
tr:['Spor ve egzersiz','enjoy ve don’t mind sonrasında -ing biçimini çalışın.','Davetler','Davet edin ve nazikçe kabul edin veya reddedin.','Yarın yoğun bir gün','Planları be going to ile anlatın.','Bir etkinliğe davet etmek için Would you like to + fiilin yalın hâlini kullanın. I’d like to + yalın fiil kendi isteğinizi anlatır.','Yes, I’d love to ile kabul edin. No, thank you ve kısa bir neden ile reddedin.'],
vi:['Thể thao và tập luyện','Luyện dạng -ing sau enjoy và don’t mind.','Lời mời','Mời người khác và lịch sự nhận lời hoặc từ chối.','Ngày mai bận rộn','Mô tả kế hoạch với be going to.','Dùng Would you like to + động từ nguyên mẫu để mời ai làm gì. I’d like to + động từ nguyên mẫu diễn đạt mong muốn của bạn.','Nhận lời bằng Yes, I’d love to. Từ chối bằng No, thank you và một lý do ngắn.'],
kk:['Спорт және жаттығу','enjoy және don’t mind сөздерінен кейін -ing түрін жаттықтырыңыз.','Шақырулар','Шақырыңыз және сыпайы түрде келісіңіз не бас тартыңыз.','Ертеңгі қарбалас күн','Жоспарларды be going to арқылы сипаттаңыз.','Әрекетке шақыру үшін Would you like to + етістіктің бастапқы түрін қолданыңыз. I’d like to + етістік өз қалауыңызды білдіреді.','Yes, I’d love to деп келісіңіз. No, thank you және қысқа себеппен бас тартыңыз.'],
uz:['Sport va mashqlar','enjoy va don’t mind dan keyin -ing shaklini mashq qiling.','Takliflar','Taklif qiling va muloyimlik bilan qabul qiling yoki rad eting.','Ertaga band kun','Rejalarni be going to bilan tasvirlang.','Biror ishga taklif qilish uchun Would you like to + fe’lning asosiy shaklini ishlating. I’d like to + asosiy shakl o‘z istagingizni bildiradi.','Yes, I’d love to bilan qabul qiling. No, thank you va qisqa sabab bilan rad eting.']
};
for(const [code,values] of Object.entries(lines)){
 if(!I.ui[code]||values.length!==keys.length)throw Error('Missing lesson 19–21 translation: '+code);
 Object.assign(I.ui[code],Object.fromEntries(keys.map((key,index)=>[key,values[index]])));
 if(I.ui[code].pilot)I.ui[code].pilot=I.ui[code].pilot.replace(/18|۱۸|١٨|१८|১৮|１８/g,m=>({'18':'21','۱۸':'۲۱','١٨':'٢١','१८':'२१','১৮':'২১','１８':'２１'}[m]));
}
})(typeof globalThis==='object'?globalThis:this);
