(function(root){
'use strict';
const en={reviewWords:'Review words',savedWord:'SAVED WORD',lessonWord:'LESSON WORD',dailyCards:'Words today',loading:'Loading cards…',sessionDone:'Review complete',comeBack:'Come back tomorrow for more words.',flipTitle:'Remember the word',recallTitle:'Say or type the English word',flipMode:'Flip cards',recallMode:'Speak or type',answerLabel:'ENGLISH WORD',clueLabel:'CLUE',flipCard:'Flip card',playWord:'Hear the word',again:'Practice again',knowIt:'I knew it',typeWord:'Type the English word',showAnswer:'Show answer',cardHint:'Try to remember before revealing the answer.',correctWord:'Correct! The word is ready for later review.',tryAgainWord:'See the answer and try this word again later.',todayGoal:'Today’s goal',goalDone:'Daily goal complete ✓',goalPrompt:'Complete one lesson or recall five words.',practiceThese:'Practice these words',correctAnswer:'Correct answer',micUnavailable:'Microphone unavailable. You can type the word.',micTimeout:'No speech heard. Try again or type the word.',listening:'Listening…',heard:'Heard',syncUnavailable:'Saved cards could not be loaded. Lesson words are still available.',saveError:'Review progress could not be saved.'};
const keys=['reviewWords','dailyCards','sessionDone','flipTitle','recallTitle','flipMode','recallMode','flipCard','again','knowIt','typeWord','showAnswer','todayGoal','goalDone','goalPrompt','practiceThese','correctAnswer'];
const rows={
 ru:['Повторить слова','Слов сегодня','Повторение завершено','Вспомните слово','Произнесите или напишите слово по-английски','Переворачивать','Говорить или писать','Перевернуть','Повторить','Я знал(а)','Напишите слово по-английски','Показать ответ','Цель на сегодня','Цель выполнена ✓','Пройдите один урок или вспомните пять слов.','Практика этих слов','Правильный ответ'],
 es:['Repasar palabras','Palabras hoy','Repaso terminado','Recuerda la palabra','Di o escribe la palabra en inglés','Voltear tarjetas','Hablar o escribir','Voltear tarjeta','Practicar otra vez','La sabía','Escribe la palabra en inglés','Mostrar respuesta','Objetivo de hoy','Objetivo cumplido ✓','Completa una lección o recuerda cinco palabras.','Practicar estas palabras','Respuesta correcta'],
 pt:['Revisar palavras','Palavras hoje','Revisão concluída','Lembre-se da palavra','Diga ou escreva a palavra em inglês','Virar cartões','Falar ou escrever','Virar cartão','Praticar novamente','Eu sabia','Digite a palavra em inglês','Mostrar resposta','Meta de hoje','Meta concluída ✓','Conclua uma aula ou lembre-se de cinco palavras.','Praticar estas palavras','Resposta correta'],
 de:['Wörter wiederholen','Wörter heute','Wiederholung abgeschlossen','Erinnere dich an das Wort','Sprich oder schreibe das englische Wort','Karten umdrehen','Sprechen oder tippen','Karte umdrehen','Noch einmal üben','Ich wusste es','Englisches Wort eingeben','Antwort zeigen','Tagesziel','Tagesziel erreicht ✓','Schließe eine Lektion ab oder erinnere dich an fünf Wörter.','Diese Wörter üben','Richtige Antwort'],
 fr:['Réviser les mots','Mots aujourd’hui','Révision terminée','Retrouvez le mot','Dites ou écrivez le mot anglais','Retourner les cartes','Parler ou écrire','Retourner la carte','Réessayer','Je le savais','Écrivez le mot anglais','Voir la réponse','Objectif du jour','Objectif atteint ✓','Terminez une leçon ou retrouvez cinq mots.','Réviser ces mots','Bonne réponse'],
 it:['Ripassa le parole','Parole oggi','Ripasso completato','Ricorda la parola','Pronuncia o scrivi la parola inglese','Gira le carte','Parla o scrivi','Gira la carta','Riprova','La sapevo','Scrivi la parola inglese','Mostra la risposta','Obiettivo di oggi','Obiettivo raggiunto ✓','Completa una lezione o ricorda cinque parole.','Ripassa queste parole','Risposta corretta'],
 hy:['Կրկնել բառերը','Բառեր այսօր','Կրկնությունն ավարտված է','Հիշեք բառը','Ասեք կամ գրեք անգլերեն բառը','Շրջել քարտերը','Խոսել կամ գրել','Շրջել քարտը','Կրկնել','Գիտեի','Գրեք անգլերեն բառը','Ցույց տալ պատասխանը','Այսօրվա նպատակը','Նպատակը կատարված է ✓','Ավարտեք մեկ դաս կամ հիշեք հինգ բառ։','Կրկնել այս բառերը','Ճիշտ պատասխան'],
 'zh-Hans':['复习单词','今日单词','复习完成','回想这个单词','说出或输入英文单词','翻转卡片','说出或输入','翻转卡片','再次练习','我记得','输入英文单词','显示答案','今日目标','目标已完成 ✓','完成一节课或回想五个单词。','练习这些单词','正确答案'],
 ja:['単語を復習','今日の単語','復習完了','単語を思い出しましょう','英単語を話すか入力してください','カードをめくる','話すか入力','カードをめくる','もう一度練習','覚えていた','英単語を入力','答えを見る','今日の目標','目標達成 ✓','レッスンを1つ終えるか、5語を思い出しましょう。','この単語を練習','正しい答え'],
 ko:['단어 복습','오늘의 단어','복습 완료','단어를 떠올려 보세요','영어 단어를 말하거나 입력하세요','카드 뒤집기','말하기 또는 입력','카드 뒤집기','다시 연습','알고 있었어요','영어 단어 입력','답 보기','오늘의 목표','목표 달성 ✓','수업 하나를 마치거나 단어 다섯 개를 떠올리세요.','이 단어 연습','정답'],
 hi:['शब्द दोहराएँ','आज के शब्द','दोहराना पूरा हुआ','शब्द याद करें','अंग्रेज़ी शब्द बोलें या लिखें','कार्ड पलटें','बोलें या लिखें','कार्ड पलटें','फिर अभ्यास करें','मुझे याद था','अंग्रेज़ी शब्द लिखें','उत्तर दिखाएँ','आज का लक्ष्य','लक्ष्य पूरा ✓','एक पाठ पूरा करें या पाँच शब्द याद करें।','इन शब्दों का अभ्यास करें','सही उत्तर'],
 bn:['শব্দ পুনরাভ্যাস','আজকের শব্দ','পুনরাভ্যাস শেষ','শব্দটি মনে করুন','ইংরেজি শব্দটি বলুন বা লিখুন','কার্ড উল্টান','বলুন বা লিখুন','কার্ড উল্টান','আবার অনুশীলন','আমি জানতাম','ইংরেজি শব্দ লিখুন','উত্তর দেখান','আজকের লক্ষ্য','লক্ষ্য পূরণ ✓','একটি পাঠ শেষ করুন বা পাঁচটি শব্দ মনে করুন।','এই শব্দগুলো অনুশীলন','সঠিক উত্তর'],
 ur:['الفاظ دہرائیں','آج کے الفاظ','دہرائی مکمل','لفظ یاد کریں','انگریزی لفظ بولیں یا لکھیں','کارڈ پلٹیں','بولیں یا لکھیں','کارڈ پلٹیں','دوبارہ مشق','مجھے معلوم تھا','انگریزی لفظ لکھیں','جواب دکھائیں','آج کا ہدف','ہدف مکمل ✓','ایک سبق مکمل کریں یا پانچ الفاظ یاد کریں۔','ان الفاظ کی مشق','درست جواب'],
 ar:['راجع الكلمات','كلمات اليوم','اكتملت المراجعة','تذكّر الكلمة','قل الكلمة الإنجليزية أو اكتبها','اقلب البطاقات','تحدث أو اكتب','اقلب البطاقة','تدرّب مجددًا','كنت أعرفها','اكتب الكلمة الإنجليزية','أظهر الإجابة','هدف اليوم','اكتمل الهدف ✓','أكمل درسًا واحدًا أو تذكّر خمس كلمات.','تدرّب على هذه الكلمات','الإجابة الصحيحة'],
 id:['Ulangi kata','Kata hari ini','Ulangan selesai','Ingat katanya','Ucapkan atau ketik kata bahasa Inggris','Balik kartu','Ucapkan atau ketik','Balik kartu','Latihan lagi','Saya tahu','Ketik kata bahasa Inggris','Tampilkan jawaban','Target hari ini','Target tercapai ✓','Selesaikan satu pelajaran atau ingat lima kata.','Latih kata-kata ini','Jawaban benar'],
 tr:['Kelimeleri tekrarla','Bugünkü kelimeler','Tekrar tamamlandı','Kelimeyi hatırla','İngilizce kelimeyi söyle veya yaz','Kartları çevir','Söyle veya yaz','Kartı çevir','Tekrar çalış','Biliyordum','İngilizce kelimeyi yaz','Cevabı göster','Günün hedefi','Hedef tamamlandı ✓','Bir ders bitir veya beş kelimeyi hatırla.','Bu kelimeleri çalış','Doğru cevap'],
 vi:['Ôn từ vựng','Từ hôm nay','Ôn tập xong','Nhớ lại từ','Nói hoặc gõ từ tiếng Anh','Lật thẻ','Nói hoặc gõ','Lật thẻ','Luyện lại','Tôi đã biết','Gõ từ tiếng Anh','Hiện đáp án','Mục tiêu hôm nay','Đã đạt mục tiêu ✓','Hoàn thành một bài hoặc nhớ lại năm từ.','Luyện các từ này','Đáp án đúng'],
 kk:['Сөздерді қайталау','Бүгінгі сөздер','Қайталау аяқталды','Сөзді еске түсіріңіз','Ағылшын сөзін айтыңыз не жазыңыз','Карталарды аудару','Айту не жазу','Картаны аудару','Қайта жаттығу','Мен білдім','Ағылшын сөзін жазыңыз','Жауапты көрсету','Бүгінгі мақсат','Мақсат орындалды ✓','Бір сабақ аяқтаңыз немесе бес сөзді еске түсіріңіз.','Осы сөздерді жаттығу','Дұрыс жауап'],
 uz:['So‘zlarni takrorlash','Bugungi so‘zlar','Takrorlash tugadi','So‘zni eslang','Inglizcha so‘zni ayting yoki yozing','Kartalarni aylantirish','Ayting yoki yozing','Kartani aylantiring','Qayta mashq','Bilgan edim','Inglizcha so‘zni yozing','Javobni ko‘rsatish','Bugungi maqsad','Maqsad bajarildi ✓','Bir darsni tugating yoki besh so‘zni eslang.','Bu so‘zlarni mashq qiling','To‘g‘ri javob']
};
const ui={en};en.recallTitle=en.typeWord;en.recallMode='Type';
const typeMode={ru:'Написать',es:'Escribir',pt:'Escrever',de:'Schreiben',fr:'Écrire',it:'Scrivere',hy:'Գրել','zh-Hans':'输入',ja:'入力',ko:'입력',hi:'लिखें',bn:'লিখুন',ur:'لکھیں',ar:'اكتب',id:'Ketik',tr:'Yaz',vi:'Gõ',kk:'Жазу',uz:'Yozish'};
for(const [locale,values] of Object.entries(rows)){ui[locale]={...en};keys.forEach((key,i)=>ui[locale][key]=values[i]);ui[locale].recallTitle=ui[locale].typeWord;ui[locale].recallMode=typeMode[locale];}root.EvoCourseReviewI18n=ui;if(typeof module==='object'&&module.exports)module.exports=ui;
})(typeof globalThis==='object'?globalThis:this);
