(function(root){
'use strict';
const I=root.EvoCourseI18n;if(!I)return;
const keys=['l10','g10','l11','g11','l12','g12','transportPoint','transportVehicle','timeAtInOn','timeNoPreposition','questionsWithBe','questionsWithDo','pilot'];
const words={
 en:['Around the city','Use at, in and on to talk about places and transport.','My daily schedule','Talk about clock times, days and parts of the day.','Countries and languages','Ask where someone is from and which languages they speak.','Use at for a specific point, such as at the bus stop, and in for an area, such as in the city.','Use on for buses and the metro, but in for a taxi or car.','Use at for clock times (at 7:00), in for parts of the day (in the evening), and on for days (on Monday).','Do not add at, in or on before every, next, last or this: every weekday, next Monday.','With be, put am, is or are before the subject: Where is Emma from?','For other Present Simple verbs, use do or does + subject + base verb: What language does she speak?','Prototype · 12 A1 lessons · the rest of the course is in development.'],
 ru:['По городу','Используйте at, in и on для мест и транспорта.','Мой распорядок дня','Говорите о времени, днях и частях суток.','Страны и языки','Спросите, откуда человек и на каких языках он говорит.','Для конкретного места используйте at: at the bus stop. Для территории — in: in the city.','В автобусе и метро используйте on, а в такси и машине — in.','Для точного времени используйте at (at 7:00), для частей суток — in (in the evening), для дней — on (on Monday).','Перед every, next, last и this не ставьте at, in или on: every weekday, next Monday.','В вопросе с be ставьте am, is или are перед подлежащим: Where is Emma from?','С другими глаголами в Present Simple используйте do или does + подлежащее + начальную форму глагола: What language does she speak?','Прототип · 12 уроков A1 · остальная часть курса в разработке.'],
 es:['Por la ciudad','Usa at, in y on para hablar de lugares y transportes.','Mi rutina diaria','Habla de horas, días y momentos del día.','Países e idiomas','Pregunta de dónde es alguien y qué idiomas habla.','Usa at para un punto concreto, como at the bus stop, e in para una zona, como in the city.','Usa on para el autobús y el metro, pero in para un taxi o coche.','Usa at para las horas (at 7:00), in para los momentos del día (in the evening) y on para los días (on Monday).','No añadas at, in ni on antes de every, next, last o this: every weekday, next Monday.','Con be, coloca am, is o are antes del sujeto: Where is Emma from?','Con otros verbos en Present Simple, usa do o does + sujeto + verbo base: What language does she speak?','Prototipo · 12 lecciones A1 · el resto del curso está en desarrollo.'],
 pt:['Pela cidade','Use at, in e on para falar de lugares e transportes.','Minha rotina diária','Fale sobre horas, dias e partes do dia.','Países e idiomas','Pergunte de onde alguém é e que idiomas fala.','Use at para um ponto específico, como at the bus stop, e in para uma área, como in the city.','Use on para ônibus e metrô, mas in para táxi ou carro.','Use at para horas (at 7:00), in para partes do dia (in the evening) e on para dias (on Monday).','Não use at, in ou on antes de every, next, last ou this: every weekday, next Monday.','Com be, coloque am, is ou are antes do sujeito: Where is Emma from?','Com outros verbos no Present Simple, use do ou does + sujeito + verbo base: What language does she speak?','Protótipo · 12 aulas A1 · o restante do curso está em desenvolvimento.'],
 de:['Unterwegs in der Stadt','Verwende at, in und on für Orte und Verkehrsmittel.','Mein Tagesablauf','Sprich über Uhrzeiten, Tage und Tageszeiten.','Länder und Sprachen','Frage, woher jemand kommt und welche Sprachen er spricht.','Verwende at für einen bestimmten Punkt wie at the bus stop und in für ein Gebiet wie in the city.','Verwende on für Bus und Metro, aber in für Taxi und Auto.','Verwende at für Uhrzeiten (at 7:00), in für Tageszeiten (in the evening) und on für Tage (on Monday).','Setze vor every, next, last oder this kein at, in oder on: every weekday, next Monday.','Bei be steht am, is oder are vor dem Subjekt: Where is Emma from?','Bei anderen Verben im Present Simple verwende do oder does + Subjekt + Grundform: What language does she speak?','Prototyp · 12 A1-Lektionen · der Rest des Kurses wird entwickelt.'],
 fr:['En ville','Utilise at, in et on pour parler des lieux et des transports.','Ma routine quotidienne','Parle des heures, des jours et des moments de la journée.','Pays et langues','Demande d’où vient une personne et quelles langues elle parle.','Utilise at pour un point précis, comme at the bus stop, et in pour une zone, comme in the city.','Utilise on pour le bus et le métro, mais in pour un taxi ou une voiture.','Utilise at pour les heures (at 7:00), in pour les moments de la journée (in the evening) et on pour les jours (on Monday).','Ne mets pas at, in ou on avant every, next, last ou this : every weekday, next Monday.','Avec be, place am, is ou are avant le sujet : Where is Emma from?','Avec les autres verbes au Present Simple, utilise do ou does + sujet + base verbale : What language does she speak?','Prototype · 12 leçons A1 · la suite du cours est en préparation.'],
 it:['In giro per la città','Usa at, in e on per parlare di luoghi e trasporti.','La mia routine quotidiana','Parla di orari, giorni e momenti della giornata.','Paesi e lingue','Chiedi da dove viene una persona e quali lingue parla.','Usa at per un punto preciso, come at the bus stop, e in per un’area, come in the city.','Usa on per autobus e metro, ma in per taxi e auto.','Usa at per gli orari (at 7:00), in per le parti del giorno (in the evening) e on per i giorni (on Monday).','Non aggiungere at, in o on prima di every, next, last o this: every weekday, next Monday.','Con be, metti am, is o are prima del soggetto: Where is Emma from?','Con gli altri verbi al Present Simple, usa do o does + soggetto + forma base: What language does she speak?','Prototipo · 12 lezioni A1 · il resto del corso è in preparazione.'],
 hy:['Քաղաքում','Վայրերի և փոխադրամիջոցների մասին խոսելիս օգտագործեք at, in և on։','Իմ օրվա ռեժիմը','Խոսեք ժամերի, օրերի և օրվա հատվածների մասին։','Երկրներ և լեզուներ','Հարցրեք՝ որտեղից է մարդը և ինչ լեզուներով է խոսում։','Կոնկրետ կետի համար օգտագործեք at, օրինակ՝ at the bus stop, իսկ տարածքի համար՝ in, օրինակ՝ in the city։','Ավտոբուսի և մետրոյի համար օգտագործեք on, իսկ տաքսու և մեքենայի համար՝ in։','Ժամերի համար օգտագործեք at (at 7:00), օրվա հատվածների համար՝ in (in the evening), օրերի համար՝ on (on Monday)։','every, next, last և this բառերից առաջ մի դրեք at, in կամ on՝ every weekday, next Monday։','be բայով հարցում am, is կամ are ձևը դրեք ենթակայից առաջ՝ Where is Emma from?','Present Simple-ի մյուս բայերի հետ օգտագործեք do կամ does + ենթակա + բայի հիմնական ձև՝ What language does she speak?','Նախատիպ · A1-ի 12 դաս · դասընթացի մնացած մասը մշակվում է։'],
 'zh-Hans':['城市出行','用 at、in 和 on 表达地点与交通方式。','我的日常安排','谈论钟点、日期和一天中的时段。','国家与语言','询问别人来自哪里、会说哪些语言。','表示具体地点用 at，如 at the bus stop；表示区域用 in，如 in the city。','乘坐公交车或地铁用 on；乘坐出租车或汽车用 in。','钟点用 at（at 7:00），一天中的时段用 in（in the evening），星期几用 on（on Monday）。','every、next、last 或 this 前不要加 at、in、on：every weekday、next Monday。','使用 be 提问时，把 am、is 或 are 放在主语前：Where is Emma from?','其他一般现在时动词提问时，用 do 或 does + 主语 + 动词原形：What language does she speak?','预览版 · 12 节 A1 课程 · 其余课程正在制作中。'],
 ja:['街の移動','場所や交通手段には at、in、on を使い分けます。','毎日の予定','時刻、曜日、時間帯について話します。','国と言語','出身地や話す言語を尋ねます。','特定の地点には at（at the bus stop）、地域には in（in the city）を使います。','バスや地下鉄には on、タクシーや車には in を使います。','時刻には at（at 7:00）、時間帯には in（in the evening）、曜日には on（on Monday）を使います。','every、next、last、this の前に at、in、on は付けません：every weekday、next Monday。','be の疑問文では am、is、are を主語の前に置きます：Where is Emma from?','一般動詞の現在形の疑問文では do または does + 主語 + 動詞の原形を使います：What language does she speak?','試作版 · A1 全12レッスン · 続きは制作中です。'],
 ko:['도시에서 이동하기','장소와 교통수단을 말할 때 at, in, on을 사용합니다.','나의 하루 일정','시각, 요일, 하루 중 시간을 말합니다.','나라와 언어','상대의 출신과 사용하는 언어를 묻습니다.','특정 지점에는 at(at the bus stop), 지역에는 in(in the city)을 씁니다.','버스와 지하철에는 on, 택시와 자동차에는 in을 씁니다.','시각에는 at(at 7:00), 하루 중 시간에는 in(in the evening), 요일에는 on(on Monday)을 씁니다.','every, next, last, this 앞에는 at, in, on을 쓰지 않습니다: every weekday, next Monday.','be 동사 의문문에서는 am, is, are를 주어 앞에 놓습니다: Where is Emma from?','다른 현재형 동사에는 do 또는 does + 주어 + 동사원형을 씁니다: What language does she speak?','미리보기 · A1 12개 수업 · 나머지 과정은 제작 중입니다.'],
 hi:['शहर में आना-जाना','स्थान और यातायात के लिए at, in और on का प्रयोग करें।','मेरी दिनचर्या','समय, दिन और दिन के हिस्सों के बारे में बोलें।','देश और भाषाएँ','पूछें कि कोई कहाँ से है और कौन-सी भाषाएँ बोलता है।','किसी निश्चित स्थान के लिए at, जैसे at the bus stop; क्षेत्र के लिए in, जैसे in the city, प्रयोग करें।','बस और मेट्रो के लिए on, लेकिन टैक्सी और कार के लिए in प्रयोग करें।','घड़ी के समय के लिए at (at 7:00), दिन के हिस्से के लिए in (in the evening), और दिनों के लिए on (on Monday) प्रयोग करें।','every, next, last या this से पहले at, in या on न लगाएँ: every weekday, next Monday।','be वाले प्रश्न में am, is या are को कर्ता से पहले रखें: Where is Emma from?','Present Simple के अन्य क्रियापदों के साथ do या does + कर्ता + क्रिया का मूल रूप प्रयोग करें: What language does she speak?','प्रोटोटाइप · A1 के 12 पाठ · बाकी पाठ तैयार किए जा रहे हैं।'],
 bn:['শহরে চলাচল','স্থান ও যানবাহন বোঝাতে at, in এবং on ব্যবহার করুন।','আমার দৈনন্দিন সময়সূচি','সময়, দিন ও দিনের বিভিন্ন ভাগ নিয়ে বলুন।','দেশ ও ভাষা','কেউ কোথা থেকে এসেছেন এবং কোন ভাষায় কথা বলেন তা জিজ্ঞেস করুন।','নির্দিষ্ট জায়গার জন্য at, যেমন at the bus stop; এলাকার জন্য in, যেমন in the city ব্যবহার করুন।','বাস ও মেট্রোর জন্য on, কিন্তু ট্যাক্সি ও গাড়ির জন্য in ব্যবহার করুন।','ঘড়ির সময়ের জন্য at (at 7:00), দিনের ভাগের জন্য in (in the evening), আর দিনের জন্য on (on Monday) ব্যবহার করুন।','every, next, last বা this-এর আগে at, in বা on বসাবেন না: every weekday, next Monday।','be দিয়ে প্রশ্নে am, is বা are কর্তার আগে বসে: Where is Emma from?','Present Simple-এর অন্য ক্রিয়ার প্রশ্নে do বা does + কর্তা + মূল ক্রিয়া ব্যবহার করুন: What language does she speak?','নমুনা · A1-এর ১২টি পাঠ · বাকি কোর্স তৈরি হচ্ছে।'],
 ur:['شہر میں آمد و رفت','جگہوں اور سواریوں کے لیے at، in اور on استعمال کریں۔','میرا روزانہ کا معمول','وقت، دنوں اور دن کے حصوں کے بارے میں بات کریں۔','ممالک اور زبانیں','پوچھیں کہ کوئی کہاں سے ہے اور کون سی زبانیں بولتا ہے۔','کسی خاص مقام کے لیے at، جیسے at the bus stop، اور علاقے کے لیے in، جیسے in the city استعمال کریں۔','بس اور میٹرو کے لیے on، لیکن ٹیکسی یا کار کے لیے in استعمال کریں۔','گھڑی کے وقت کے لیے at (at 7:00)، دن کے حصوں کے لیے in (in the evening)، اور دنوں کے لیے on (on Monday) استعمال کریں۔','every، next، last یا this سے پہلے at، in یا on نہ لگائیں: every weekday، next Monday۔','be کے سوال میں am، is یا are کو فاعل سے پہلے رکھیں: Where is Emma from?','Present Simple کے دوسرے افعال کے لیے do یا does + فاعل + فعل کی بنیادی شکل استعمال کریں: What language does she speak?','ابتدائی نمونہ · A1 کے 12 اسباق · باقی کورس تیار ہو رہا ہے۔'],
 ar:['التنقل في المدينة','استخدم at وin وon للتحدث عن الأماكن ووسائل النقل.','روتيني اليومي','تحدث عن الساعة والأيام وأوقات اليوم.','البلدان واللغات','اسأل عن بلد الشخص واللغات التي يتحدث بها.','استخدم at لمكان محدد، مثل at the bus stop، وin لمنطقة، مثل in the city.','استخدم on للحافلة والمترو، وin لسيارة الأجرة أو السيارة.','استخدم at للساعة (at 7:00)، وin لأوقات اليوم (in the evening)، وon للأيام (on Monday).','لا تضف at أو in أو on قبل every أو next أو last أو this: every weekday، next Monday.','في السؤال مع be، ضع am أو is أو are قبل الفاعل: Where is Emma from?','مع الأفعال الأخرى في Present Simple، استخدم do أو does + الفاعل + الفعل في صورته الأساسية: What language does she speak?','نسخة تجريبية · 12 درسًا A1 · بقية الدورة قيد الإعداد.'],
 id:['Keliling kota','Gunakan at, in, dan on untuk tempat dan transportasi.','Rutinitas harian saya','Bicarakan jam, hari, dan waktu dalam sehari.','Negara dan bahasa','Tanyakan asal seseorang dan bahasa yang mereka gunakan.','Gunakan at untuk titik tertentu, seperti at the bus stop, dan in untuk wilayah, seperti in the city.','Gunakan on untuk bus dan metro, tetapi in untuk taksi atau mobil.','Gunakan at untuk jam (at 7:00), in untuk bagian hari (in the evening), dan on untuk hari (on Monday).','Jangan tambahkan at, in, atau on sebelum every, next, last, atau this: every weekday, next Monday.','Dalam pertanyaan dengan be, letakkan am, is, atau are sebelum subjek: Where is Emma from?','Dengan kata kerja lain dalam Present Simple, gunakan do atau does + subjek + bentuk dasar kata kerja: What language does she speak?','Prototipe · 12 pelajaran A1 · sisanya sedang dibuat.'],
 tr:['Şehirde ulaşım','Yerleri ve ulaşımı anlatırken at, in ve on kullan.','Günlük programım','Saatler, günler ve günün bölümleri hakkında konuş.','Ülkeler ve diller','Birinin nereli olduğunu ve hangi dilleri konuştuğunu sor.','Belirli bir nokta için at (at the bus stop), bir alan için in (in the city) kullan.','Otobüs ve metro için on, taksi ve araba için in kullan.','Saatler için at (at 7:00), günün bölümleri için in (in the evening), günler için on (on Monday) kullan.','every, next, last veya this önüne at, in ya da on ekleme: every weekday, next Monday.','be ile soruda am, is veya are öznenin önüne gelir: Where is Emma from?','Present Simple içindeki diğer fiillerle do veya does + özne + fiilin yalın hâlini kullan: What language does she speak?','Prototip · 12 A1 dersi · kursun kalanı hazırlanıyor.'],
 vi:['Đi lại trong thành phố','Dùng at, in và on để nói về địa điểm và phương tiện.','Lịch sinh hoạt hằng ngày','Nói về giờ, ngày và các buổi trong ngày.','Quốc gia và ngôn ngữ','Hỏi một người đến từ đâu và nói những ngôn ngữ nào.','Dùng at cho một điểm cụ thể như at the bus stop, và in cho một khu vực như in the city.','Dùng on cho xe buýt và tàu điện, nhưng in cho taxi hoặc ô tô.','Dùng at với giờ (at 7:00), in với buổi trong ngày (in the evening), và on với ngày (on Monday).','Không thêm at, in hoặc on trước every, next, last hoặc this: every weekday, next Monday.','Với be, đặt am, is hoặc are trước chủ ngữ: Where is Emma from?','Với động từ khác ở Present Simple, dùng do hoặc does + chủ ngữ + động từ nguyên mẫu: What language does she speak?','Bản thử · 12 bài A1 · phần còn lại đang được xây dựng.'],
 kk:['Қаладағы көлік','Орындар мен көлік туралы айтқанда at, in және on қолданыңыз.','Менің күн тәртібім','Сағат, күндер және тәулік мезгілдері туралы айтыңыз.','Елдер мен тілдер','Адамның қайдан екенін және қандай тілде сөйлейтінін сұраңыз.','Нақты нүкте үшін at (at the bus stop), аумақ үшін in (in the city) қолданыңыз.','Автобус пен метрода on, такси мен көлікте in қолданыңыз.','Сағатпен at (at 7:00), тәулік мезгілімен in (in the evening), күнмен on (on Monday) қолданыңыз.','every, next, last немесе this сөздерінің алдына at, in не on қоймаңыз: every weekday, next Monday.','be етістігімен сұрақта am, is немесе are бастауыштың алдында тұрады: Where is Emma from?','Present Simple шағындағы басқа етістіктермен do немесе does + бастауыш + етістіктің негізгі түрін қолданыңыз: What language does she speak?','Прототип · A1 деңгейінің 12 сабағы · қалған курс әзірленуде.'],
 uz:['Shahar bo‘ylab','Joylar va transport haqida gapirganda at, in va on dan foydalaning.','Mening kundalik tartibim','Soatlar, kunlar va kunning qismlari haqida gapiring.','Mamlakatlar va tillar','Kimning qayerdan ekanini va qaysi tillarda gapirishini so‘rang.','Aniq nuqta uchun at (at the bus stop), hudud uchun in (in the city) ishlating.','Avtobus va metro uchun on, taksi yoki mashina uchun in ishlating.','Soat uchun at (at 7:00), kunning qismi uchun in (in the evening), kun uchun on (on Monday) ishlating.','every, next, last yoki this oldidan at, in yoki on qo‘ymang: every weekday, next Monday.','be bilan savolda am, is yoki are egadan oldin keladi: Where is Emma from?','Present Simple dagi boshqa fe’llar bilan do yoki does + ega + fe’lning asosiy shaklini ishlating: What language does she speak?','Prototip · A1 uchun 12 dars · qolgan kurs tayyorlanmoqda.']
};
const labels={
 en:['Use the English prompt below to practise this topic with AI Assistant.','Show transcript','Replay lesson audio'],
 ru:['Используйте английскую подсказку ниже, чтобы потренировать эту тему с AI Assistant.','Открыть транскрипцию','Повторно прослушать аудио урока'],
 es:['Usa la indicación en inglés de abajo para practicar este tema con AI Assistant.','Mostrar transcripción','Volver a escuchar el audio'],
 pt:['Use a sugestão em inglês abaixo para praticar este tema com o AI Assistant.','Mostrar transcrição','Ouvir o áudio novamente'],
 de:['Nutze die englische Aufgabe unten, um dieses Thema mit AI Assistant zu üben.','Transkript anzeigen','Lektionsaudio erneut abspielen'],
 fr:['Utilisez la consigne en anglais ci-dessous pour pratiquer ce sujet avec AI Assistant.','Afficher la transcription','Réécouter l’audio de la leçon'],
 it:['Usa la traccia in inglese qui sotto per esercitarti su questo tema con AI Assistant.','Mostra la trascrizione','Riascolta l’audio della lezione'],
 hy:['Ստորև բերված անգլերեն հուշումով այս թեման վարժեք AI Assistant-ի հետ։','Ցույց տալ տեքստը','Կրկին լսել դասի աուդիոն'],
 'zh-Hans':['使用下方的英语提示，与 AI Assistant 练习本课话题。','显示音频文本','重听本课音频'],
 ja:['下の英語の指示を使い、AI Assistant とこのテーマを練習しましょう。','文字起こしを表示','レッスン音声をもう一度聞く'],
 ko:['아래 영어 안내를 따라 AI Assistant와 이 주제를 연습하세요.','대본 보기','수업 오디오 다시 듣기'],
 hi:['नीचे दिए अंग्रेज़ी संकेत से AI Assistant के साथ इस विषय पर बोलने का अभ्यास करें।','प्रतिलेख दिखाएँ','पाठ का ऑडियो फिर सुनें'],
 bn:['নিচের ইংরেজি নির্দেশনা দিয়ে AI Assistant-এর সঙ্গে এই বিষয়ে কথা বলার অনুশীলন করুন।','লিখিত পাঠ দেখুন','পাঠের অডিও আবার শুনুন'],
 ur:['نیچے دی گئی انگریزی ہدایت سے AI Assistant کے ساتھ اس موضوع پر بولنے کی مشق کریں۔','تحریری متن دکھائیں','سبق کی آڈیو دوبارہ سنیں'],
 ar:['استخدم التعليمات الإنجليزية أدناه للتدرّب على هذا الموضوع مع AI Assistant.','عرض النص المكتوب','أعِد تشغيل صوت الدرس'],
 id:['Gunakan petunjuk bahasa Inggris di bawah untuk berlatih topik ini bersama AI Assistant.','Tampilkan transkrip','Putar ulang audio pelajaran'],
 tr:['Aşağıdaki İngilizce yönergeyle bu konuyu AI Assistant ile konuşarak çalış.','Metni göster','Ders sesini tekrar dinle'],
 vi:['Dùng gợi ý tiếng Anh bên dưới để luyện nói chủ đề này với AI Assistant.','Hiện bản chép lời','Nghe lại âm thanh bài học'],
 kk:['Төмендегі ағылшын нұсқаулығымен осы тақырыпты AI Assistant арқылы сөйлеп жаттықтырыңыз.','Мәтінді көрсету','Сабақ аудиосын қайта тыңдау'],
 uz:['Quyidagi inglizcha ko‘rsatma bilan bu mavzuni AI Assistant orqali gapirib mashq qiling.','Matnni ko‘rsatish','Dars audiosini qayta tinglash']
};
for(const [code,strings] of Object.entries(words)){
 if(strings.length!==keys.length||labels[code]?.length!==3||!I.ui[code])throw Error('Missing A1 course translation: '+code);
 Object.assign(I.ui[code],Object.fromEntries(keys.map((key,index)=>[key,strings[index]])),Object.fromEntries(['speakingText','transcriptLabel','replayAudio'].map((key,index)=>[key,labels[code][index]])));
}
const nextKeys=['l13','g13','l14','g14','l15','g15','adjectiveBefore','adjectiveAfter','adjectiveNoPlural','articleFirst','articleSpecific','articleZero','thereExists','itRefers','itWeatherTime','pilot'];
const nextWords={
 en:['Describing people','Use adjectives to describe people and feelings.','My apartment and articles','Choose a/an, the or no article in familiar situations.','Life in a village','Use there to introduce something and it to describe it.','Put an adjective before a noun: a kind person.','Use an adjective after be and feel: Alex is kind; Anna feels happy.','Adjectives do not change in the plural: kind people.','Use a/an for a singular countable noun when you first mention it: a balcony, an apartment.','Use the for something specific or already mentioned: the balcony.','Use no article for general plural nouns or uncountable things: rooms, coffee.','Use there is/are to say something exists: There is a shop.','Use it for one thing already mentioned, or they for more than one: It is small; They are small.','Use it for weather and time: It is sunny; It is seven o’clock.','Prototype · 15 A1 lessons · the rest of the course is in development.'],
 ru:['Описание людей','Описывайте людей и чувства прилагательными.','Моя квартира и артикли','Выбирайте a/an, the или отсутствие артикля.','Жизнь в деревне','Используйте there, чтобы назвать предмет, а it — чтобы описать его.','Прилагательное ставится перед существительным: a kind person.','После be и feel ставьте прилагательное: Alex is kind; Anna feels happy.','Прилагательные не меняются во множественном числе: kind people.','При первом упоминании одного исчисляемого предмета ставьте a/an: a balcony, an apartment.','Для конкретного или уже названного предмета используйте the: the balcony.','Когда говорите о множестве предметов или веществе в целом, артикль не нужен: rooms, coffee.','There is/are сообщает, что что-то существует: There is a shop.','Для уже названного одного предмета используйте it, для нескольких — they: It is small; They are small.','Для погоды и времени используйте it: It is sunny; It is seven o’clock.','Прототип · 15 уроков A1 · остальная часть курса в разработке.'],
 es:['Describir personas','Usa adjetivos para describir personas y sentimientos.','Mi apartamento y los artículos','Elige a/an, the o ningún artículo.','La vida en un pueblo','Usa there para presentar algo e it para describirlo.','Pon el adjetivo antes del sustantivo: a kind person.','Usa un adjetivo después de be y feel: Alex is kind; Anna feels happy.','Los adjetivos no cambian en plural: kind people.','Usa a/an al mencionar por primera vez un sustantivo contable singular: a balcony, an apartment.','Usa the para algo concreto o ya mencionado: the balcony.','Sin artículo para plurales y nombres incontables en general: rooms, coffee.','Usa there is/are para decir que algo existe: There is a shop.','Usa it para una cosa ya mencionada y they para varias: It is small; They are small.','Usa it para el tiempo atmosférico y la hora: It is sunny; It is seven o’clock.','Prototipo · 15 lecciones A1 · el resto del curso está en desarrollo.'],
 pt:['Descrever pessoas','Use adjetivos para descrever pessoas e sentimentos.','Meu apartamento e os artigos','Escolha a/an, the ou nenhum artigo.','Vida numa aldeia','Use there para apresentar algo e it para descrevê-lo.','Coloque o adjetivo antes do substantivo: a kind person.','Use um adjetivo após be e feel: Alex is kind; Anna feels happy.','Adjetivos não mudam no plural: kind people.','Use a/an na primeira menção de um substantivo contável singular: a balcony, an apartment.','Use the para algo específico ou já mencionado: the balcony.','Sem artigo para plurais e incontáveis em geral: rooms, coffee.','Use there is/are para dizer que algo existe: There is a shop.','Use it para uma coisa já mencionada e they para várias: It is small; They are small.','Use it para o clima e as horas: It is sunny; It is seven o’clock.','Protótipo · 15 aulas A1 · o restante do curso está em desenvolvimento.'],
 de:['Menschen beschreiben','Beschreibe Menschen und Gefühle mit Adjektiven.','Meine Wohnung und Artikel','Wähle a/an, the oder keinen Artikel.','Leben im Dorf','Führe etwas mit there ein und beschreibe es mit it.','Das Adjektiv steht vor dem Substantiv: a kind person.','Nach be und feel steht ein Adjektiv: Alex is kind; Anna feels happy.','Adjektive ändern sich im Plural nicht: kind people.','Verwende a/an bei der ersten Erwähnung eines zählbaren Nomens im Singular: a balcony, an apartment.','Verwende the für etwas Bestimmtes oder bereits Erwähntes: the balcony.','Bei allgemeinen Pluralformen und nicht zählbaren Nomen kein Artikel: rooms, coffee.','Mit there is/are sagst du, dass etwas vorhanden ist: There is a shop.','Mit it beziehst du dich auf eine erwähnte Sache, mit they auf mehrere: It is small; They are small.','Für Wetter und Uhrzeit verwende it: It is sunny; It is seven o’clock.','Prototyp · 15 A1-Lektionen · der restliche Kurs wird entwickelt.'],
 fr:['Décrire les personnes','Utilisez des adjectifs pour décrire les personnes et les sentiments.','Mon appartement et les articles','Choisissez a/an, the ou aucun article.','La vie dans un village','Utilisez there pour présenter une chose, puis it pour la décrire.','Placez l’adjectif avant le nom : a kind person.','Après be et feel, employez un adjectif : Alex is kind; Anna feels happy.','Les adjectifs ne changent pas au pluriel : kind people.','Employez a/an à la première mention d’un nom dénombrable singulier : a balcony, an apartment.','Employez the pour une chose précise ou déjà mentionnée : the balcony.','Pas d’article pour les pluriels et les indénombrables en général : rooms, coffee.','There is/are indique qu’une chose existe : There is a shop.','Reprenez une chose déjà mentionnée avec it et plusieurs avec they : It is small; They are small.','Employez it pour la météo et l’heure : It is sunny; It is seven o’clock.','Prototype · 15 leçons A1 · la suite du cours est en préparation.'],
 it:['Descrivere le persone','Usa gli aggettivi per descrivere persone e sentimenti.','Il mio appartamento e gli articoli','Scegli a/an, the o nessun articolo.','Vivere in un villaggio','Usa there per introdurre qualcosa e it per descriverlo.','Metti l’aggettivo prima del nome: a kind person.','Usa un aggettivo dopo be e feel: Alex is kind; Anna feels happy.','Gli aggettivi non cambiano al plurale: kind people.','Usa a/an alla prima menzione di un nome numerabile singolare: a balcony, an apartment.','Usa the per qualcosa di specifico o già menzionato: the balcony.','Nessun articolo per plurali e non numerabili in generale: rooms, coffee.','Usa there is/are per dire che qualcosa esiste: There is a shop.','Usa it per una cosa già citata e they per più cose: It is small; They are small.','Usa it per il meteo e l’ora: It is sunny; It is seven o’clock.','Prototipo · 15 lezioni A1 · il resto del corso è in preparazione.'],
 hy:['Նկարագրել մարդկանց','Ածականներով նկարագրեք մարդկանց և զգացմունքները։','Իմ բնակարանը և հոդերը','Ընտրեք a/an, the կամ առանց հոդի տարբերակը։','Կյանքը գյուղում','Նոր առարկան նշեք there-ով, ապա նկարագրեք it-ով։','Ածականը դրեք գոյականից առաջ՝ a kind person.','be և feel բայերից հետո դրեք ածական՝ Alex is kind; Anna feels happy.','Հոգնակիի դեպքում ածականը չի փոխվում՝ kind people.','Եզակի հաշվելի գոյականի առաջին հիշատակման դեպքում օգտագործեք a/an՝ a balcony, an apartment.','Հայտնի կամ արդեն հիշատակված առարկայի համար օգտագործեք the՝ the balcony.','Ընդհանուր հոգնակի և անհաշվելի բառերի հետ հոդ պետք չէ՝ rooms, coffee.','Գոյությունը նշելու համար օգտագործեք there is/are՝ There is a shop.','Արդեն հիշատակված մեկ առարկայի համար օգտագործեք it, մի քանիսի համար՝ they՝ It is small; They are small.','Եղանակի և ժամի համար օգտագործեք it՝ It is sunny; It is seven o’clock.','Նախատիպ · A1-ի 15 դաս · մնացած դասերը մշակվում են։'],
 'zh-Hans':['描述人物','用形容词描述人物和感受。','我的公寓与冠词','选择 a/an、the 或不用冠词。','乡村生活','先用 there 引出事物，再用 it 描述它。','形容词放在名词前：a kind person。','be 和 feel 后使用形容词：Alex is kind; Anna feels happy。','复数形式不改变形容词：kind people。','首次提到单数可数名词时使用 a/an：a balcony, an apartment。','特指或再次提及时使用 the：the balcony。','泛指复数或不可数名词时不用冠词：rooms, coffee。','用 there is/are 表示某物存在：There is a shop。','已提到的一个事物用 it，多个用 they：It is small; They are small。','天气和时间用 it：It is sunny; It is seven o’clock。','体验版 · 15 节 A1 课程 · 其余课程正在制作中。'],
 ja:['人を描写する','形容詞で人柄や気持ちを表します。','私のアパートと冠詞','a/an、the、冠詞なしを選びます。','村での暮らし','there で存在を紹介し、it でそれを説明します。','形容詞は名詞の前に置きます：a kind person。','be と feel の後には形容詞を使います：Alex is kind; Anna feels happy。','複数でも形容詞の形は変わりません：kind people。','単数の数えられる名詞を初めて述べるときは a/an：a balcony, an apartment。','特定のものや既出のものには the：the balcony。','一般的な複数名詞や数えられない名詞には冠詞を付けません：rooms, coffee。','存在を表すには there is/are：There is a shop。','既出の一つのものには it、複数には they：It is small; They are small。','天気や時刻には it：It is sunny; It is seven o’clock。','試作版 · A1 の15レッスン · 続きは制作中です。'],
 ko:['사람 묘사하기','형용사로 사람과 감정을 묘사합니다.','우리 집과 관사','a/an, the 또는 관사 없음을 고릅니다.','마을 생활','there로 대상을 소개하고 it으로 설명합니다.','형용사는 명사 앞에 옵니다: a kind person.','be와 feel 뒤에는 형용사를 씁니다: Alex is kind; Anna feels happy.','복수여도 형용사는 변하지 않습니다: kind people.','셀 수 있는 단수 명사를 처음 말할 때 a/an을 씁니다: a balcony, an apartment.','특정하거나 앞서 말한 대상에는 the를 씁니다: the balcony.','일반적인 복수나 셀 수 없는 명사에는 관사가 없습니다: rooms, coffee.','존재를 말할 때 there is/are를 씁니다: There is a shop.','앞서 말한 하나는 it, 여러 개는 they로 받습니다: It is small; They are small.','날씨와 시간에는 it을 씁니다: It is sunny; It is seven o’clock.','프로토타입 · A1 15강 · 나머지 과정은 준비 중입니다.'],
 hi:['लोगों का वर्णन','लोगों और भावनाओं का वर्णन विशेषण से करें।','मेरा अपार्टमेंट और आर्टिकल','a/an, the या बिना आर्टिकल के सही रूप चुनें।','गाँव में जीवन','पहली बार बताने के लिए there, फिर वर्णन के लिए it इस्तेमाल करें।','विशेषण संज्ञा से पहले आता है: a kind person.','be और feel के बाद विशेषण आता है: Alex is kind; Anna feels happy.','बहुवचन में विशेषण नहीं बदलता: kind people.','एकवचन गिनने योग्य संज्ञा का पहली बार ज़िक्र हो तो a/an लगाएँ: a balcony, an apartment.','विशिष्ट या पहले बताई चीज़ के लिए the लगाएँ: the balcony.','सामान्य बहुवचन और अगणनीय शब्दों के साथ आर्टिकल नहीं: rooms, coffee.','किसी चीज़ के होने के लिए there is/are: There is a shop.','पहले बताई एक चीज़ के लिए it, कई के लिए they: It is small; They are small.','मौसम और समय के लिए it: It is sunny; It is seven o’clock.','प्रोटोटाइप · A1 के 15 पाठ · बाकी पाठ तैयार किए जा रहे हैं।'],
 bn:['মানুষের বর্ণনা','বিশেষণ দিয়ে মানুষ ও অনুভূতি বর্ণনা করুন।','আমার অ্যাপার্টমেন্ট ও আর্টিকেল','a/an, the অথবা আর্টিকেল ছাড়াই সঠিক রূপ বাছুন।','গ্রামের জীবন','প্রথমে there দিয়ে কিছু পরিচয় করান, পরে it দিয়ে বর্ণনা করুন।','বিশেষণ বিশেষ্যের আগে বসে: a kind person.','be ও feel-এর পরে বিশেষণ বসে: Alex is kind; Anna feels happy.','বহুবচনে বিশেষণ বদলায় না: kind people.','গণনাযোগ্য একবচন বিশেষ্য প্রথমবার উল্লেখে a/an ব্যবহার করুন: a balcony, an apartment.','নির্দিষ্ট বা আগে উল্লেখ করা কিছুর জন্য the ব্যবহার করুন: the balcony.','সাধারণ বহুবচন বা অগণনীয় বিশেষ্যে আর্টিকেল লাগে না: rooms, coffee.','কিছুর অস্তিত্ব বোঝাতে there is/are: There is a shop.','আগে বলা একটি জিনিসে it, একাধিক হলে they: It is small; They are small.','আবহাওয়া ও সময় বলতে it ব্যবহার করুন: It is sunny; It is seven o’clock.','প্রোটোটাইপ · A1-এর ১৫টি পাঠ · বাকি পাঠ তৈরি হচ্ছে।'],
 ur:['لوگوں کی وضاحت','لوگوں اور احساسات کی وضاحت صفت سے کریں۔','میرا اپارٹمنٹ اور آرٹیکل','a/an، the یا بغیر آرٹیکل کے درست شکل چنیں۔','گاؤں کی زندگی','کسی چیز کو متعارف کرانے کے لیے there اور پھر بیان کے لیے it استعمال کریں۔','صفت اسم سے پہلے آتی ہے: a kind person.','be اور feel کے بعد صفت آتی ہے: Alex is kind; Anna feels happy.','جمع میں صفت کی شکل نہیں بدلتی: kind people.','قابلِ شمار واحد اسم کا پہلی بار ذکر ہو تو a/an لگائیں: a balcony, an apartment.','مخصوص یا پہلے مذکور چیز کے لیے the لگائیں: the balcony.','عام جمع یا ناقابلِ شمار اسم کے ساتھ آرٹیکل نہیں آتا: rooms, coffee.','کسی چیز کے موجود ہونے کے لیے there is/are: There is a shop.','پہلے مذکور ایک چیز کے لیے it، کئی چیزوں کے لیے they: It is small; They are small.','موسم اور وقت کے لیے it استعمال کریں: It is sunny; It is seven o’clock.','نمونہ · A1 کے ۱۵ اسباق · باقی کورس تیار ہو رہا ہے۔'],
 ar:['وصف الأشخاص','استخدم الصفات لوصف الأشخاص والمشاعر.','شقتي وأدوات التعريف','اختر a/an أو the أو بلا أداة.','الحياة في قرية','استخدم there لتقديم شيء ثم it لوصفه.','تأتي الصفة قبل الاسم: a kind person.','تأتي الصفة بعد be وfeel: Alex is kind; Anna feels happy.','لا تتغير الصفة في الجمع: kind people.','استخدم a/an عند ذكر اسم مفرد معدود لأول مرة: a balcony, an apartment.','استخدم the لشيء محدد أو ذُكر من قبل: the balcony.','لا تستخدم أداة مع الجمع العام أو الاسم غير المعدود: rooms, coffee.','استخدم there is/are لبيان وجود شيء: There is a shop.','استخدم it لشيء واحد سبق ذكره وthey لأشياء متعددة: It is small; They are small.','استخدم it للطقس والوقت: It is sunny; It is seven o’clock.','نسخة تجريبية · 15 درسًا في A1 · بقية الدورة قيد الإعداد.'],
 id:['Mendeskripsikan orang','Gunakan kata sifat untuk orang dan perasaan.','Apartemen saya dan artikel','Pilih a/an, the, atau tanpa artikel.','Hidup di desa','Gunakan there untuk mengenalkan sesuatu, lalu it untuk menjelaskannya.','Letakkan kata sifat sebelum kata benda: a kind person.','Gunakan kata sifat sesudah be dan feel: Alex is kind; Anna feels happy.','Kata sifat tidak berubah dalam bentuk jamak: kind people.','Gunakan a/an saat pertama menyebut kata benda tunggal yang dapat dihitung: a balcony, an apartment.','Gunakan the untuk sesuatu yang khusus atau sudah disebut: the balcony.','Tanpa artikel untuk bentuk jamak atau tak terhitung secara umum: rooms, coffee.','Gunakan there is/are untuk menyatakan keberadaan: There is a shop.','Gunakan it untuk satu hal yang sudah disebut, they untuk beberapa: It is small; They are small.','Gunakan it untuk cuaca dan waktu: It is sunny; It is seven o’clock.','Prototipe · 15 pelajaran A1 · sisa kursus sedang disiapkan.'],
 tr:['İnsanları betimleme','İnsanları ve duyguları sıfatlarla anlatın.','Dairem ve artikeller','a/an, the veya artikelsiz biçimi seçin.','Köy yaşamı','Bir şeyi tanıtmak için there, anlatmak için it kullanın.','Sıfat isimden önce gelir: a kind person.','be ve feel fiillerinden sonra sıfat kullanın: Alex is kind; Anna feels happy.','Sıfat çoğulda değişmez: kind people.','Tekil sayılabilir bir adı ilk kez söylerken a/an kullanın: a balcony, an apartment.','Belirli veya daha önce söylenmiş bir şey için the kullanın: the balcony.','Genel çoğul ve sayılamayan isimlerde artikel kullanmayın: rooms, coffee.','Bir şeyin varlığını belirtmek için there is/are: There is a shop.','Daha önce söylenen bir şey için it, birden fazlası için they: It is small; They are small.','Hava ve saat için it kullanın: It is sunny; It is seven o’clock.','Prototip · 15 A1 dersi · kursun kalanı hazırlanıyor.'],
 vi:['Miêu tả con người','Dùng tính từ để miêu tả con người và cảm xúc.','Căn hộ của tôi và mạo từ','Chọn a/an, the hoặc không dùng mạo từ.','Cuộc sống ở làng','Dùng there để giới thiệu sự vật, rồi it để miêu tả.','Đặt tính từ trước danh từ: a kind person.','Dùng tính từ sau be và feel: Alex is kind; Anna feels happy.','Tính từ không đổi ở số nhiều: kind people.','Dùng a/an khi lần đầu nhắc đến danh từ đếm được số ít: a balcony, an apartment.','Dùng the cho vật cụ thể hoặc đã nhắc đến: the balcony.','Không dùng mạo từ với số nhiều hay danh từ không đếm được nói chung: rooms, coffee.','Dùng there is/are để nói một vật tồn tại: There is a shop.','Dùng it cho một vật đã nhắc đến, they cho nhiều vật: It is small; They are small.','Dùng it khi nói thời tiết và thời gian: It is sunny; It is seven o’clock.','Bản thử nghiệm · 15 bài A1 · phần còn lại đang được phát triển.'],
 kk:['Адамдарды сипаттау','Адамдар мен сезімдерді сын есіммен сипаттаңыз.','Менің пәтерім және артикльдер','a/an, the немесе артикльсіз нұсқаны таңдаңыз.','Ауыл өмірі','Бір нәрсені алғаш айтуға there, сипаттауға it қолданыңыз.','Сын есім зат есімнің алдында тұрады: a kind person.','be және feel сөздерінен кейін сын есім қолданыңыз: Alex is kind; Anna feels happy.','Көпше түрде сын есім өзгермейді: kind people.','Жекеше саналатын зат есімді алғаш атағанда a/an қолданыңыз: a balcony, an apartment.','Нақты немесе бұрын аталған нәрсе үшін the қолданыңыз: the balcony.','Жалпы көпше және саналмайтын зат есімдермен артикль қоймаңыз: rooms, coffee.','Бар екенін айту үшін there is/are қолданыңыз: There is a shop.','Бұрын айтылған бір нәрсеге it, бірнешеуіне they қолданыңыз: It is small; They are small.','Ауа райы мен уақытқа it қолданыңыз: It is sunny; It is seven o’clock.','Прототип · A1 деңгейінің 15 сабағы · қалған курс әзірленуде.'],
 uz:['Odamlarni tasvirlash','Odamlar va hislarni sifatlar bilan tasvirlang.','Mening kvartiram va artikllar','a/an, the yoki artiklsiz shaklni tanlang.','Qishloq hayoti','Biror narsani tanishtirish uchun there, keyin tasvirlash uchun it ishlating.','Sifat ot oldida keladi: a kind person.','be va feel dan keyin sifat ishlating: Alex is kind; Anna feels happy.','Ko‘plikda sifat o‘zgarmaydi: kind people.','Sanasa bo‘ladigan birlik ot birinchi marta aytilganda a/an ishlating: a balcony, an apartment.','Aniq yoki oldin aytilgan narsa uchun the ishlating: the balcony.','Umumiy ko‘plik va sanalmaydigan otlarda artikl ishlatmang: rooms, coffee.','Biror narsa borligini aytish uchun there is/are: There is a shop.','Oldin aytilgan bitta narsa uchun it, ko‘plari uchun they: It is small; They are small.','Ob-havo va vaqt uchun it ishlating: It is sunny; It is seven o’clock.','Prototip · A1 uchun 15 dars · qolgan kurs tayyorlanmoqda.']
};
for(const [code,strings] of Object.entries(nextWords)){
 if(strings.length!==nextKeys.length||!I.ui[code])throw Error('Missing A1 lesson 13–15 translation: '+code);
 Object.assign(I.ui[code],Object.fromEntries(nextKeys.map((key,index)=>[key,strings[index]])));
}
})(typeof globalThis==='object'?globalThis:this);
