(function(root){
'use strict';
const I=root.EvoCourseI18n;if(!I)return;
// Order: lesson titles/goals, grammar explanations, pilot note, microphone UI.
const keys=['l7','g7','l8','g8','l9','g9','aAn','pluralNouns','possessiveAdjectives','thereIsAre','placeWords','pilot','micPrompt','playModel','startMic','micListening','heardWords','micPassed','micRetry','micUnavailable','speechNotice','skipSpeech'];
const words={
 en:[
  'Jobs and articles','Talk about a job using a/an and plural nouns.','My family','Describe your family with my, his, her and our.','My room','Say what is in a room and where things are.',
  'Use a before a consonant sound and an before a vowel sound: a barista, an assistant.','For more than one, use plural -s/-es without a/an: tables, sandwiches.','Use my with I, his with he, her with she, and our with we. Put them before a noun.','Use there is for one thing and there are for two or more. Ask Is there…? or Are there…?','Use next to for beside, in the corner for an indoor corner, and on for a surface.',
  'Prototype · 9 A1 lessons · the rest of the course is in development.','Say this sentence','Hear an example','Start microphone','Listening…','Recognized:','The words were recognized.','Some words were not recognized. Listen and try again.','Recognition is unavailable or microphone access was denied. You can continue.','This checks recognized words, not individual sounds. Your browser may send audio to an online speech service.','Continue without microphone'],
 ru:[
  'Профессии и артикли','Расскажите о работе, используя a/an и множественное число.','Моя семья','Опишите семью с помощью my, his, her и our.','Моя комната','Расскажите, что есть в комнате и где находятся предметы.',
  'Перед согласным звуком ставьте a, перед гласным — an: a barista, an assistant.','Для нескольких предметов используйте -s/-es без a/an: tables, sandwiches.','С I используйте my, с he — his, с she — her, с we — our. Ставьте их перед существительным.','Для одного предмета используйте there is, для двух и более — there are. Вопросы: Is there…? / Are there…?','Next to значит «рядом», in the corner — «в углу комнаты», on — «на поверхности».',
  'Прототип · 9 уроков A1 · остальная часть курса в разработке.','Произнесите предложение','Прослушать образец','Включить микрофон','Слушаю…','Распознано:','Слова распознаны.','Некоторые слова не распознаны. Прослушайте и попробуйте ещё раз.','Распознавание недоступно или доступ к микрофону запрещён. Можно продолжить.','Проверяются распознанные слова, а не отдельные звуки. Браузер может отправлять аудио в онлайн-сервис распознавания.','Продолжить без микрофона'],
 es:[
  'Trabajos y artículos','Habla de un trabajo usando a/an y sustantivos en plural.','Mi familia','Describe a tu familia con my, his, her y our.','Mi habitación','Di qué hay en una habitación y dónde están las cosas.',
  'Usa a antes de un sonido consonántico y an antes de uno vocálico: a barista, an assistant.','Para más de uno, usa el plural -s/-es sin a/an: tables, sandwiches.','Usa my con I, his con he, her con she y our con we. Colócalos antes de un sustantivo.','Usa there is para una cosa y there are para dos o más. Pregunta: Is there…? / Are there…?','Usa next to para junto a, in the corner para en una esquina interior y on para una superficie.',
  'Prototipo · 9 lecciones A1 · el resto del curso está en desarrollo.','Di esta frase','Escuchar un ejemplo','Activar micrófono','Escuchando…','Reconocido:','Se reconocieron las palabras.','No se reconocieron algunas palabras. Escucha e inténtalo de nuevo.','El reconocimiento no está disponible o se denegó el micrófono. Puedes continuar.','Se comprueban las palabras reconocidas, no los sonidos individuales. El navegador puede enviar audio a un servicio en línea.','Continuar sin micrófono'],
 pt:[
  'Profissões e artigos','Fale sobre um trabalho usando a/an e substantivos no plural.','Minha família','Descreva a família usando my, his, her e our.','Meu quarto','Diga o que há num quarto e onde estão as coisas.',
  'Use a antes de som consonantal e an antes de som vocálico: a barista, an assistant.','Para mais de um, use o plural -s/-es sem a/an: tables, sandwiches.','Use my com I, his com he, her com she e our com we. Coloque-os antes do substantivo.','Use there is para uma coisa e there are para duas ou mais. Pergunte: Is there…? / Are there…?','Use next to para ao lado de, in the corner para no canto e on para uma superfície.',
  'Protótipo · 9 aulas A1 · o restante do curso está em desenvolvimento.','Diga esta frase','Ouvir um exemplo','Ativar microfone','Ouvindo…','Reconhecido:','As palavras foram reconhecidas.','Algumas palavras não foram reconhecidas. Ouça e tente novamente.','O reconhecimento não está disponível ou o microfone foi negado. Você pode continuar.','A verificação compara palavras reconhecidas, não sons individuais. O navegador pode enviar áudio a um serviço online.','Continuar sem microfone'],
 de:[
  'Berufe und Artikel','Sprich über einen Beruf mit a/an und Nomen im Plural.','Meine Familie','Beschreibe deine Familie mit my, his, her und our.','Mein Zimmer','Sage, was sich in einem Zimmer befindet und wo die Dinge sind.',
  'Verwende a vor einem Konsonantenlaut und an vor einem Vokallaut: a barista, an assistant.','Bei mehreren Dingen verwende den Plural -s/-es ohne a/an: tables, sandwiches.','Verwende my zu I, his zu he, her zu she und our zu we. Sie stehen vor dem Nomen.','Verwende there is für eine Sache und there are für mehrere. Frage: Is there…? / Are there…?','Next to bedeutet neben, in the corner in der Zimmerecke und on auf einer Oberfläche.',
  'Prototyp · 9 A1-Lektionen · der Rest des Kurses wird entwickelt.','Sprich diesen Satz','Beispiel anhören','Mikrofon einschalten','Ich höre zu…','Erkannt:','Die Wörter wurden erkannt.','Einige Wörter wurden nicht erkannt. Hör zu und versuche es erneut.','Spracherkennung ist nicht verfügbar oder der Mikrofonzugriff wurde verweigert. Du kannst fortfahren.','Geprüft werden erkannte Wörter, nicht einzelne Laute. Der Browser kann Audio an einen Onlinedienst senden.','Ohne Mikrofon fortfahren'],
 fr:[
  'Métiers et articles','Parle d’un métier avec a/an et des noms au pluriel.','Ma famille','Décris ta famille avec my, his, her et our.','Ma chambre','Dis ce qu’il y a dans une pièce et où se trouvent les objets.',
  'Utilise a devant un son consonne et an devant un son voyelle : a barista, an assistant.','Pour plusieurs objets, utilise le pluriel -s/-es sans a/an : tables, sandwiches.','Utilise my avec I, his avec he, her avec she et our avec we. Place-les avant le nom.','Utilise there is pour une chose et there are pour plusieurs. Questions : Is there…? / Are there…?','Next to signifie à côté de, in the corner dans un coin de la pièce et on sur une surface.',
  'Prototype · 9 leçons A1 · la suite du cours est en préparation.','Prononce cette phrase','Écouter un exemple','Activer le micro','Écoute en cours…','Reconnu :','Les mots ont été reconnus.','Certains mots n’ont pas été reconnus. Écoute et réessaie.','La reconnaissance est indisponible ou l’accès au micro a été refusé. Tu peux continuer.','La vérification compare les mots reconnus, pas chaque son. Le navigateur peut envoyer l’audio à un service en ligne.','Continuer sans micro'],
 it:[
  'Lavori e articoli','Parla di un lavoro usando a/an e nomi plurali.','La mia famiglia','Descrivi la tua famiglia con my, his, her e our.','La mia stanza','Di’ cosa c’è in una stanza e dove sono gli oggetti.',
  'Usa a prima di un suono consonantico e an prima di un suono vocalico: a barista, an assistant.','Per più oggetti usa il plurale -s/-es senza a/an: tables, sandwiches.','Usa my con I, his con he, her con she e our con we. Mettili prima del nome.','Usa there is per una cosa e there are per due o più. Domande: Is there…? / Are there…?','Next to significa accanto a, in the corner nell’angolo della stanza e on su una superficie.',
  'Prototipo · 9 lezioni A1 · il resto del corso è in preparazione.','Pronuncia questa frase','Ascolta un esempio','Attiva microfono','In ascolto…','Riconosciuto:','Le parole sono state riconosciute.','Alcune parole non sono state riconosciute. Ascolta e riprova.','Il riconoscimento non è disponibile o l’accesso al microfono è negato. Puoi continuare.','Il controllo confronta le parole riconosciute, non i singoli suoni. Il browser può inviare l’audio a un servizio online.','Continua senza microfono'],
 hy:[
  'Մասնագիտություններ և հոդեր','Պատմեք աշխատանքի մասին՝ օգտագործելով a/an և հոգնակի գոյականներ։','Իմ ընտանիքը','Նկարագրեք ընտանիքը՝ օգտագործելով my, his, her և our։','Իմ սենյակը','Ասեք, թե ինչ կա սենյակում և որտեղ են իրերը։',
  'Բաղաձայն հնչյունից առաջ գործածեք a, ձայնավորից առաջ՝ an. a barista, an assistant։','Մեկից ավելի իրերի համար գործածեք -s/-es հոգնակին՝ առանց a/an. tables, sandwiches։','I-ի հետ գործածեք my, he-ի հետ՝ his, she-ի հետ՝ her, we-ի հետ՝ our։ Դրեք գոյականից առաջ։','Մեկ իրի համար գործածեք there is, մի քանիսի համար՝ there are։ Հարցեր՝ Is there…? / Are there…?','Next to նշանակում է կողքին, in the corner՝ սենյակի անկյունում, on՝ մակերեսի վրա։',
  'Նախատիպ · A1-ի 9 դաս · դասընթացի մնացած մասը մշակվում է։','Արտասանեք այս նախադասությունը','Լսել օրինակը','Միացնել խոսափողը','Լսում եմ…','Ճանաչված է՝','Բառերը ճանաչվեցին։','Որոշ բառեր չճանաչվեցին։ Լսեք և կրկին փորձեք։','Խոսքի ճանաչումն անհասանելի է կամ խոսափողի թույլտվությունը մերժվել է։ Կարող եք շարունակել։','Ստուգվում են ճանաչված բառերը, ոչ թե առանձին հնչյունները։ Դիտարկիչը կարող է ձայնը ուղարկել առցանց ծառայության։','Շարունակել առանց խոսափողի'],
 'zh-Hans':[
  '职业与冠词','用 a/an 和复数名词谈论职业。','我的家人','用 my、his、her 和 our 描述家人。','我的房间','说出房间里有什么，以及物品的位置。',
  '辅音音素前用 a，元音音素前用 an：a barista, an assistant。','多个物品用复数 -s/-es，不加 a/an：tables, sandwiches。','I 对应 my，he 对应 his，she 对应 her，we 对应 our；放在名词前。','一件物品用 there is，两件及以上用 there are。提问：Is there…? / Are there…?','next to 表示旁边，in the corner 表示房间角落，on 表示在表面上。',
  '预览版 · 9 节 A1 课程 · 其余课程正在制作中。','读出这个句子','听示范','开启麦克风','正在聆听…','识别结果：','句子中的词已识别。','部分词未识别。请听示范并重试。','语音识别不可用或麦克风权限被拒绝。你可以继续。','这里只核对识别出的词，不评估单个发音。浏览器可能将音频发送至在线语音服务。','不用麦克风继续'],
 ja:[
  '職業と冠詞','a/an と複数形を使って仕事について話します。','私の家族','my、his、her、our を使って家族を紹介します。','私の部屋','部屋にある物とその場所を説明します。',
  '子音の音の前は a、母音の音の前は an：a barista, an assistant。','複数には a/an を付けず、-s/-es を使います：tables, sandwiches。','I には my、he には his、she には her、we には our。名詞の前に置きます。','1つなら there is、2つ以上なら there are。質問は Is there…? / Are there…?','next to は隣、in the corner は部屋の隅、on は表面の上です。',
  '試作版 · A1 全9レッスン · 続きは制作中です。','この文を声に出しましょう','お手本を聞く','マイクを使う','聞き取り中…','認識結果：','単語を認識しました。','認識できない単語があります。お手本を聞いて再挑戦してください。','音声認識が使えないか、マイクの許可がありません。先に進めます。','認識した単語を照合します。個々の発音は評価しません。ブラウザーが音声をオンラインサービスに送る場合があります。','マイクなしで続ける'],
 ko:[
  '직업과 관사','a/an과 복수 명사를 사용해 직업을 말하세요.','우리 가족','my, his, her, our로 가족을 설명하세요.','내 방','방에 있는 물건과 위치를 설명하세요.',
  '자음 소리 앞에는 a, 모음 소리 앞에는 an을 씁니다: a barista, an assistant.','둘 이상이면 a/an 없이 복수형 -s/-es를 씁니다: tables, sandwiches.','I에는 my, he에는 his, she에는 her, we에는 our를 쓰고 명사 앞에 놓습니다.','하나에는 there is, 둘 이상에는 there are를 씁니다. 질문: Is there…? / Are there…?','next to는 옆, in the corner는 방의 구석, on은 표면 위를 뜻합니다.',
  '미리보기 · A1 9개 수업 · 나머지 과정은 제작 중입니다.','이 문장을 말해 보세요','예시 듣기','마이크 켜기','듣는 중…','인식 결과:','단어가 인식되었습니다.','일부 단어를 인식하지 못했습니다. 예시를 듣고 다시 시도하세요.','음성 인식을 사용할 수 없거나 마이크 접근이 거부되었습니다. 계속할 수 있습니다.','인식된 단어만 확인하며 개별 발음은 평가하지 않습니다. 브라우저가 오디오를 온라인 서비스에 보낼 수 있습니다.','마이크 없이 계속'],
 hi:[
  'पेशे और आर्टिकल','a/an और बहुवचन संज्ञाओं से नौकरी के बारे में बताएं।','मेरा परिवार','my, his, her और our से परिवार का वर्णन करें।','मेरा कमरा','कमरे में क्या है और चीज़ें कहाँ हैं, बताएं।',
  'व्यंजन ध्वनि से पहले a और स्वर ध्वनि से पहले an लगाएं: a barista, an assistant।','एक से अधिक चीज़ों के लिए a/an के बिना -s/-es बहुवचन लगाएं: tables, sandwiches।','I के साथ my, he के साथ his, she के साथ her और we के साथ our लगाएं। इन्हें संज्ञा से पहले रखें।','एक चीज़ के लिए there is और दो या अधिक के लिए there are लगाएं। प्रश्न: Is there…? / Are there…?','next to का अर्थ बगल में, in the corner कमरे के कोने में और on सतह पर है।',
  'प्रोटोटाइप · A1 के 9 पाठ · बाकी पाठ तैयार किए जा रहे हैं।','यह वाक्य बोलें','नमूना सुनें','माइक्रोफ़ोन चालू करें','सुन रहा है…','पहचाने गए शब्द:','शब्द पहचान लिए गए।','कुछ शब्द नहीं पहचाने गए। नमूना सुनकर फिर कोशिश करें।','वाणी पहचान उपलब्ध नहीं है या माइक्रोफ़ोन की अनुमति नहीं मिली। आप आगे बढ़ सकते हैं।','यह पहचाने गए शब्दों की जाँच है, अलग-अलग ध्वनियों की नहीं। ब्राउज़र ऑडियो ऑनलाइन सेवा को भेज सकता है।','माइक्रोफ़ोन के बिना आगे बढ़ें'],
 bn:[
  'পেশা ও আর্টিকেল','a/an ও বহুবচন বিশেষ্য ব্যবহার করে কাজের কথা বলুন।','আমার পরিবার','my, his, her ও our দিয়ে পরিবার বর্ণনা করুন।','আমার ঘর','ঘরে কী আছে এবং কোথায় আছে তা বলুন।',
  'ব্যঞ্জনধ্বনির আগে a, স্বরধ্বনির আগে an ব্যবহার করুন: a barista, an assistant।','একাধিক জিনিসে a/an ছাড়া -s/-es বহুবচন ব্যবহার করুন: tables, sandwiches।','I-এর সঙ্গে my, he-এর সঙ্গে his, she-এর সঙ্গে her, we-এর সঙ্গে our বসে; বিশেষ্যের আগে লিখুন।','একটির জন্য there is, একাধিকের জন্য there are। প্রশ্ন: Is there…? / Are there…?','next to মানে পাশে, in the corner মানে ঘরের কোণে, on মানে কোনো পৃষ্ঠের ওপর।',
  'প্রোটোটাইপ · A1-এর ৯টি পাঠ · বাকি কোর্স তৈরি হচ্ছে।','এই বাক্যটি বলুন','নমুনা শুনুন','মাইক্রোফোন চালু করুন','শুনছি…','শনাক্ত হয়েছে:','শব্দগুলো শনাক্ত হয়েছে।','কিছু শব্দ শনাক্ত হয়নি। নমুনা শুনে আবার চেষ্টা করুন।','কথা শনাক্তকরণ উপলব্ধ নয় বা মাইক্রোফোনের অনুমতি মেলেনি। আপনি এগোতে পারেন।','এখানে শনাক্ত শব্দ মিলিয়ে দেখা হয়, আলাদা উচ্চারণ নয়। ব্রাউজার অডিও অনলাইন সেবায় পাঠাতে পারে।','মাইক্রোফোন ছাড়া এগিয়ে যান'],
 ur:[
  'پیشے اور آرٹیکل','a/an اور جمع اسموں سے ملازمت کے بارے میں بات کریں۔','میرا خاندان','my، his، her اور our سے خاندان بیان کریں۔','میرا کمرہ','بتائیں کمرے میں کیا ہے اور چیزیں کہاں ہیں۔',
  'حرفِ صحیح کی آواز سے پہلے a اور حرفِ علت کی آواز سے پہلے an استعمال کریں: a barista, an assistant۔','ایک سے زیادہ چیزوں کے لیے a/an کے بغیر جمع -s/-es لگائیں: tables, sandwiches۔','I کے ساتھ my، he کے ساتھ his، she کے ساتھ her اور we کے ساتھ our لگائیں؛ انہیں اسم سے پہلے رکھیں۔','ایک چیز کے لیے there is اور دو یا زیادہ کے لیے there are؛ سوال: Is there…? / Are there…?','next to کا مطلب پاس، in the corner کمرے کے کونے میں اور on کسی سطح پر ہے۔',
  'ابتدائی نمونہ · A1 کے 9 اسباق · باقی کورس تیار ہو رہا ہے۔','یہ جملہ بولیں','نمونہ سنیں','مائیکروفون آن کریں','سن رہا ہے…','پہچانے گئے الفاظ:','الفاظ پہچان لیے گئے۔','کچھ الفاظ نہیں پہچانے گئے۔ نمونہ سن کر دوبارہ کوشش کریں۔','آواز کی شناخت دستیاب نہیں یا مائیکروفون کی اجازت نہیں ملی۔ آپ آگے بڑھ سکتے ہیں۔','یہ پہچانے گئے الفاظ ملاتا ہے، ہر آواز کی ادائیگی نہیں جانچتا۔ براؤزر آڈیو آن لائن سروس کو بھیج سکتا ہے۔','مائیکروفون کے بغیر آگے بڑھیں'],
 ar:[
  'المهن وأدوات التنكير','تحدث عن وظيفة باستخدام a/an والأسماء في الجمع.','عائلتي','صِف عائلتك باستخدام my وhis وher وour.','غرفتي','قل ما الموجود في الغرفة وأين توجد الأشياء.',
  'استخدم a قبل الصوت الساكن وan قبل الصوت المتحرك: a barista, an assistant.','لأكثر من شيء، استخدم صيغة الجمع -s/-es دون a/an: tables, sandwiches.','استخدم my مع I، وhis مع he، وher مع she، وour مع we. ضعها قبل الاسم.','استخدم there is لشيء واحد وthere are لشيئين أو أكثر. السؤال: Is there…? / Are there…?','تعني next to بجانب، وin the corner في زاوية الغرفة، وon على سطح.',
  'نسخة تجريبية · 9 دروس A1 · بقية الدورة قيد الإعداد.','انطق هذه الجملة','استمع إلى النموذج','شغّل الميكروفون','جارٍ الاستماع…','ما تم التعرف عليه:','تم التعرف على الكلمات.','لم يتم التعرف على بعض الكلمات. استمع وحاول مجددًا.','التعرف على الكلام غير متاح أو رُفض إذن الميكروفون. يمكنك المتابعة.','يُقارن هذا الكلمات المتعرّف عليها، ولا يقيّم كل صوت. قد يرسل المتصفح الصوت إلى خدمة عبر الإنترنت.','المتابعة دون ميكروفون'],
 id:[
  'Pekerjaan dan artikel','Bicarakan pekerjaan memakai a/an dan kata benda jamak.','Keluarga saya','Jelaskan keluarga dengan my, his, her, dan our.','Kamar saya','Katakan apa yang ada di kamar dan letak benda-bendanya.',
  'Gunakan a sebelum bunyi konsonan dan an sebelum bunyi vokal: a barista, an assistant.','Untuk lebih dari satu benda, gunakan bentuk jamak -s/-es tanpa a/an: tables, sandwiches.','Gunakan my untuk I, his untuk he, her untuk she, dan our untuk we. Letakkan sebelum kata benda.','Gunakan there is untuk satu benda dan there are untuk dua atau lebih. Tanya: Is there…? / Are there…?','next to berarti di samping, in the corner di sudut ruangan, dan on di atas permukaan.',
  'Prototipe · 9 pelajaran A1 · sisanya sedang dibuat.','Ucapkan kalimat ini','Dengarkan contoh','Nyalakan mikrofon','Mendengarkan…','Terdengar:','Kata-kata berhasil dikenali.','Beberapa kata tidak dikenali. Dengarkan dan coba lagi.','Pengenalan suara tidak tersedia atau izin mikrofon ditolak. Anda dapat melanjutkan.','Yang diperiksa adalah kata yang dikenali, bukan setiap bunyi. Browser dapat mengirim audio ke layanan daring.','Lanjut tanpa mikrofon'],
 tr:[
  'Meslekler ve artikeller','a/an ve çoğul isimlerle bir işten söz et.','Ailem','Aileni my, his, her ve our ile anlat.','Odam','Odada neler olduğunu ve eşyaların yerini söyle.',
  'Ünsüz sesten önce a, ünlü sesten önce an kullan: a barista, an assistant.','Birden fazla şey için a/an kullanmadan -s/-es çoğulunu kur: tables, sandwiches.','I ile my, he ile his, she ile her, we ile our kullan. Bunları isimden önce koy.','Bir şey için there is, iki veya daha fazlası için there are kullan. Soru: Is there…? / Are there…?','next to yanında, in the corner odanın köşesinde, on ise bir yüzeyin üzerinde demektir.',
  'Prototip · 9 A1 dersi · kursun kalanı hazırlanıyor.','Bu cümleyi söyle','Örneği dinle','Mikrofonu aç','Dinleniyor…','Algılanan:','Kelimeler algılandı.','Bazı kelimeler algılanmadı. Dinleyip tekrar dene.','Konuşma tanıma kullanılamıyor veya mikrofon izni reddedildi. Devam edebilirsin.','Bu, algılanan kelimeleri karşılaştırır; tek tek sesleri değerlendirmez. Tarayıcı sesi çevrimiçi bir hizmete gönderebilir.','Mikrofonsuz devam et'],
 vi:[
  'Nghề nghiệp và mạo từ','Nói về một công việc bằng a/an và danh từ số nhiều.','Gia đình tôi','Miêu tả gia đình bằng my, his, her và our.','Phòng của tôi','Nói trong phòng có gì và các đồ vật ở đâu.',
  'Dùng a trước âm phụ âm, an trước âm nguyên âm: a barista, an assistant.','Với nhiều đồ vật, dùng số nhiều -s/-es và không dùng a/an: tables, sandwiches.','Dùng my với I, his với he, her với she, our với we. Đặt trước danh từ.','Dùng there is cho một vật, there are cho từ hai vật. Hỏi: Is there…? / Are there…?','next to là bên cạnh, in the corner là trong góc phòng, on là trên bề mặt.',
  'Bản thử · 9 bài A1 · phần còn lại đang được xây dựng.','Đọc câu này','Nghe mẫu','Bật micrô','Đang nghe…','Đã nhận dạng:','Các từ đã được nhận dạng.','Một số từ chưa được nhận dạng. Nghe mẫu và thử lại.','Nhận dạng giọng nói không khả dụng hoặc quyền micrô bị từ chối. Bạn vẫn có thể tiếp tục.','Bài này đối chiếu từ được nhận dạng, không chấm từng âm. Trình duyệt có thể gửi âm thanh tới dịch vụ trực tuyến.','Tiếp tục không dùng micrô'],
 kk:[
  'Мамандықтар мен артикльдер','a/an және көпше зат есімдерді қолданып жұмыс туралы айтыңыз.','Менің отбасым','Отбасыңызды my, his, her және our арқылы сипаттаңыз.','Менің бөлмем','Бөлмеде не барын және заттардың қайда тұрғанын айтыңыз.',
  'Дауыссыз дыбыстың алдында a, дауысты дыбыстың алдында an қолданыңыз: a barista, an assistant.','Бірнеше зат үшін a/an қоспай, -s/-es көпше түрін қолданыңыз: tables, sandwiches.','I сөзімен my, he сөзімен his, she сөзімен her, we сөзімен our қолданыңыз. Зат есімнің алдына қойыңыз.','Бір затқа there is, бірнеше затқа there are қолданыңыз. Сұрақ: Is there…? / Are there…?','next to — жанында, in the corner — бөлменің бұрышында, on — бетінде.',
  'Прототип · A1 деңгейінің 9 сабағы · қалған курс әзірленуде.','Осы сөйлемді айтыңыз','Үлгіні тыңдау','Микрофонды қосу','Тыңдап тұрмын…','Танылғаны:','Сөздер танылды.','Кейбір сөздер танылмады. Үлгіні тыңдап, қайталап көріңіз.','Сөйлеуді тану қолжетімсіз немесе микрофонға рұқсат берілмеді. Жалғастыра аласыз.','Бұл жеке дыбыстарды емес, танылған сөздерді салыстырады. Браузер аудионы онлайн қызметке жіберуі мүмкін.','Микрофонсыз жалғастыру'],
 uz:[
  'Kasblar va artikllar','a/an hamda ko‘plik otlari bilan ish haqida gapiring.','Mening oilam','Oilani my, his, her va our bilan tasvirlang.','Mening xonam','Xonada nima borligini va buyumlar qayerdaligini ayting.',
  'Undosh tovush oldidan a, unli tovush oldidan an ishlating: a barista, an assistant.','Bir nechta buyum uchun a/an siz -s/-es ko‘plik shaklini ishlating: tables, sandwiches.','I bilan my, he bilan his, she bilan her, we bilan our ishlating. Ularni ot oldiga qo‘ying.','Bitta buyum uchun there is, ikki yoki ko‘proq uchun there are ishlating. Savol: Is there…? / Are there…?','next to — yonida, in the corner — xonaning burchagida, on — sirt ustida.',
  'Prototip · A1 uchun 9 dars · qolgan kurs tayyorlanmoqda.','Bu gapni ayting','Namunani tinglash','Mikrofonni yoqish','Tinglanmoqda…','Tanilgan so‘zlar:','So‘zlar tanildi.','Ba’zi so‘zlar tanilmadi. Namunani tinglab, yana urinib ko‘ring.','Nutqni tanish imkoni yo‘q yoki mikrofonga ruxsat berilmadi. Davom etishingiz mumkin.','Bu alohida tovushlarni emas, tanilgan so‘zlarni solishtiradi. Brauzer audioni onlayn xizmatga yuborishi mumkin.','Mikrofonsiz davom etish'],
};
const timeoutText={
 en:'Nothing was recognized within 7 seconds. Try again.',
 ru:'За 7 секунд слова не распознаны. Попробуйте ещё раз.',
 es:'No se reconoció nada en 7 segundos. Inténtalo de nuevo.',
 pt:'Nada foi reconhecido em 7 segundos. Tente novamente.',
 de:'Innerhalb von 7 Sekunden wurde nichts erkannt. Versuche es erneut.',
 fr:'Aucun mot reconnu en 7 secondes. Réessayez.',
 it:'Nessuna parola riconosciuta entro 7 secondi. Riprova.',
 hy:'7 վայրկյանում ոչինչ չճանաչվեց։ Կրկին փորձեք։',
 'zh-Hans':'7 秒内未识别出词语。请重试。',
 ja:'7秒以内に単語を認識できませんでした。もう一度お試しください。',
 ko:'7초 동안 단어를 인식하지 못했습니다. 다시 시도하세요.',
 hi:'7 सेकंड में कोई शब्द पहचाना नहीं गया। फिर कोशिश करें।',
 bn:'৭ সেকেন্ডে কোনো শব্দ শনাক্ত হয়নি। আবার চেষ্টা করুন।',
 ur:'7 سیکنڈ میں کوئی لفظ نہیں پہچانا گیا۔ دوبارہ کوشش کریں۔',
 ar:'لم يتم التعرف على كلمات خلال 7 ثوانٍ. حاول مجددًا.',
 id:'Tidak ada kata yang dikenali dalam 7 detik. Coba lagi.',
 tr:'7 saniye içinde hiçbir kelime algılanmadı. Tekrar dene.',
 vi:'Không nhận dạng được từ nào trong 7 giây. Hãy thử lại.',
 kk:'7 секунд ішінде сөздер танылмады. Қайталап көріңіз.',
 uz:'7 soniya ichida hech bir so‘z tanilmadi. Qayta urinib ko‘ring.'
};
for(const [code,strings] of Object.entries(words)){if(strings.length!==keys.length||!timeoutText[code])throw Error('Missing course translation: '+code);Object.assign(I.ui[code],Object.fromEntries(keys.map((key,index)=>[key,strings[index]])),{micTimeout:timeoutText[code]});}
})(typeof globalThis==='object'?globalThis:this);
